souffle: include/souffle/profile/Tui.h File Reference
Tui.h File Reference
#include "souffle/profile/CellInterface.h"
#include "souffle/profile/HtmlGenerator.h"
#include "souffle/profile/Iteration.h"
#include "souffle/profile/OutputProcessor.h"
#include "souffle/profile/ProfileDatabase.h"
#include "souffle/profile/ProfileEvent.h"
#include "souffle/profile/ProgramRun.h"
#include "souffle/profile/Reader.h"
#include "souffle/profile/Relation.h"
#include "souffle/profile/Row.h"
#include "souffle/profile/Rule.h"
#include "souffle/profile/StringUtils.h"
#include "souffle/profile/Table.h"
#include "souffle/profile/UserInputReader.h"
#include "souffle/utility/MiscUtil.h"
#include <algorithm>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <iterator>
#include <map>
#include <memory>
#include <ratio>
#include <set>
#include <string>
#include <thread>
#include <unordered_map>
#include <utility>
#include <vector>
#include <dirent.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
Data Structures
class souffle::profile::Tui
struct souffle::profile::Tui::Usage
Namespaces
souffle
souffle::profile
Functions
void configuration ()
std::string genJson ()
std::stringstream & genJsonAtoms (std::stringstream &ss)
std::stringstream & genJsonConfiguration (std::stringstream &ss)
std::stringstream & souffle::genJsonRules (std::stringstream &ss, const std::string &name, size_t maxRows)
std::stringstream & souffle::genJsonUsage (std::stringstream &ss)
uint32_t getTermWidth ()
std::set< Usage > getUsageStats (size_t width=size_t(-1))
void graphBySize (std::vector< size_t > list)
void graphByTime (std::vector< std::chrono::microseconds > list)
static void help ()
void id (std::string col)
void iterRel (std::string c, std::string col)
void iterRul (std::string c, std::string col)
void memoryUsage (std::chrono::microseconds, std::chrono::microseconds, uint32_t height=20)
void memoryUsage (uint32_t height=20)
void outputHtml (std::string filename="profiler_html/")
void quit ()
void rel (size_t limit, bool showLimit=true)
void relRul (std::string str)
void rul (size_t limit, bool showLimit=true)
void setResultLimit (size_t limit)
void setupTabCompletion ()
void top ()
void updateDB ()
void usage (std::chrono::microseconds endTime, std::chrono::microseconds startTime, uint32_t height=20)
void usage (uint32_t height=20)
void usageRelation (std::string id)
void usageRule (std::string id)
void verAtoms (Table &atomTable, const std::string &ruleName="")
void verGraph (std::string c, std::string col)
void verRul (std::string str)
Variables
class souffle::profile::Tui souffle::profile::ss
Function Documentation
configuration()
void configuration ()
Definition at line 1009 of file Tui.h.
{
         std::cout << "Configuration" << '\n';
         printf("%30s      %s", "Key", "Value\n\n");
         for (auto& kvp :
                 ProfileEventSingleton::instance().getDB().getStringMap({"program", "configuration"})) {
             if (kvp.first == "") {
                 printf("%30s      %s\n", "Datalog input file", kvp.second.c_str());
                 continue;
             }
             printf("%30s      %s\n", kvp.first.c_str(), kvp.second.c_str());
         }
         std::cout << std::endl;
     }
References souffle::ProfileEventSingleton::instance(), and tinyformat::printf().
Referenced by souffle::profile::Tui::runCommand().
genJson()
std::string genJson ()
Definition at line 611 of file Tui.h.
{
         std::stringstream ss;
         genJsonTop(ss);
         ss << ",\n";
         genJsonRelations(ss, "topRel", 3);
         ss << ",\n";
         genJsonRules(ss, "topRul", 3);
         ss << ",\n";
         genJsonRelations(ss, "rel", relationTable.rows.size());
         ss << ",\n";
         genJsonRules(ss, "rul", ruleTable.rows.size());
         ss << ",\n";
         genJsonUsage(ss);
         ss << ",\n";
         genJsonConfiguration(ss);
         ss << ",\n";
         genJsonAtoms(ss);
         ss << '\n';
         ss << "};\n";
         return ss.str();
     }
References genJsonAtoms(), genJsonConfiguration(), souffle::profile::Tui::genJsonRelations(), souffle::genJsonRules(), souffle::profile::Tui::genJsonTop(), souffle::genJsonUsage(), souffle::profile::Tui::relationTable, souffle::profile::Table::rows, souffle::profile::Tui::ruleTable, and souffle::profile::ss.
Referenced by outputHtml().
genJsonAtoms()
std::stringstream& genJsonAtoms (std::stringstream & ss)
Definition at line 549 of file Tui.h.
{
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         auto comma = [&ss](bool& first, const std::string& delimiter = ", ") {
             if (!first) {
                 ss << delimiter;
             } else {
                 first = false;
             }
         };
         ss << R"_("atoms": {)_";
         bool firstRow = true;
         for (auto& relation : run->getRelationMap()) {
             // Get atoms for non-recursive rules
             for (auto& rule : relation.second->getRuleMap()) {
                 comma(firstRow, ", \n");
                 ss << '"' << rule.second->getId() << R"_(": [)_";
                 bool firstCol = true;
                 for (auto& atom : rule.second->getAtoms()) {
                     comma(firstCol);
                     std::string relationName = atom.identifier;
                     relationName = relationName.substr(0, relationName.find('('));
                     auto* relation = out.getProgramRun()->getRelation(relationName);
                     std::string relationSize = relation == nullptr ? "" : std::to_string(relation->size());
                     ss << '[';
                     ss << '"' << Tools::cleanJsonOut(Tools::cleanString(atom.rule)) << R"_(", )_";
                     ss << '"' << Tools::cleanJsonOut(atom.identifier) << R"_(", )_";
                     ss << relationSize << ", ";
                     ss << atom.frequency << ']';
                 }
                 ss << "]";
             }
             // Get atoms for recursive rules
             for (auto& iteration : relation.second->getIterations()) {
                 for (auto& rule : iteration->getRules()) {
                     comma(firstRow, ", \n");
                     ss << '"' << rule.second->getId() << R"_(": [)_";
                     bool firstCol = true;
                     for (auto& atom : rule.second->getAtoms()) {
                         comma(firstCol);
                         std::string relationName = atom.identifier;
                         relationName = relationName.substr(0, relationName.find('('));
                         auto* relation = out.getProgramRun()->getRelation(relationName);
                         std::string relationSize =
                                 relation == nullptr ? "" : std::to_string(relation->size());
                         ss << '[';
                         ss << '"' << Tools::cleanJsonOut(Tools::cleanString(atom.rule)) << R"_(", )_";
                         ss << '"' << Tools::cleanJsonOut(atom.identifier) << R"_(", )_";
                         ss << relationSize << ", ";
                         ss << atom.frequency << ']';
                     }
                     ss << "]";
                 }
             }
         }
         ss << '}';
         return ss;
     }
References souffle::profile::Tools::cleanJsonOut(), souffle::profile::Tools::cleanString(), souffle::profile::OutputProcessor::getProgramRun(), iteration, souffle::profile::Tui::out, relation, rule, and souffle::profile::ss.
Referenced by genJson().
genJsonConfiguration()
std::stringstream& genJsonConfiguration (std::stringstream & ss)
Definition at line 528 of file Tui.h.
{
         auto comma = [&ss](bool& first, const std::string& delimiter = ", ") {
             if (!first) {
                 ss << delimiter;
             } else {
                 first = false;
             }
         };
         // Add configuration key-value pairs
         ss << R"_("configuration": {)_";
         bool firstRow = true;
         for (auto& kvp :
                 ProfileEventSingleton::instance().getDB().getStringMap({"program", "configuration"})) {
             comma(firstRow);
             ss << '"' << kvp.first << R"_(": ")_" << Tools::cleanJsonOut(kvp.second) << '"';
         }
         ss << '}';
         return ss;
     }
References souffle::profile::Tools::cleanJsonOut(), souffle::ProfileEventSingleton::getDB(), souffle::ProfileEventSingleton::instance(), and souffle::profile::ss.
Referenced by genJson().
getTermWidth()
uint32_t getTermWidth () protected
Definition at line 1478 of file Tui.h.
{
         struct winsize w {};
         ioctl(0, TIOCGWINSZ, &w);
         uint32_t width = w.ws_col > 0 ? w.ws_col : 80;
         return width;
     }
Referenced by memoryUsage(), top(), and usage().
getUsageStats()
std::set<Usage> getUsageStats (size_t width = size_t(-1))
Definition at line 768 of file Tui.h.
{
         std::set<Usage> usages;
         DirectoryEntry* usageStats = dynamic_cast<DirectoryEntry*>(
                 ProfileEventSingleton::instance().getDB().lookupEntry({"program", "usage", "timepoint"}));
         if (usageStats == nullptr || usageStats->getKeys().size() < 2) {
             return usages;
         }
         std::chrono::microseconds endTime{};
         std::chrono::microseconds startTime{};
         std::chrono::microseconds timeStep{};
         // Translate the string ordered text usage stats to a time ordered binary form.
         std::set<Usage> allUsages;
         for (auto& currentKey : usageStats->getKeys()) {
             Usage currentUsage{};
             uint64_t cur = std::stoul(currentKey);
             currentUsage.time = std::chrono::duration<uint64_t, std::micro>(cur);
             cur = dynamic_cast<SizeEntry*>(
                     usageStats->readDirectoryEntry(currentKey)->readEntry("systemtime"))
                           ->getSize();
             currentUsage.systemtime = std::chrono::duration<uint64_t, std::micro>(cur);
             cur = dynamic_cast<SizeEntry*>(usageStats->readDirectoryEntry(currentKey)->readEntry("usertime"))
                           ->getSize();
             currentUsage.usertime = std::chrono::duration<uint64_t, std::micro>(cur);
             currentUsage.maxRSS =
                     dynamic_cast<SizeEntry*>(usageStats->readDirectoryEntry(currentKey)->readEntry("maxRSS"))
                             ->getSize();
             // Duplicate times are possible
             if (allUsages.find(currentUsage) != allUsages.end()) {
                 auto& existing = *allUsages.find(currentUsage);
                 currentUsage.systemtime = std::max(existing.systemtime, currentUsage.systemtime);
                 currentUsage.usertime = std::max(existing.usertime, currentUsage.usertime);
                 currentUsage.maxRSS = std::max(existing.maxRSS, currentUsage.maxRSS);
                 allUsages.erase(currentUsage);
             }
             allUsages.insert(currentUsage);
         }
         // cpu times aren't quite recorded in a monotonic way, so skip the invalid ones.
         for (auto it = ++allUsages.begin(); it != allUsages.end(); ++it) {
             auto previous = std::prev(it);
             if (it->usertime < previous->usertime || it->systemtime < previous->systemtime ||
                     it->time == previous->time) {
                 it = allUsages.erase(it);
                 --it;
             }
         }
         // Extract our overall stats
         startTime = allUsages.begin()->time;
         endTime = allUsages.rbegin()->time;
         // If we don't have enough records, just return what we can
         if (allUsages.size() < width) {
             return allUsages;
         }
         timeStep = (endTime - startTime) / width;
         // Store the timepoints we need for the graph
         for (uint32_t i = 1; i <= width; ++i) {
             auto it = allUsages.upper_bound(Usage{startTime + timeStep * i, 0, {}, {}});
             if (it != allUsages.begin()) {
                 --it;
             }
             usages.insert(*it);
         }
         return usages;
     }
References souffle::ProfileEventSingleton::getDB(), i, and souffle::ProfileEventSingleton::instance().
Referenced by souffle::genJsonUsage(), memoryUsage(), and usage().
graphBySize()
void graphBySize (std::vector< size_t > list)
Definition at line 1421 of file Tui.h.
{
         size_t max = 0;
         for (auto& l : list) {
             if (l > max) {
                 max = l;
             }
         }
         std::sort(list.begin(), list.end());
         std::reverse(list.begin(), list.end());
         uint32_t i = 0;
         for (auto& l : list) {
             size_t len = max == 0 ? 0 : 64.0 * l / max;
             std::string bar = "";
             for (uint32_t j = 0; j < len; j++) {
                 bar += "*";
             }
             std::printf("%4d %8s | %s\n", i++, Tools::formatNum(precision, l).c_str(), bar.c_str());
         }
     }
References souffle::profile::Tools::formatNum(), i, j, l, souffle::profile::Tui::precision, and tinyformat::printf().
Referenced by iterRel(), iterRul(), and verGraph().
graphByTime()
void graphByTime (std::vector< std::chrono::microseconds > list)
Definition at line 1399 of file Tui.h.
{
         std::chrono::microseconds max{};
         for (auto& d : list) {
             if (d > max) {
                 max = d;
             }
         }
         std::sort(list.begin(), list.end());
         std::reverse(list.begin(), list.end());
         int i = 0;
         for (auto& d : list) {
             uint32_t len = 67.0 * d.count() / max.count();
             std::string bar = "";
             for (uint32_t j = 0; j < len; j++) {
                 bar += "*";
             }
             std::printf("%4d %10.8f | %s\n", i++, (d.count() / 1000000.0), bar.c_str());
         }
     }
References d, i, j, and tinyformat::printf().
Referenced by iterRel(), iterRul(), and verGraph().
help()
static void help () static
Definition at line 685 of file Tui.h.
{
         std::cout << "\nAvailable profiling commands:" << std::endl;
         std::printf("  %-30s%-5s %s\n", "rel", "-", "display relation table.");
         std::printf("  %-30s%-5s %s\n", "rel <relation id>", "-", "display all rules of a given relation.");
         std::printf("  %-30s%-5s %s\n", "rul", "-", "display rule table");
         std::printf("  %-30s%-5s %s\n", "rul <rule id>", "-", "display all version of given rule.");
         std::printf("  %-30s%-5s %s\n", "rul id", "-", "display all rules names and ids.");
         std::printf(
                 "  %-30s%-5s %s\n", "rul id <rule id>", "-", "display the rule name for the given rule id.");
         std::printf("  %-30s%-5s %s\n", "graph <relation id> <type>", "-",
                 "graph a relation by type: (tot_t/copy_t/tuples).");
         std::printf("  %-30s%-5s %s\n", "graph <rule id> <type>", "-",
                 "graph recursive(C) rule by type(tot_t/tuples).");
         std::printf("  %-30s%-5s %s\n", "graph ver <rule id> <type>", "-",
                 "graph recursive(C) rule versions by type(tot_t/copy_t/tuples).");
         std::printf("  %-30s%-5s %s\n", "top", "-", "display top-level summary of program run.");
         std::printf("  %-30s%-5s %s\n", "configuration", "-", "display configuration settings for this run.");
         std::printf("  %-30s%-5s %s\n", "usage [relation id|rule id]", "-",
                 "display CPU usage graphs for a relation or rule.");
         std::printf("  %-30s%-5s %s\n", "memory", "-", "display memory usage.");
         std::printf("  %-30s%-5s %s\n", "help", "-", "print this.");
         std::cout << "\nInteractive mode only commands:" << std::endl;
         //    if (alive) std::printf("  %-30s%-5s %s\n", "stop", "-",
         //                "stop the current live run.");
         std::printf("  %-30s%-5s %s\n", "limit <row count>", "-", "limit number of results shown.");
         std::printf("  %-30s%-5s %s\n", "sort <col number>", "-", "sort tables by given column number.");
         std::printf("  %-30s%-5s %s\n", "q", "-", "exit program.");
     }
References tinyformat::printf().
Referenced by souffle::profile::Tui::runCommand().
id()
void id (std::string col)
Definition at line 1124 of file Tui.h.
{
         ruleTable.sort(6);
         std::vector<std::vector<std::string>> table = Tools::formatTable(ruleTable, precision);
         if (col == "0") {
             std::printf("%7s%2s%s\n\n", "ID", "", "NAME");
             for (auto& row : table) {
                 std::printf("%7s%2s%s\n", row[6].c_str(), "", row[5].c_str());
             }
         } else {
             for (auto& row : table) {
                 if (row[6] == col) {
                     std::printf("%7s%2s%s\n", row[6].c_str(), "", row[5].c_str());
                 }
             }
         }
     }
References souffle::profile::Tools::formatTable(), souffle::profile::Tui::precision, tinyformat::printf(), souffle::profile::Tui::ruleTable, and souffle::profile::Table::sort().
Referenced by souffle::ram::TupleOperation::getTupleId(), souffle::profile::Tui::runCommand(), and souffle::profile::Rule::setId().
iterRel()
void iterRel (std::string c, std::string col)
Definition at line 1250 of file Tui.h.
{
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         std::vector<std::vector<std::string>> table = Tools::formatTable(relationTable, -1);
         std::vector<std::shared_ptr<Iteration>> iter;
         for (auto& row : table) {
             if (row[6] == c) {
                 std::printf("%4s%2s%s\n\n", row[6].c_str(), "", row[5].c_str());
                 iter = run->getRelation(row[5])->getIterations();
                 if (col == "tot_t") {
                     std::vector<std::chrono::microseconds> list;
                     for (auto& i : iter) {
                         list.emplace_back(i->getRuntime());
                     }
                     std::printf("%4s   %s\n\n", "NO", "RUNTIME");
                     graphByTime(list);
                 } else if (col == "copy_t") {
                     std::vector<std::chrono::microseconds> list;
                     for (auto& i : iter) {
                         list.emplace_back(i->getCopytime());
                     }
                     std::printf("%4s   %s\n\n", "NO", "COPYTIME");
                     graphByTime(list);
                 } else if (col == "tuples") {
                     std::vector<size_t> list;
                     for (auto& i : iter) {
                         list.emplace_back(i->size());
                     }
                     std::printf("%4s   %s\n\n", "NO", "TUPLES");
                     graphBySize(list);
                 }
                 return;
             }
         }
         for (auto& row : table) {
             if (row[5] == c) {
                 std::printf("%4s%2s%s\n\n", row[6].c_str(), "", row[5].c_str());
                 const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
                 iter = run->getRelation(row[5])->getIterations();
                 if (col == "tot_t") {
                     std::vector<std::chrono::microseconds> list;
                     for (auto& i : iter) {
                         list.emplace_back(i->getRuntime());
                     }
                     std::printf("%4s   %s\n\n", "NO", "RUNTIME");
                     graphByTime(list);
                 } else if (col == "copy_t") {
                     std::vector<std::chrono::microseconds> list;
                     for (auto& i : iter) {
                         list.emplace_back(i->getCopytime());
                     }
                     std::printf("%4s   %s\n\n", "NO", "COPYTIME");
                     graphByTime(list);
                 } else if (col == "tuples") {
                     std::vector<size_t> list;
                     for (auto& i : iter) {
                         list.emplace_back(i->size());
                     }
                     std::printf("%4s   %s\n\n", "NO", "TUPLES");
                     graphBySize(list);
                 }
                 return;
             }
         }
     }
References souffle::profile::Tools::formatTable(), souffle::profile::OutputProcessor::getProgramRun(), graphBySize(), graphByTime(), i, souffle::profile::Tui::out, tinyformat::printf(), and souffle::profile::Tui::relationTable.
Referenced by souffle::profile::Tui::runCommand().
iterRul()
void iterRul (std::string c, std::string col)
Definition at line 1315 of file Tui.h.
{
         std::vector<std::vector<std::string>> table = Tools::formatTable(ruleTable, precision);
         std::vector<std::shared_ptr<Iteration>> iter;
         for (auto& row : table) {
             if (row[6] == c) {
                 std::printf("%6s%2s%s\n\n", row[6].c_str(), "", row[5].c_str());
                 const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
                 iter = run->getRelation(row[7])->getIterations();
                 if (col == "tot_t") {
                     std::vector<std::chrono::microseconds> list;
                     for (auto& i : iter) {
                         bool add = false;
                         std::chrono::microseconds totalTime{};
                         for (auto& rul : i->getRules()) {
                             if (rul.second->getId() == c) {
                                 totalTime += rul.second->getRuntime();
                                 add = true;
                             }
                         }
                         if (add) {
                             list.emplace_back(totalTime);
                         }
                     }
                     std::printf("%4s   %s\n\n", "NO", "RUNTIME");
                     graphByTime(list);
                 } else if (col == "tuples") {
                     std::vector<size_t> list;
                     for (auto& i : iter) {
                         bool add = false;
                         size_t totalSize = 0L;
                         for (auto& rul : i->getRules()) {
                             if (rul.second->getId() == c) {
                                 totalSize += rul.second->size();
                                 add = true;
                             }
                         }
                         if (add) {
                             list.emplace_back(totalSize);
                         }
                     }
                     std::printf("%4s   %s\n\n", "NO", "TUPLES");
                     graphBySize(list);
                 }
                 break;
             }
         }
     }
References souffle::profile::Tools::formatTable(), souffle::profile::OutputProcessor::getProgramRun(), graphBySize(), graphByTime(), i, souffle::profile::Tui::out, souffle::profile::Tui::precision, tinyformat::printf(), rul(), and souffle::profile::Tui::ruleTable.
Referenced by souffle::profile::Tui::runCommand().
memoryUsage() [1/2]
void memoryUsage (std::chrono::microseconds , std::chrono::microseconds , uint32_t height = 20)
Definition at line 944 of file Tui.h.
{
         uint32_t width = getTermWidth() - 8;
         uint64_t maxMaxRSS = 0;
         std::set<Usage> usages = getUsageStats(width);
         char grid[height][width];
         for (uint32_t i = 0; i < height; ++i) {
             for (uint32_t j = 0; j < width; ++j) {
                 grid[i][j] = ' ';
             }
         }
         for (auto& usage : usages) {
             maxMaxRSS = std::max(maxMaxRSS, usage.maxRSS);
         }
         size_t col = 0;
         for (const Usage& currentUsage : usages) {
             uint64_t curHeight = height * currentUsage.maxRSS / maxMaxRSS;
             for (uint32_t row = 0; row < curHeight; ++row) {
                 grid[row][col] = '*';
             }
             ++col;
         }
         // Print array
         for (int32_t row = height - 1; row >= 0; --row) {
             printf("%6s ", Tools::formatMemory(maxMaxRSS * (row + 1) / height).c_str());
             for (uint32_t col = 0; col < width; ++col) {
                 std::cout << grid[row][col];
             }
             std::cout << std::endl;
         }
         for (uint32_t col = 0; col < 8; ++col) {
             std::cout << ' ';
         }
         for (uint32_t col = 0; col < width; ++col) {
             std::cout << '-';
         }
         std::cout << std::endl;
     }
References souffle::profile::Tools::formatMemory(), getTermWidth(), getUsageStats(), i, j, tinyformat::printf(), and usage().
memoryUsage() [2/2]
void memoryUsage (uint32_t height = 20)
Definition at line 940 of file Tui.h.
{
         memoryUsage({}, {}, height);
     }
Referenced by souffle::profile::Tui::runCommand().
outputHtml()
void outputHtml (std::string filename = "profiler_html/")
Definition at line 636 of file Tui.h.
{
         std::cout << "SouffleProf\n";
         std::cout << "Generating HTML files...\n";
         DIR* dir;
         bool exists = false;
         if (filename.find('/') != std::string::npos) {
             std::string path = filename.substr(0, filename.find('/'));
             if ((dir = opendir(path.c_str())) != nullptr) {
                 exists = true;
                 closedir(dir);
             }
             if (!exists) {
                 mode_t nMode = 0733;  // UNIX style permissions
                 int nError = 0;
                 nError = mkdir(path.c_str(), nMode);
                 if (nError != 0) {
                     std::cerr << "directory " << path
                               << " could not be created. Please create it and try again.";
                     exit(2);
                 }
             }
         }
         std::string filetype = ".html";
         std::string newFile = filename;
         if (filename.size() <= filetype.size() ||
                 !std::equal(filetype.rbegin(), filetype.rend(), filename.rbegin())) {
             int i = 0;
             do {
                 ++i;
                 newFile = filename + std::to_string(i) + ".html";
             } while (Tools::file_exists(newFile));
         }
         std::ofstream outfile(newFile);
         outfile << HtmlGenerator::getHtml(genJson());
         std::cout << "file output to: " << newFile << std::endl;
     }
References souffle::profile::Tools::file_exists(), genJson(), souffle::profile::HtmlGenerator::getHtml(), and i.
quit()
void quit ()
Definition at line 679 of file Tui.h.
                 {
         if (updater.joinable()) {
             updater.join();
         }
     }
References souffle::profile::Tui::updater.
Referenced by souffle::profile::Tui::runProf().
rel()
void rel (size_t limit, bool showLimit = true)
Definition at line 1086 of file Tui.h.
{
         relationTable.sort(sortColumn);
         std::cout << " ----- Relation Table -----\n";
         std::printf("%8s%8s%8s%8s%8s%8s%8s%8s%8s%6s %s\n\n", "TOT_T", "NREC_T", "REC_T", "COPY_T", "LOAD_T",
                 "SAVE_T", "TUPLES", "READS", "TUP/s", "ID", "NAME");
         size_t count = 0;
         for (auto& row : Tools::formatTable(relationTable, precision)) {
             if (++count > limit) {
                 if (showLimit) {
                     std::cout << (relationTable.getRows().size() - resultLimit) << " rows not shown"
                               << std::endl;
                 }
                 break;
             }
             std::printf("%8s%8s%8s%8s%8s%8s%8s%8s%8s%6s %s\n", row[0].c_str(), row[1].c_str(), row[2].c_str(),
                     row[3].c_str(), row[9].c_str(), row[10].c_str(), row[4].c_str(), row[12].c_str(),
                     row[8].c_str(), row[6].c_str(), row[5].c_str());
         }
     }
References souffle::test::count(), souffle::profile::Tools::formatTable(), souffle::profile::Table::getRows(), souffle::profile::Tui::precision, tinyformat::printf(), souffle::profile::Tui::relationTable, souffle::profile::Tui::resultLimit, souffle::profile::Table::sort(), and souffle::profile::Tui::sortColumn.
Referenced by souffle::ParserDriver::addIoFromDeprecatedTag(), souffle::ast::Program::addRelation(), souffle::profile::Reader::addRelation(), souffle::SouffleProgram::addRelation(), souffle::ast::analysis::RecursiveClausesAnalysis::computeIsRecursive(), souffle::interpreter::Engine::execute(), souffle::ExplainProvenanceImpl::ExplainProvenanceImpl(), souffle::ExplainProvenanceImpl::findTuple(), souffle::profile::OutputProcessor::getAtomTable(), souffle::ast::transform::getInlinedLiteral(), souffle::profile::OutputProcessor::getRelTable(), souffle::profile::OutputProcessor::getRulTable(), souffle::profile::OutputProcessor::getSubrulTable(), souffle::synthesiser::Relation::getSynthesiserRelation(), souffle::ast::transform::MagicSetTransformer::getTriviallyIgnoredRelations(), souffle::profile::OutputProcessor::getVersionAtoms(), souffle::profile::OutputProcessor::getVersions(), souffle::ast::analysis::ProfileUseAnalysis::hasRelationSize(), souffle::interpreter::NodeGenerator::lookup(), souffle::ram::transform::MakeIndexTransformer::makeIndex(), souffle::ram::transform::ParallelTransformer::parallelizeOperations(), souffle::ast::transform::MagicSetTransformer::NormaliseDatabaseTransformer::partitionIO(), souffle::ast::analysis::SCCGraphAnalysis::print(), souffle::interpreter::ProgInterface::ProgInterface(), souffle::ExplainProvenanceImpl::queryProcess(), souffle::ast::transform::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::ast::transform::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::ast::transform::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::profile::Tui::runCommand(), souffle::ast::analysis::SCCGraphAnalysis::SCCGraphAnalysis(), souffle::ast::transform::SemanticCheckerImpl::SemanticCheckerImpl(), top(), souffle::ast::transform::ComponentInstantiationTransformer::transform(), souffle::ast::transform::RemoveRedundantRelationsTransformer::transform(), souffle::ast::transform::ExecutionPlanChecker::transform(), souffle::ast::transform::IOAttributesTransformer::transform(), souffle::ast::transform::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer::transform(), souffle::ast::transform::MagicSetTransformer::AdornDatabaseTransformer::transform(), souffle::ast2ram::AstToRamTranslator::translateNonRecursiveRelation(), souffle::ast2ram::AstToRamTranslator::translateRecursiveRelation(), usageRelation(), usageRule(), souffle::interpreter::NodeGenerator::visitLogSize(), and souffle::interpreter::NodeGenerator::visitQuery().
relRul()
void relRul (std::string str)
Definition at line 1142 of file Tui.h.
{
         ruleTable.sort(sortColumn);
         std::vector<std::vector<std::string>> formattedRuleTable = Tools::formatTable(ruleTable, precision);
         std::vector<std::vector<std::string>> formattedRelationTable =
                 Tools::formatTable(relationTable, precision);
         std::cout << "  ----- Rules of a Relation -----\n";
         std::printf("%8s%8s%8s%8s%8s %s\n\n", "TOT_T", "NREC_T", "REC_T", "TUPLES", "ID", "NAME");
         std::string name = "";
         for (auto& row : formattedRelationTable) {
             // Test for relation name or relation id
             if (row[5] == str || row[6] == str) {
                 std::printf("%8s%8s%8s%8s%8s %s\n", row[0].c_str(), row[1].c_str(), row[2].c_str(),
                         row[4].c_str(), row[6].c_str(), row[5].c_str());
                 name = row[5];
                 break;
             }
         }
         std::cout << " ---------------------------------------------------------\n";
         for (auto& row : formattedRuleTable) {
             if (row[7] == name) {
                 std::printf("%8s%8s%8s%8s%8s %s\n", row[0].c_str(), row[1].c_str(), row[2].c_str(),
                         row[4].c_str(), row[6].c_str(), row[7].c_str());
             }
         }
         std::string src = "";
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         if (run->getRelation(name) != nullptr) {
             src = run->getRelation(name)->getLocator();
         }
         std::cout << "\nSrc locator: " << src << "\n\n";
         for (auto& row : formattedRuleTable) {
             if (row[7] == name) {
                 std::printf("%7s%2s%s\n", row[6].c_str(), "", row[5].c_str());
             }
         }
     }
References souffle::profile::Tools::formatTable(), souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::Tui::out, souffle::profile::Tui::precision, tinyformat::printf(), souffle::profile::Tui::relationTable, souffle::profile::Tui::ruleTable, souffle::profile::Table::sort(), souffle::profile::Tui::sortColumn, and str.
Referenced by souffle::profile::Tui::runCommand().
rul()
void rul (size_t limit, bool showLimit = true)
Definition at line 1106 of file Tui.h.
{
         ruleTable.sort(sortColumn);
         std::cout << "  ----- Rule Table -----\n";
         std::printf(
                 "%8s%8s%8s%8s%8s%8s %s\n\n", "TOT_T", "NREC_T", "REC_T", "TUPLES", "TUP/s", "ID", "RELATION");
         size_t count = 0;
         for (auto& row : Tools::formatTable(ruleTable, precision)) {
             if (++count > limit) {
                 if (showLimit) {
                     std::cout << (ruleTable.getRows().size() - resultLimit) << " rows not shown" << std::endl;
                 }
                 break;
             }
             std::printf("%8s%8s%8s%8s%8s%8s %s\n", row[0].c_str(), row[1].c_str(), row[2].c_str(),
                     row[4].c_str(), row[9].c_str(), row[6].c_str(), row[7].c_str());
         }
     }
References souffle::test::count(), souffle::profile::Tools::formatTable(), souffle::profile::Table::getRows(), souffle::profile::Tui::precision, tinyformat::printf(), souffle::profile::Tui::resultLimit, souffle::profile::Tui::ruleTable, souffle::profile::Table::sort(), and souffle::profile::Tui::sortColumn.
Referenced by souffle::profile::Relation::createRecID(), souffle::genJsonRules(), souffle::profile::Relation::getRuleRecList(), souffle::profile::Relation::getTotalRecursiveRuleSize(), iterRul(), souffle::profile::Tui::runCommand(), top(), souffle::profile::Iteration::toString(), souffle::profile::Relation::toString(), and usageRule().
setResultLimit()
void setResultLimit (size_t limit)
Definition at line 1082 of file Tui.h.
{
         resultLimit = limit;
     }
References souffle::profile::Tui::resultLimit.
Referenced by souffle::profile::Tui::runCommand().
setupTabCompletion()
void setupTabCompletion ()
Definition at line 985 of file Tui.h.
{
         linereader.clearTabCompletion();
         linereader.appendTabCompletion("rel");
         linereader.appendTabCompletion("rul");
         linereader.appendTabCompletion("rul id");
         linereader.appendTabCompletion("graph ");
         linereader.appendTabCompletion("top");
         linereader.appendTabCompletion("help");
         linereader.appendTabCompletion("usage");
         linereader.appendTabCompletion("limit ");
         linereader.appendTabCompletion("memory");
         linereader.appendTabCompletion("configuration");
         // add rel tab completes after the rest so users can see all commands first
         for (auto& row : Tools::formatTable(relationTable, precision)) {
             linereader.appendTabCompletion("rel " + row[5]);
             linereader.appendTabCompletion("graph " + row[5] + " tot_t");
             linereader.appendTabCompletion("graph " + row[5] + " copy_t");
             linereader.appendTabCompletion("graph " + row[5] + " tuples");
             linereader.appendTabCompletion("usage " + row[5]);
         }
     }
References souffle::profile::InputReader::appendTabCompletion(), souffle::profile::InputReader::clearTabCompletion(), souffle::profile::Tools::formatTable(), souffle::profile::Tui::linereader, souffle::profile::Tui::precision, and souffle::profile::Tui::relationTable.
Referenced by souffle::profile::Tui::runCommand(), and souffle::profile::Tui::runProf().
top()
void top ()
Definition at line 1023 of file Tui.h.
                {
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         auto* totalRelationsEntry =
                 dynamic_cast<TextEntry*>(ProfileEventSingleton::instance().getDB().lookupEntry(
                         {"program", "configuration", "relationCount"}));
         auto* totalRulesEntry =
                 dynamic_cast<TextEntry*>(ProfileEventSingleton::instance().getDB().lookupEntry(
                         {"program", "configuration", "ruleCount"}));
         size_t totalRelations = 0;
         if (totalRelationsEntry != nullptr) {
             totalRelations = std::stoul(totalRelationsEntry->getText());
         } else {
             totalRelations = run->getRelationMap().size();
         }
         size_t totalRules = 0;
         if (totalRulesEntry != nullptr) {
             totalRules = std::stoul(totalRulesEntry->getText());
         } else {
             totalRules = ruleTable.getRows().size();
         }
         std::printf("%11s%10s%10s%10s%10s%20s\n", "runtime", "loadtime", "savetime", "relations", "rules",
                 "tuples generated");
         std::printf("%11s%10s%10s%10s%10s%14s\n", run->getRuntime().c_str(),
                 run->formatTime(run->getTotalLoadtime()).c_str(),
                 run->formatTime(run->getTotalSavetime()).c_str(), run->formatNum(0, totalRelations).c_str(),
                 run->formatNum(0, totalRules).c_str(),
                 run->formatNum(precision, run->getTotalSize()).c_str());
         // Progress bar
         // Determine number of relations processed
         size_t processedRelations = run->getRelationMap().size();
         size_t screenWidth = getTermWidth() - 10;
         if (alive && totalRelationsEntry != nullptr) {
             std::cout << "Progress ";
             for (size_t i = 0; i < screenWidth; ++i) {
                 if (screenWidth * processedRelations / totalRelations > i) {
                     std::cout << '#';
                 } else {
                     std::cout << '_';
                 }
             }
         }
         std::cout << std::endl;
         std::cout << "Slowest relations to fully evaluate\n";
         rel(3, false);
         for (size_t i = relationTable.getRows().size(); i < 3; ++i) {
             std::cout << "\n";
         }
         std::cout << "Slowest rules to fully evaluate\n";
         rul(3, false);
         for (size_t i = ruleTable.getRows().size(); i < 3; ++i) {
             std::cout << "\n";
         }
         usage(10);
     }
References souffle::profile::Tui::alive, souffle::ProfileEventSingleton::getDB(), souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::Table::getRows(), getTermWidth(), i, souffle::ProfileEventSingleton::instance(), souffle::profile::Tui::out, souffle::profile::Tui::precision, tinyformat::printf(), rel(), souffle::profile::Tui::relationTable, rul(), souffle::profile::Tui::ruleTable, and usage().
Referenced by souffle::profile::Tui::runCommand(), and souffle::profile::Tui::runProf().
updateDB()
void updateDB () protected
Definition at line 1472 of file Tui.h.
                     {
         reader->processFile();
         ruleTable = out.getRulTable();
         relationTable = out.getRelTable();
     }
References souffle::profile::OutputProcessor::getRelTable(), souffle::profile::OutputProcessor::getRulTable(), souffle::profile::Tui::out, souffle::profile::Tui::reader, souffle::profile::Tui::relationTable, and souffle::profile::Tui::ruleTable.
Referenced by souffle::profile::Tui::runCommand(), and souffle::profile::Tui::Tui().
usage() [1/2]
void usage (std::chrono::microseconds endTime, std::chrono::microseconds startTime, uint32_t height = 20)
Definition at line 843 of file Tui.h.
{
         uint32_t width = getTermWidth() - 8;
         std::set<Usage> usages = getUsageStats(width);
         if (usages.size() < 2) {
             for (uint8_t i = 0; i < height + 2; ++i) {
                 std::cout << std::endl;
             }
             std::cout << "Insufficient data for usage statistics." << std::endl;
             return;
         }
         double maxIntervalUsage = 0;
         // Extract our overall stats
         if (startTime.count() == 0) {
             startTime = usages.begin()->time;
         }
         if (endTime.count() == 0) {
             endTime = usages.rbegin()->time;
         }
         if (usages.size() < width) {
             width = usages.size();
         }
         // Find maximum so we can normalise the graph
         Usage previousUsage{{}, 0, {}, {}};
         for (auto& currentUsage : usages) {
             double usageDiff = (currentUsage.systemtime - previousUsage.systemtime + currentUsage.usertime -
                                 previousUsage.usertime)
                                        .count();
             usageDiff /= (currentUsage.time - previousUsage.time).count();
             if (usageDiff > maxIntervalUsage) {
                 maxIntervalUsage = usageDiff;
             }
             previousUsage = currentUsage;
         }
         double intervalUsagePercent = 100.0 * maxIntervalUsage;
         std::printf("%11s\n", "cpu total");
         std::printf("%11s\n", Tools::formatTime(usages.rbegin()->usertime).c_str());
         // Add columns to the graph
         char grid[height][width];
         for (uint32_t i = 0; i < height; ++i) {
             for (uint32_t j = 0; j < width; ++j) {
                 grid[i][j] = ' ';
             }
         }
         previousUsage = {{}, 0, {}, {}};
         uint32_t col = 0;
         for (const Usage& currentUsage : usages) {
             uint64_t curHeight = 0;
             uint64_t curSystemHeight = 0;
             // Usage may be 0
             if (maxIntervalUsage != 0) {
                 curHeight = (currentUsage.systemtime - previousUsage.systemtime + currentUsage.usertime -
                              previousUsage.usertime)
                                     .count();
                 curHeight /= (currentUsage.time - previousUsage.time).count();
                 curHeight *= height / maxIntervalUsage;
                 curSystemHeight = (currentUsage.systemtime - previousUsage.systemtime).count();
                 curSystemHeight /= (currentUsage.time - previousUsage.time).count();
                 curSystemHeight *= height / maxIntervalUsage;
             }
             for (uint32_t row = 0; row < curHeight; ++row) {
                 grid[row][col] = '*';
             }
             for (uint32_t row = curHeight - curSystemHeight; row < curHeight; ++row) {
                 grid[row][col] = '+';
             }
             previousUsage = currentUsage;
             ++col;
         }
         // Print array
         for (int32_t row = height - 1; row >= 0; --row) {
             printf("%6d%% ", uint32_t(intervalUsagePercent * (row + 1) / height));
             for (uint32_t col = 0; col < width; ++col) {
                 std::cout << grid[row][col];
             }
             std::cout << std::endl;
         }
         for (uint32_t col = 0; col < 8; ++col) {
             std::cout << ' ';
         }
         for (uint32_t col = 0; col < width; ++col) {
             std::cout << '-';
         }
         std::cout << std::endl;
     }
References souffle::test::count(), souffle::profile::Tools::formatTime(), getTermWidth(), getUsageStats(), i, j, and tinyformat::printf().
usage() [2/2]
void usage (uint32_t height = 20)
Definition at line 839 of file Tui.h.
{
         usage({}, {}, height);
     }
Referenced by souffle::genJsonUsage(), memoryUsage(), souffle::profile::Tui::runCommand(), top(), usageRelation(), and usageRule().
usageRelation()
void usageRelation (std::string id)
Definition at line 715 of file Tui.h.
{
         std::vector<std::vector<std::string>> formattedRelationTable =
                 Tools::formatTable(relationTable, precision);
         std::string name = "";
         bool found = false;
         for (auto& row : formattedRelationTable) {
             if (row[5] == id || row[6] == id) {
                 name = row[5];
                 found = true;
                 break;
             }
         }
         if (!found) {
             std::cout << "Relation does not exist.\n";
             return;
         }
         const Relation* rel = out.getProgramRun()->getRelation(name);
         usage(rel->getEndtime(), rel->getStarttime());
     }
References souffle::profile::Tools::formatTable(), souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::Tui::out, souffle::profile::Tui::precision, rel(), souffle::profile::Tui::relationTable, and usage().
Referenced by souffle::profile::Tui::runCommand().
usageRule()
void usageRule (std::string id)
Definition at line 736 of file Tui.h.
{
         std::vector<std::vector<std::string>> formattedRuleTable = Tools::formatTable(ruleTable, precision);
         std::string relName = "";
         std::string srcLocator = "";
         bool found = false;
         for (auto& row : formattedRuleTable) {
             if (row[5] == id || row[6] == id) {
                 relName = row[7];
                 srcLocator = row[10];
                 found = true;
                 break;
             }
         }
         if (!found) {
             std::cout << "Rule does not exist.\n";
             return;
         }
         auto* rel = out.getProgramRun()->getRelation(relName);
         if (rel == nullptr) {
             std::cout << "Relation ceased to exist. Odd." << std::endl;
             return;
         }
         if (rel->getRuleMap().count(srcLocator) == 0) {
             std::cout << "Rule ceased to exist. Odd." << std::endl;
             return;
         }
         auto& rul = rel->getRuleMap().at(srcLocator);
         usage(rul->getEndtime(), rul->getStarttime());
     }
References souffle::profile::Tools::formatTable(), souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::Tui::out, souffle::profile::Tui::precision, rel(), rul(), souffle::profile::Tui::ruleTable, and usage().
Referenced by souffle::profile::Tui::runCommand().
verAtoms()
void verAtoms (Table & atomTable, const std::string & ruleName = "") protected
Definition at line 1443 of file Tui.h.
{
         // If there are no subrules then just print out any atoms found
         // If we do find subrules, then label atoms with their subrules.
         if (atomTable.rows.empty()) {
             return;
         }
         bool firstRun = true;
         std::string lastRule = ruleName;
         for (auto& _row : atomTable.rows) {
             Row& row = *_row;
             std::string rule = row[0]->toString(precision);
             if (rule != lastRule) {
                 lastRule = rule;
                 std::cout << "     " << row[0]->toString(precision) << std::endl;
                 firstRun = true;
             }
             if (firstRun) {
                 std::printf("      %-16s%-16s%s\n", "FREQ", "RELSIZE", "ATOM");
                 firstRun = false;
             }
             std::string relationName = row[1]->getStringVal();
             relationName = relationName.substr(0, relationName.find('('));
             auto* relation = out.getProgramRun()->getRelation(relationName);
             std::string relationSize = relation == nullptr ? "--" : std::to_string(relation->size());
             std::printf("      %-16s%-16s%s\n", row[3]->toString(precision).c_str(), relationSize.c_str(),
                     row[1]->getStringVal().c_str());
         }
         std::cout << '\n';
     }
References souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::Tui::out, souffle::profile::Tui::precision, tinyformat::printf(), relation, rule, and souffle::toString().
Referenced by verRul().
verGraph()
void verGraph (std::string c, std::string col)
Definition at line 1363 of file Tui.h.
{
         if (c.find('.') == std::string::npos) {
             std::cout << "Rule does not exist";
             return;
         }
         std::vector<std::string> part = Tools::split(c, ".");
         std::string strRel = "R" + part[0].substr(1);
         Table versionTable = out.getVersions(strRel, c);
         std::printf("%6s%2s%s\n\n", (*versionTable.rows[0])[6]->toString(0).c_str(), "",
                 (*versionTable.rows[0])[5]->toString(0).c_str());
         if (col == "tot_t") {
             std::vector<std::chrono::microseconds> list;
             for (auto& row : versionTable.rows) {
                 list.emplace_back((*row)[0]->getTimeVal());
             }
             std::printf("%4s   %s\n\n", "NO", "RUNTIME");
             graphByTime(list);
         } else if (col == "copy_t") {
             std::vector<std::chrono::microseconds> list;
             for (auto& row : versionTable.rows) {
                 list.emplace_back((*row)[3]->getTimeVal());
             }
             std::printf("%4s   %s\n\n", "NO", "COPYTIME");
             graphByTime(list);
         } else if (col == "tuples") {
             std::vector<size_t> list;
             for (auto& row : versionTable.rows) {
                 list.emplace_back((*row)[4]->getLongVal());
             }
             std::printf("%4s   %s\n\n", "NO", "TUPLES");
             graphBySize(list);
         }
     }
References souffle::profile::OutputProcessor::getVersions(), graphBySize(), graphByTime(), souffle::profile::Tui::out, tinyformat::printf(), and souffle::profile::Tools::split().
Referenced by souffle::profile::Tui::runCommand().
verRul()
void verRul (std::string str)
Definition at line 1181 of file Tui.h.
{
         if (str.find(".") == std::string::npos) {
             std::cout << "Rule does not exist\n";
             return;
         }
         std::vector<std::string> part = Tools::split(str, ".");
         std::string strRel = "R" + part[0].substr(1);
         Table versionTable = out.getVersions(strRel, str);
         versionTable.sort(sortColumn);
         ruleTable.sort(sortColumn);  // why isnt it sorted in the original java?!?
         std::vector<std::vector<std::string>> formattedRuleTable = Tools::formatTable(ruleTable, precision);
         bool found = false;
         std::string ruleName;
         std::string srcLocator;
         // Check that the rule exists, and print it out if so.
         for (auto& row : formattedRuleTable) {
             if (row[6] == str) {
                 std::cout << row[5] << std::endl;
                 found = true;
                 ruleName = row[5];
                 srcLocator = row[10];
             }
         }
         // If the rule exists, print out the source locator.
         if (found) {
             if (versionTable.rows.size() > 0) {
                 if (versionTable.rows[0]->cells[9] != nullptr) {
                     std::cout << "Src locator-: " << (*versionTable.rows[0])[9]->getStringVal() << "\n\n";
                 } else {
                     std::cout << "Src locator-: -\n\n";
                 }
             } else if (formattedRuleTable.size() > 0) {
                 std::cout << "Src locator-: " << formattedRuleTable[0][10] << "\n\n";
             }
         }
         // Print out the versions of this rule.
         std::cout << "  ----- Rule Versions Table -----\n";
         std::printf("%8s%8s%8s%16s%6s\n\n", "TOT_T", "NREC_T", "REC_T", "TUPLES", "VER");
         for (auto& row : formattedRuleTable) {
             if (row[6] == str) {
                 std::printf("%8s%8s%8s%16s%6s\n", row[0].c_str(), row[1].c_str(), row[2].c_str(),
                         row[4].c_str(), "");
             }
         }
         std::cout << "   ---------------------------------------------\n";
         for (auto& _row : versionTable.rows) {
             Row row = *_row;
             std::printf("%8s%8s%8s%16s%6s\n", row[0]->toString(precision).c_str(),
                     row[1]->toString(precision).c_str(), row[2]->toString(precision).c_str(),
                     row[4]->toString(precision).c_str(), row[8]->toString(precision).c_str());
             Table atom_table = out.getVersionAtoms(strRel, srcLocator, row[8]->getLongVal());
             verAtoms(atom_table);
         }
         if (!versionTable.rows.empty()) {
             return;
         }
         Table atom_table = out.getAtomTable(strRel, str);
         verAtoms(atom_table, ruleName);
     }
References souffle::profile::Tools::formatTable(), souffle::profile::OutputProcessor::getAtomTable(), souffle::profile::OutputProcessor::getVersionAtoms(), souffle::profile::OutputProcessor::getVersions(), souffle::profile::Tui::out, souffle::profile::Tui::precision, tinyformat::printf(), souffle::profile::Tui::ruleTable, souffle::profile::Table::sort(), souffle::profile::Tui::sortColumn, souffle::profile::Tools::split(), str, souffle::toString(), and verAtoms().
Referenced by souffle::profile::Tui::runCommand().