souffle: souffle::interpreter::IndexAggregate Class Reference
souffle::interpreter::IndexAggregate Class Reference
#include <Node.h>
Public Member Functions
IndexAggregate (enum NodeType ty, const ram::Node *sdw, RelationHandle *relHandle, Own< Node > expr, Own< Node > filter, Own< Node > nested, size_t viewId, SuperInstruction superInst)
Public Member Functions inherited from souffle::interpreter::Aggregate
Aggregate (enum NodeType ty, const ram::Node *sdw, RelationHandle *relHandle, Own< Node > expr, Own< Node > filter, Own< Node > nested)
const Node * getExpr () const
Public Member Functions inherited from souffle::interpreter::Node
RelationWrapper * getRelation () const
get relation from handle
const ram::Node * getShadow () const
get shadow node, i.e., RAM node
enum NodeType getType () const
get node type
Node (enum NodeType ty, const ram::Node *sdw, RelationHandle *relHandle=nullptr)
virtual ~Node ()=default
Public Member Functions inherited from souffle::interpreter::ConditionalOperation
ConditionalOperation (Own< Node > cond)
const Node * getCondition () const
Public Member Functions inherited from souffle::interpreter::NestedOperation
const Node * getNestedOperation () const
NestedOperation (Own< Node > nested)
Public Member Functions inherited from souffle::interpreter::SuperOperation
const SuperInstruction & getSuperInst () const
SuperOperation (SuperInstruction superInst)
Public Member Functions inherited from souffle::interpreter::ViewOperation
size_t getViewId () const
ViewOperation (size_t id)
Additional Inherited Members
Public Types inherited from souffle::interpreter::Node
using RelationHandle = Own< RelationWrapper >
Protected Attributes inherited from souffle::interpreter::Aggregate
Own< Node > expr
Protected Attributes inherited from souffle::interpreter::Node
RelationHandle *const relHandle
const ram::Node * shadow
enum NodeType type
Protected Attributes inherited from souffle::interpreter::ConditionalOperation
Own< Node > cond
Protected Attributes inherited from souffle::interpreter::NestedOperation
Own< Node > nested
Protected Attributes inherited from souffle::interpreter::SuperOperation
const SuperInstruction superInst
Protected Attributes inherited from souffle::interpreter::ViewOperation
size_t viewId
Detailed Description
Definition at line 695 of file Node.h.
Constructor & Destructor Documentation
IndexAggregate()
souffle::interpreter::IndexAggregate::IndexAggregate (enum NodeType ty, const ram::Node * sdw, RelationHandle * relHandle, Own< Node > expr, Own< Node > filter, Own< Node > nested, size_t viewId, SuperInstruction superInst) inline
Definition at line 697 of file Node.h.
             : public Node, public ConditionalOperation, public NestedOperation {
References souffle::interpreter::Break::Break(), souffle::interpreter::ConditionalOperation::cond, souffle::interpreter::ConditionalOperation::ConditionalOperation(), souffle::interpreter::NestedOperation::nested, souffle::interpreter::NestedOperation::NestedOperation(), and souffle::interpreter::Node::Node().
The documentation for this class was generated from the following file:
interpreter/Node.h