souffle: souffle::ast::analysis::TypeAnalysis Class Reference
souffle::ast::analysis::TypeAnalysis Class Reference
#include <Type.h>
Public Member Functions
TypeAttribute getFunctorArgType (const Functor *functor, const size_t idx) const
const std::vector< TypeAttribute > & getFunctorArgTypes (const UserDefinedFunctor &udf) const
TypeAttribute getFunctorReturnType (const Functor *functor) const
const std::map< const NumericConstant *, NumericConstant::Type > & getNumericConstantTypes () const
NumericConstant::Type getPolymorphicNumericConstantType (const NumericConstant *nc) const
– Polymorphism-related methods –
AggregateOp getPolymorphicOperator (const Aggregator *agg) const
BinaryConstraintOp getPolymorphicOperator (const BinaryConstraint *bc) const
FunctorOp getPolymorphicOperator (const IntrinsicFunctor *inf) const
std::set< TypeAttribute > getTypeAttributes (const Argument *arg) const
TypeSet const & getTypes (const Argument *argument) const
Get the computed types for the given argument.
IntrinsicFunctors getValidIntrinsicFunctorOverloads (const IntrinsicFunctor &inf) const
– Functor-related methods –
bool hasValidTypeInfo (const Argument *argument) const
bool isStatefulFunctor (const UserDefinedFunctor *udf) const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
TypeAnalysis ()
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Member Functions
static std::map< const Argument *, TypeSet > analyseTypes (const TranslationUnit &tu, const Clause &clause, std::ostream *logs=nullptr)
Analyse the given clause and computes for each contained argument a set of potential types.
static bool isMultiResultFunctor (const Functor &functor)
Static Public Attributes
static constexpr const char * name = "type-analysis"
Private Member Functions
bool analyseAggregators (const TranslationUnit &translationUnit)
bool analyseBinaryConstraints (const TranslationUnit &translationUnit)
bool analyseIntrinsicFunctors (const TranslationUnit &translationUnit)
bool analyseNumericConstants (const TranslationUnit &translationUnit)
bool isFloat (const Argument *argument) const
bool isSymbol (const Argument *argument) const
bool isUnsigned (const Argument *argument) const
Static Private Member Functions
static Own< Clause > createAnnotatedClause (const Clause *clause, const std::map< const Argument *, TypeSet > argumentTypes)
Private Attributes
std::map< const Aggregator *, AggregateOp > aggregatorType
std::stringstream analysisLogs
VecOwn< Clause > annotatedClauses
std::map< const Argument *, TypeSet > argumentTypes
std::map< const BinaryConstraint *, BinaryConstraintOp > constraintType
std::map< const IntrinsicFunctor *, const IntrinsicFunctorInfo * > functorInfo
std::map< const NumericConstant *, NumericConstant::Type > numericConstantType
std::map< std::string, const FunctorDeclaration * > udfDeclaration
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Definition at line 45 of file Type.h.
Constructor & Destructor Documentation
TypeAnalysis()
souffle::ast::analysis::TypeAnalysis::TypeAnalysis () inline
Definition at line 49 of file Type.h.
 : Analysis(name) {}
Member Function Documentation
analyseAggregators()
bool souffle::ast::analysis::TypeAnalysis::analyseAggregators (const TranslationUnit & translationUnit) private
Definition at line 355 of file Type.cpp.
{
             return;
         }
         changed = true;
         aggregatorType[&agg] = overloadedType;
     };
     visitDepthFirst(program, [&](const Aggregator& agg) {
         if (isOverloadedAggregator(agg.getBaseOperator())) {
             auto* targetExpression = agg.getTargetExpression();
             if (isFloat(targetExpression)) {
                 setAggregatorType(agg, TypeAttribute::Float);
             } else if (isUnsigned(targetExpression)) {
                 setAggregatorType(agg, TypeAttribute::Unsigned);
             } else {
                 setAggregatorType(agg, TypeAttribute::Signed);
             }
         } else {
             if (contains(aggregatorType, &agg)) {
                 assert(aggregatorType.at(&agg) == agg.getBaseOperator() &&
                         "non-overloaded aggr types should always be the base operator");
                 return;
             }
             changed = true;
             aggregatorType[&agg] = agg.getBaseOperator();
         }
     });
     return changed;
 }
 bool TypeAnalysis::analyseBinaryConstraints(const TranslationUnit& translationUnit) {
     bool changed = false;
     const auto& program = translationUnit.getProgram();
     auto setConstraintType = [&](const BinaryConstraint& bc, TypeAttribute attr) {
analyseBinaryConstraints()
bool souffle::ast::analysis::TypeAnalysis::analyseBinaryConstraints (const TranslationUnit & translationUnit) private
Definition at line 392 of file Type.cpp.
{
             return;
         }
         changed = true;
         constraintType[&bc] = overloadedType;
     };
     visitDepthFirst(program, [&](const BinaryConstraint& binaryConstraint) {
         if (isOverloaded(binaryConstraint.getBaseOperator())) {
             // Get arguments
             auto* leftArg = binaryConstraint.getLHS();
             auto* rightArg = binaryConstraint.getRHS();
             // Both args must be of the same type
             if (isFloat(leftArg) && isFloat(rightArg)) {
                 setConstraintType(binaryConstraint, TypeAttribute::Float);
             } else if (isUnsigned(leftArg) && isUnsigned(rightArg)) {
                 setConstraintType(binaryConstraint, TypeAttribute::Unsigned);
             } else if (isSymbol(leftArg) && isSymbol(rightArg)) {
                 setConstraintType(binaryConstraint, TypeAttribute::Symbol);
             } else {
                 setConstraintType(binaryConstraint, TypeAttribute::Signed);
             }
         } else {
             if (contains(constraintType, &binaryConstraint)) {
                 assert(constraintType.at(&binaryConstraint) == binaryConstraint.getBaseOperator() &&
                         "unexpected constraint type");
                 return;
             }
             changed = true;
             constraintType[&binaryConstraint] = binaryConstraint.getBaseOperator();
         }
     });
     return changed;
 }
 bool TypeAnalysis::isFloat(const Argument* argument) const {
     return isOfKind(getTypes(argument), TypeAttribute::Float);
 }
 bool TypeAnalysis::isUnsigned(const Argument* argument) const {
analyseIntrinsicFunctors()
bool souffle::ast::analysis::TypeAnalysis::analyseIntrinsicFunctors (const TranslationUnit & translationUnit) private
Definition at line 288 of file Type.cpp.
{
                 functorInfo.erase(&functor);
                 changed = true;
             }
             return;
         }
         // Update to the canonic representation if different
         const auto* curInfo = &candidates.front().get();
         if (contains(functorInfo, &functor) && functorInfo.at(&functor) == curInfo) {
             return;
         }
         functorInfo[&functor] = curInfo;
         changed = true;
     });
     return changed;
 }
 bool TypeAnalysis::analyseNumericConstants(const TranslationUnit& translationUnit) {
     bool changed = false;
     const auto& program = translationUnit.getProgram();
     auto setNumericConstantType = [&](const NumericConstant& nc, NumericConstant::Type ncType) {
References functorInfo.
analyseNumericConstants()
bool souffle::ast::analysis::TypeAnalysis::analyseNumericConstants (const TranslationUnit & translationUnit) private
Definition at line 313 of file Type.cpp.
{
         // Constant has a fixed type
         if (numericConstant.getFixedType().has_value()) {
             setNumericConstantType(numericConstant, numericConstant.getFixedType().value());
             return;
         }
         // Otherwise, type should be inferred
         TypeSet types = getTypes(&numericConstant);
         auto hasOfKind = [&](TypeAttribute kind) -> bool {
             return any_of(types, [&](const analysis::Type& type) { return isOfKind(type, kind); });
         };
         if (hasOfKind(TypeAttribute::Signed)) {
             setNumericConstantType(numericConstant, NumericConstant::Type::Int);
         } else if (hasOfKind(TypeAttribute::Unsigned)) {
             setNumericConstantType(numericConstant, NumericConstant::Type::Uint);
         } else if (hasOfKind(TypeAttribute::Float)) {
             setNumericConstantType(numericConstant, NumericConstant::Type::Float);
         } else {
             // Type information no longer valid
             if (contains(numericConstantType, &numericConstant)) {
                 numericConstantType.erase(&numericConstant);
                 changed = true;
             }
         }
     });
     return changed;
 }
 bool TypeAnalysis::analyseAggregators(const TranslationUnit& translationUnit) {
     bool changed = false;
     const auto& program = translationUnit.getProgram();
     auto setAggregatorType = [&](const Aggregator& agg, TypeAttribute attr) {
analyseTypes()
std::map< const Argument *, TypeSet > souffle::ast::analysis::TypeAnalysis::analyseTypes (const TranslationUnit & tu, const Clause & clause, std::ostream * logs = nullptr) static
Analyse the given clause and computes for each contained argument a set of potential types.
If the set associated to an argument is empty, no consistent typing can be found and the rule can not be properly typed.
Returns
a map mapping each contained argument to a set of types
Definition at line 131 of file Type.cpp.
                    : annotatedClauses) {
createAnnotatedClause()
Own< Clause > souffle::ast::analysis::TypeAnalysis::createAnnotatedClause (const Clause * clause, const std::map< const Argument *, TypeSet > argumentTypes) static private
Definition at line 68 of file Type.cpp.
                                                                      : types(types) {}
         Own<Node> operator()(Own<Node> node) const override {
             if (auto* var = dynamic_cast<ast::Variable*>(node.get())) {
                 std::stringstream newVarName;
                 newVarName << var->getName() << "&isin;" << types.find(var)->second;
                 return mk<ast::Variable>(newVarName.str());
             } else if (auto* var = dynamic_cast<UnnamedVariable*>(node.get())) {
                 std::stringstream newVarName;
                 newVarName << "_"
                            << "&isin;" << types.find(var)->second;
                 return mk<ast::Variable>(newVarName.str());
             }
             node->apply(*this);
             return node;
         }
     };
     /* Note:
      * Because the type of each argument is stored in the form [address -> type-set],
      * the type-analysis result does not immediately apply to the clone due to differing
      * addresses.
      * Two ways around this:
      *  (1) Perform the type-analysis again for the cloned clause
      *  (2) Keep track of the addresses of equivalent arguments in the cloned clause
      * Method (2) was chosen to avoid having to recompute the analysis each time.
      */
     auto annotatedClause = souffle::clone(clause);
     // Maps x -> y, where x is the address of an argument in the original clause, and y
     // is the address of the equivalent argument in the clone.
     std::map<const Argument*, const Argument*> memoryMap;
     std::vector<const Argument*> originalAddresses;
     visitDepthFirst(*clause, [&](const Argument& arg) { originalAddresses.push_back(&arg); });
     std::vector<const Argument*> cloneAddresses;
     visitDepthFirst(*annotatedClause, [&](const Argument& arg) { cloneAddresses.push_back(&arg); });
     assert(cloneAddresses.size() == originalAddresses.size());
     for (size_t i = 0; i < originalAddresses.size(); i++) {
         memoryMap[originalAddresses[i]] = cloneAddresses[i];
     }
     // Map the types to the clause clone
     std::map<const Argument*, TypeSet> cloneArgumentTypes;
     for (auto& pair : argumentTypes) {
         cloneArgumentTypes[memoryMap[pair.first]] = pair.second;
     }
     // Create the type-annotated clause
     TypeAnnotator annotator(cloneArgumentTypes);
     annotatedClause->apply(annotator);
     return annotatedClause;
 }
 std::map<const Argument*, TypeSet> TypeAnalysis::analyseTypes(
         const TranslationUnit& tu, const Clause& clause, std::ostream* logs) {
     return TypeConstraintsAnalysis(tu).analyse(clause, logs);
 }
getFunctorArgType()
TypeAttribute souffle::ast::analysis::TypeAnalysis::getFunctorArgType (const Functor * functor, const size_t idx) const
Definition at line 155 of file Type.cpp.
{
     return udfDeclaration.at(udf.getName())->getArgsTypes();
 }
 bool TypeAnalysis::isStatefulFunctor(const UserDefinedFunctor* udf) const {
getFunctorArgTypes()
const std::vector< TypeAttribute > & souffle::ast::analysis::TypeAnalysis::getFunctorArgTypes (const UserDefinedFunctor & udf) const
Definition at line 166 of file Type.cpp.
{
getFunctorReturnType()
TypeAttribute souffle::ast::analysis::TypeAnalysis::getFunctorReturnType (const Functor * functor) const
Definition at line 145 of file Type.cpp.
{
     assert(hasValidTypeInfo(functor) && "type of functor not processed");
     if (auto* intrinsic = as<IntrinsicFunctor>(functor)) {
         auto* info = functorInfo.at(intrinsic);
         return info->params.at(info->variadic ? 0 : idx);
getNumericConstantTypes()
const std::map< const NumericConstant *, NumericConstant::Type > & souffle::ast::analysis::TypeAnalysis::getNumericConstantTypes () const
Definition at line 174 of file Type.cpp.
{
         auto candidates = functorBuiltIn(intrinsic->getBaseFunctionOp());
getPolymorphicNumericConstantType()
NumericConstant::Type souffle::ast::analysis::TypeAnalysis::getPolymorphicNumericConstantType (const NumericConstant * nc) const
– Polymorphism-related methods –
Definition at line 268 of file Type.cpp.
Referenced by souffle::ast::analysis::PolymorphicObjectsAnalysis::getOverloadedFunctionOp().
getPolymorphicOperator() [1/3]
AggregateOp souffle::ast::analysis::TypeAnalysis::getPolymorphicOperator (const Aggregator * agg) const
Definition at line 278 of file Type.cpp.
Referenced by souffle::ast::analysis::PolymorphicObjectsAnalysis::getOverloadedOperator(), and souffle::ast::analysis::PolymorphicObjectsAnalysis::hasInvalidType().
getPolymorphicOperator() [2/3]
BinaryConstraintOp souffle::ast::analysis::TypeAnalysis::getPolymorphicOperator (const BinaryConstraint * bc) const
Definition at line 273 of file Type.cpp.
getPolymorphicOperator() [3/3]
FunctorOp souffle::ast::analysis::TypeAnalysis::getPolymorphicOperator (const IntrinsicFunctor * inf) const
Definition at line 283 of file Type.cpp.
{
         auto candidates = getValidIntrinsicFunctorOverloads(functor);
References getValidIntrinsicFunctorOverloads().
getTypeAttributes()
std::set< TypeAttribute > souffle::ast::analysis::TypeAnalysis::getTypeAttributes (const Argument * arg) const
Definition at line 189 of file Type.cpp.
{
         if (hasValidTypeInfo(udf)) {
             typeAttributes.insert(getFunctorReturnType(udf));
             return typeAttributes;
         }
     }
     const auto& types = getTypes(arg);
     if (types.isAll()) {
         return {TypeAttribute::Signed, TypeAttribute::Unsigned, TypeAttribute::Float, TypeAttribute::Symbol,
                 TypeAttribute::Record};
     }
     for (const auto& type : types) {
         typeAttributes.insert(getTypeAttribute(type));
     }
     return typeAttributes;
 }
 IntrinsicFunctors TypeAnalysis::getValidIntrinsicFunctorOverloads(const IntrinsicFunctor& inf) const {
     // Get the info of all possible functors which can be used here
     IntrinsicFunctors functorInfos = contains(functorInfo, &inf) ? functorBuiltIn(functorInfo.at(&inf)->op)
                                                                  : functorBuiltIn(inf.getBaseFunctionOp());
getTypes()
TypeSet const& souffle::ast::analysis::TypeAnalysis::getTypes (const Argument * argument) const inline
Get the computed types for the given argument.
Definition at line 56 of file Type.h.
{
         return argumentTypes.at(argument);
     }
References argumentTypes.
Referenced by souffle::ast::transform::TypeCheckerImpl::visitStringConstant(), and souffle::ast::transform::TypeCheckerImpl::visitVariable().
getValidIntrinsicFunctorOverloads()
IntrinsicFunctors souffle::ast::analysis::TypeAnalysis::getValidIntrinsicFunctorOverloads (const IntrinsicFunctor & inf) const
– Functor-related methods –
Definition at line 216 of file Type.cpp.
                                                                      { return getTypeAttributes(arg); });
     auto isValidOverload = [&](const IntrinsicFunctorInfo& candidate) {
         // Check for arity mismatch
         if (!candidate.variadic && argTypes.size() != candidate.params.size()) {
             return false;
         }
         // Check that argument types match
         for (size_t i = 0; i < argTypes.size(); ++i) {
             const auto& expectedType = candidate.params[candidate.variadic ? 0 : i];
             if (!contains(argTypes[i], expectedType)) {
                 return false;
             }
         }
         // Check that the return type matches
         return contains(returnTypes, candidate.result);
     };
     auto candidates = filter(functorInfos, isValidOverload);
     // Sort them in a standardised way (so order is deterministic)
     auto comparator = [&](const IntrinsicFunctorInfo& a, const IntrinsicFunctorInfo& b) {
         if (a.result != b.result) return a.result < b.result;
         if (a.variadic != b.variadic) return a.variadic < b.variadic;
         return std::lexicographical_compare(
                 a.params.begin(), a.params.end(), b.params.begin(), b.params.end());
     };
     std::sort(candidates.begin(), candidates.end(), comparator);
     return candidates;
 }
 bool TypeAnalysis::hasValidTypeInfo(const Argument* argument) const {
     if (auto* inf = as<IntrinsicFunctor>(argument)) {
         return contains(functorInfo, inf);
     } else if (auto* udf = as<UserDefinedFunctor>(argument)) {
         return contains(udfDeclaration, udf->getName());
Referenced by getPolymorphicOperator().
hasValidTypeInfo()
bool souffle::ast::analysis::TypeAnalysis::hasValidTypeInfo (const Argument * argument) const
Definition at line 255 of file Type.cpp.
{
         return contains(aggregatorType, agg);
     }
     return true;
 }
 NumericConstant::Type TypeAnalysis::getPolymorphicNumericConstantType(const NumericConstant* nc) const {
     assert(hasValidTypeInfo(nc) && "numeric constant type not set");
     return numericConstantType.at(nc);
 }
Referenced by souffle::ast::analysis::PolymorphicObjectsAnalysis::getInferredType(), and souffle::ast::analysis::TypeConstraintsAnalysis::visitFunctor().
isFloat()
bool souffle::ast::analysis::TypeAnalysis::isFloat (const Argument * argument) const private
Definition at line 435 of file Type.cpp.
{
isMultiResultFunctor()
bool souffle::ast::analysis::TypeAnalysis::isMultiResultFunctor (const Functor & functor) static
Definition at line 178 of file Type.cpp.
{
     std::set<TypeAttribute> typeAttributes;
     if (const auto* inf = dynamic_cast<const IntrinsicFunctor*>(arg)) {
         // intrinsic functor type is its return type if its set
isStatefulFunctor()
bool souffle::ast::analysis::TypeAnalysis::isStatefulFunctor (const UserDefinedFunctor * udf) const
Definition at line 170 of file Type.cpp.
{
isSymbol()
bool souffle::ast::analysis::TypeAnalysis::isSymbol (const Argument * argument) const private
Definition at line 443 of file Type.cpp.
{
         debugStream = &analysisLogs;
References analysisLogs.
isUnsigned()
bool souffle::ast::analysis::TypeAnalysis::isUnsigned (const Argument * argument) const private
Definition at line 439 of file Type.cpp.
{
print()
void souffle::ast::analysis::TypeAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 136 of file Type.cpp.
{
     assert(hasValidTypeInfo(functor) && "type of functor not processed");
     if (auto* intrinsic = as<IntrinsicFunctor>(functor)) {
         return functorInfo.at(intrinsic)->result;
     } else if (const auto* udf = as<UserDefinedFunctor>(functor)) {
run()
void souffle::ast::analysis::TypeAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 447 of file Type.cpp.
                                                           { udfDeclaration[fdecl.getName()] = &fdecl; });
     // Rest of the analysis done until fixpoint reached
     bool changed = true;
     while (changed) {
         changed = false;
         argumentTypes.clear();
         // Analyse general argument types, clause by clause.
         for (const Clause* clause : program.getClauses()) {
             auto clauseArgumentTypes = analyseTypes(translationUnit, *clause, debugStream);
             argumentTypes.insert(clauseArgumentTypes.begin(), clauseArgumentTypes.end());
             if (debugStream != nullptr) {
                 // Store an annotated clause for printing purposes
                 annotatedClauses.emplace_back(createAnnotatedClause(clause, clauseArgumentTypes));
             }
         }
         // Analyse intrinsic-functor types
         changed |= analyseIntrinsicFunctors(translationUnit);
         // Deduce numeric-constant polymorphism
         changed |= analyseNumericConstants(translationUnit);
         // Deduce aggregator polymorphism
         changed |= analyseAggregators(translationUnit);
         // Deduce binary-constraint polymorphism
         changed |= analyseBinaryConstraints(translationUnit);
     }
 }
 }  // namespace souffle::ast::analysis
References souffle::ast::FunctorDeclaration::getName(), and udfDeclaration.
Field Documentation
aggregatorType
std::map<const Aggregator*, AggregateOp> souffle::ast::analysis::TypeAnalysis::aggregatorType private
Definition at line 105 of file Type.h.
analysisLogs
std::stringstream souffle::ast::analysis::TypeAnalysis::analysisLogs private
Definition at line 95 of file Type.h.
Referenced by isSymbol().
annotatedClauses
VecOwn<Clause> souffle::ast::analysis::TypeAnalysis::annotatedClauses private
Definition at line 94 of file Type.h.
argumentTypes
std::map<const Argument*, TypeSet> souffle::ast::analysis::TypeAnalysis::argumentTypes private
Definition at line 93 of file Type.h.
Referenced by getTypes().
constraintType
std::map<const BinaryConstraint*, BinaryConstraintOp> souffle::ast::analysis::TypeAnalysis::constraintType private
Definition at line 106 of file Type.h.
functorInfo
std::map<const IntrinsicFunctor*, const IntrinsicFunctorInfo*> souffle::ast::analysis::TypeAnalysis::functorInfo private
Definition at line 102 of file Type.h.
Referenced by analyseIntrinsicFunctors().
name
constexpr const char* souffle::ast::analysis::TypeAnalysis::name = "type-analysis" static constexpr
Definition at line 47 of file Type.h.
numericConstantType
std::map<const NumericConstant*, NumericConstant::Type> souffle::ast::analysis::TypeAnalysis::numericConstantType private
Definition at line 104 of file Type.h.
udfDeclaration
std::map<std::string, const FunctorDeclaration*> souffle::ast::analysis::TypeAnalysis::udfDeclaration private
Definition at line 103 of file Type.h.
Referenced by run().
The documentation for this class was generated from the following files:
ast/analysis/Type.h
ast/analysis/Type.cpp