souffle: souffle::interpreter::Engine Class Reference
souffle::interpreter::Engine Class Reference
This class translate the RAM Program into executable format and interpreter it.
#include <Engine.h>
Public Member Functions
Engine (ram::TranslationUnit &tUnit)
void executeMain ()
Execute the main program.
void executeSubroutine (const std::string &name, const std::vector< RamDomain > &args, std::vector< RamDomain > &ret)
Execute the subroutine program.
Private Types
using RelationHandle = Own< RelationWrapper >
Private Member Functions
void createRelation (const ram::Relation &id, const size_t idx)
Create and add relation into the runtime environment.
void dropRelation (const size_t relId)
Remove a relation from the environment.
template<typename Aggregate , typename Iter >
RamDomain evalAggregate (const Aggregate &aggregate, const Node &filter, const Node *expression, const Node &nestedOperation, const Iter &ranges, Context &ctxt)
template<typename Rel >
RamDomain evalChoice (const Rel &rel, const ram::Choice &cur, const Choice &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalExistenceCheck (const ExistenceCheck &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalIndexAggregate (const ram::IndexAggregate &cur, const IndexAggregate &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalIndexChoice (const ram::IndexChoice &cur, const IndexChoice &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalIndexScan (const ram::IndexScan &cur, const IndexScan &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalParallelAggregate (const Rel &rel, const ram::ParallelAggregate &cur, const ParallelAggregate &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalParallelChoice (const Rel &rel, const ram::ParallelChoice &cur, const ParallelChoice &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalParallelIndexAggregate (const ram::ParallelIndexAggregate &cur, const ParallelIndexAggregate &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalParallelIndexChoice (const Rel &rel, const ram::ParallelIndexChoice &cur, const ParallelIndexChoice &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalParallelIndexScan (const Rel &rel, const ram::ParallelIndexScan &cur, const ParallelIndexScan &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalParallelScan (const Rel &rel, const ram::ParallelScan &cur, const ParallelScan &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalProject (Rel &rel, const Project &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalProvenanceExistenceCheck (const ProvenanceExistenceCheck &shadow, Context &ctxt)
template<typename Rel >
RamDomain evalScan (const Rel &rel, const ram::Scan &cur, const Scan &shadow, Context &ctxt)
RamDomain execute (const Node *, Context &)
Execute the program.
void generateIR ()
Generate intermediate representation from RAM.
size_t getIterationNumber () const
Return current iteration number for loop operation.
void * getMethodHandle (const std::string &method)
Return method handler.
RecordTable & getRecordTable ()
Return the record table.
RelationHandle & getRelationHandle (const size_t idx)
Return a reference to the relation on the given index.
VecOwn< RelationHandle > & getRelationMap ()
Return the relation map.
SymbolTable & getSymbolTable ()
Return the string symbol table.
ram::TranslationUnit & getTranslationUnit ()
Return the ram::TranslationUnit.
int incCounter ()
Increment the counter.
void incIterationNumber ()
Increase iteration number by one.
const std::vector< void * > & loadDLL ()
Load DLL.
void resetIterationNumber ()
Reset iteration number.
void swapRelation (const size_t ramRel1, const size_t ramRel2)
Swap the content of two relations.
Private Attributes
std::atomic< RamDomain > counter {0}
Profile counter.
std::vector< void * > dll
DLL.
std::map< std::string, std::deque< std::atomic< size_t > > > frequencies
Profile for rule frequencies.
ram::analysis::IndexAnalysis * isa
IndexAnalysis.
const bool isProvenance
If running a provenance program.
size_t iteration = 0
Loop iteration counter.
Own< Node > main
main program
friend NodeGenerator
size_t numOfThreads
Number of threads enabled for this program.
const bool profileEnabled
If profile is enable in this program.
friend ProgInterface
std::map< std::string, std::atomic< size_t > > reads
Profile for relation reads.
RecordTable recordTable
Record Table.
VecOwn< RelationHandle > relations
Symbol table for relations.
VecOwn< Node > subroutine
subroutines
ram::TranslationUnit & tUnit
Program.
Detailed Description
This class translate the RAM Program into executable format and interpreter it.
Definition at line 56 of file Engine.h.
Member Typedef Documentation
RelationHandle
using souffle::interpreter::Engine::RelationHandle = Own<RelationWrapper> private
Definition at line 57 of file Engine.h.
Constructor & Destructor Documentation
Engine()
souffle::interpreter::Engine::Engine (ram::TranslationUnit & tUnit)
Definition at line 146 of file Engine.cpp.
{
         omp_set_num_threads(numOfThreads);
     }
 #endif
 }
 Engine::RelationHandle& Engine::getRelationHandle(const size_t idx) {
     return *relations[idx];
 }
Member Function Documentation
createRelation()
void souffle::interpreter::Engine::createRelation (const ram::Relation & id, const size_t idx) private
Create and add relation into the runtime environment.
Definition at line 198 of file Engine.cpp.
{
         res = createEqrelRelation(id, orderSet);
     } else {
         if (isProvenance) {
             res = createProvenanceRelation(id, orderSet);
         } else {
             res = createBTreeRelation(id, orderSet);
         }
     }
     relations[idx] = mk<RelationHandle>(std::move(res));
 }
 const std::vector<void*>& Engine::loadDLL() {
     if (!dll.empty()) {
         return dll;
     }
References souffle::interpreter::createEqrelRelation().
dropRelation()
void souffle::interpreter::Engine::dropRelation (const size_t relId) private
Remove a relation from the environment.
evalAggregate()
template<typename Aggregate , typename Iter > RamDomain souffle::interpreter::Engine::evalAggregate (const Aggregate & aggregate, const Node & filter, const Node * expression, const Node & nestedOperation, const Iter & ranges, Context & ctxt) private
Definition at line 1511 of file Engine.cpp.
{
         case AggregateOp::MIN: res = ramBitCast(MAX_RAM_SIGNED); break;
         case AggregateOp::UMIN: res = ramBitCast(MAX_RAM_UNSIGNED); break;
         case AggregateOp::FMIN: res = ramBitCast(MAX_RAM_FLOAT); break;
         case AggregateOp::MAX: res = ramBitCast(MIN_RAM_SIGNED); break;
         case AggregateOp::UMAX: res = ramBitCast(MIN_RAM_UNSIGNED); break;
         case AggregateOp::FMAX: res = ramBitCast(MIN_RAM_FLOAT); break;
         case AggregateOp::SUM:
             res = ramBitCast(static_cast<RamSigned>(0));
             shouldRunNested = true;
             break;
         case AggregateOp::USUM:
             res = ramBitCast(static_cast<RamUnsigned>(0));
             shouldRunNested = true;
             break;
         case AggregateOp::FSUM:
             res = ramBitCast(static_cast<RamFloat>(0));
             shouldRunNested = true;
             break;
         case AggregateOp::MEAN:
             res = 0;
             accumulateMean = {0, 0};
             break;
         case AggregateOp::COUNT:
             res = 0;
             shouldRunNested = true;
             break;
     }
     for (const auto& tuple : ranges) {
         ctxt[aggregate.getTupleId()] = tuple.data();
         if (!execute(&filter, ctxt)) {
             continue;
         }
         shouldRunNested = true;
         // count is a special case.
         if (aggregate.getFunction() == AggregateOp::COUNT) {
             ++res;
             continue;
         }
         // eval target expression
         assert(expression);  // only case where this is null is `COUNT`
         RamDomain val = execute(expression, ctxt);
         switch (aggregate.getFunction()) {
             case AggregateOp::MIN: res = std::min(res, val); break;
             case AggregateOp::FMIN:
                 res = ramBitCast(std::min(ramBitCast<RamFloat>(res), ramBitCast<RamFloat>(val)));
                 break;
             case AggregateOp::UMIN:
                 res = ramBitCast(std::min(ramBitCast<RamUnsigned>(res), ramBitCast<RamUnsigned>(val)));
                 break;
             case AggregateOp::MAX: res = std::max(res, val); break;
             case AggregateOp::FMAX:
                 res = ramBitCast(std::max(ramBitCast<RamFloat>(res), ramBitCast<RamFloat>(val)));
                 break;
             case AggregateOp::UMAX:
                 res = ramBitCast(std::max(ramBitCast<RamUnsigned>(res), ramBitCast<RamUnsigned>(val)));
                 break;
             case AggregateOp::SUM: res += val; break;
             case AggregateOp::FSUM:
                 res = ramBitCast(ramBitCast<RamFloat>(res) + ramBitCast<RamFloat>(val));
                 break;
             case AggregateOp::USUM:
                 res = ramBitCast(ramBitCast<RamUnsigned>(res) + ramBitCast<RamUnsigned>(val));
                 break;
             case AggregateOp::MEAN:
                 accumulateMean.first += ramBitCast<RamFloat>(val);
                 accumulateMean.second++;
                 break;
             case AggregateOp::COUNT: fatal("This should never be executed");
         }
     }
     if (aggregate.getFunction() == AggregateOp::MEAN && accumulateMean.second != 0) {
         res = ramBitCast(accumulateMean.first / accumulateMean.second);
     }
     // write result to environment
     souffle::Tuple<RamDomain, 1> tuple;
     tuple[0] = res;
     ctxt[aggregate.getTupleId()] = tuple.data();
     if (!shouldRunNested) {
         return true;
     } else {
         return execute(&nestedOperation, ctxt);
     }
 }
 template <typename Rel>
 RamDomain Engine::evalParallelAggregate(
         const Rel& rel, const ram::ParallelAggregate& cur, const ParallelAggregate& shadow, Context& ctxt) {
     // TODO (rdowavic): make parallel
     auto viewContext = shadow.getViewContext();
References souffle::MAX_RAM_FLOAT, souffle::MAX_RAM_SIGNED, souffle::MAX_RAM_UNSIGNED, souffle::MIN_RAM_FLOAT, souffle::MIN_RAM_SIGNED, souffle::MIN_RAM_UNSIGNED, and souffle::ramBitCast().
evalChoice()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalChoice (const Rel & rel, const ram::Choice & cur, const Choice & shadow, Context & ctxt) private
Definition at line 1416 of file Engine.cpp.
{
     auto viewContext = shadow.getViewContext();
evalExistenceCheck()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalExistenceCheck (const ExistenceCheck & shadow, Context & ctxt) private
Definition at line 1237 of file Engine.cpp.
{
         souffle::Tuple<RamDomain, Arity> tuple;
         TUPLE_COPY_FROM(tuple, superInfo.first);
         /* TupleElement */
         for (const auto& tupleElement : superInfo.tupleFirst) {
             tuple[tupleElement[0]] = ctxt[tupleElement[1]][tupleElement[2]];
         }
         /* Generic */
         for (const auto& expr : superInfo.exprFirst) {
             tuple[expr.first] = execute(expr.second.get(), ctxt);
         }
         return Rel::castView(ctxt.getView(viewPos))->contains(tuple);
     }
     // for partial we search for lower and upper boundaries
     souffle::Tuple<RamDomain, Arity> low;
     souffle::Tuple<RamDomain, Arity> high;
     TUPLE_COPY_FROM(low, superInfo.first);
     TUPLE_COPY_FROM(high, superInfo.second);
     /* TupleElement */
     for (const auto& tupleElement : superInfo.tupleFirst) {
         low[tupleElement[0]] = ctxt[tupleElement[1]][tupleElement[2]];
         high[tupleElement[0]] = low[tupleElement[0]];
     }
     /* Generic */
     for (const auto& expr : superInfo.exprFirst) {
         low[expr.first] = execute(expr.second.get(), ctxt);
         high[expr.first] = low[expr.first];
     }
     return Rel::castView(ctxt.getView(viewPos))->contains(low, high);
 }
 template <typename Rel>
 RamDomain Engine::evalProvenanceExistenceCheck(const ProvenanceExistenceCheck& shadow, Context& ctxt) {
     // construct the pattern tuple
     constexpr size_t Arity = Rel::Arity;
evalIndexAggregate()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalIndexAggregate (const ram::IndexAggregate & cur, const IndexAggregate & shadow, Context & ctxt) private
Definition at line 1664 of file Engine.cpp.
{
     constexpr size_t Arity = Rel::Arity;
     const auto& superInfo = shadow.getSuperInst();
evalIndexChoice()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalIndexChoice (const ram::IndexChoice & cur, const IndexChoice & shadow, Context & ctxt) private
Definition at line 1454 of file Engine.cpp.
                            : view->range(low, high)) {
         ctxt[cur.getTupleId()] = tuple.data();
         if (execute(shadow.getCondition(), ctxt)) {
             execute(shadow.getNestedOperation(), ctxt);
             break;
         }
     }
     return true;
 }
 template <typename Rel>
 RamDomain Engine::evalParallelIndexChoice(const Rel& rel, const ram::ParallelIndexChoice& cur,
         const ParallelIndexChoice& shadow, Context& ctxt) {
     auto viewContext = shadow.getViewContext();
evalIndexScan()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalIndexScan (const ram::IndexScan & cur, const IndexScan & shadow, Context & ctxt) private
Definition at line 1363 of file Engine.cpp.
                            : view->range(low, high)) {
         ctxt[cur.getTupleId()] = tuple.data();
         if (!execute(shadow.getNestedOperation(), ctxt)) {
             break;
         }
     }
     return true;
 }
 template <typename Rel>
 RamDomain Engine::evalParallelIndexScan(
         const Rel& rel, const ram::ParallelIndexScan& cur, const ParallelIndexScan& shadow, Context& ctxt) {
     auto viewContext = shadow.getViewContext();
evalParallelAggregate()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalParallelAggregate (const Rel & rel, const ram::ParallelAggregate & cur, const ParallelAggregate & shadow, Context & ctxt) private
Definition at line 1623 of file Engine.cpp.
                           : viewInfo) {
         newCtxt.createView(*getRelationHandle(info[0]), info[1], info[2]);
     }
     return evalAggregate(
             cur, *shadow.getCondition(), shadow.getExpr(), *shadow.getNestedOperation(), rel.scan(), newCtxt);
 }
 template <typename Rel>
 RamDomain Engine::evalParallelIndexAggregate(
         const ram::ParallelIndexAggregate& cur, const ParallelIndexAggregate& shadow, Context& ctxt) {
     // TODO (rdowavic): make parallel
evalParallelChoice()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalParallelChoice (const Rel & rel, const ram::ParallelChoice & cur, const ParallelChoice & shadow, Context & ctxt) private
Definition at line 1429 of file Engine.cpp.
                               : viewInfo) {
             newCtxt.createView(*getRelationHandle(info[0]), info[1], info[2]);
         }
         pfor(auto it = pStream.begin(); it < pStream.end(); it++) {
             for (const auto& tuple : *it) {
                 newCtxt[cur.getTupleId()] = tuple.data();
                 if (execute(shadow.getCondition(), newCtxt)) {
                     execute(shadow.getNestedOperation(), newCtxt);
                     break;
                 }
             }
         }
     PARALLEL_END
     return true;
 }
 template <typename Rel>
 RamDomain Engine::evalIndexChoice(const ram::IndexChoice& cur, const IndexChoice& shadow, Context& ctxt) {
     constexpr size_t Arity = Rel::Arity;
     const auto& superInfo = shadow.getSuperInst();
evalParallelIndexAggregate()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalParallelIndexAggregate (const ram::ParallelIndexAggregate & cur, const ParallelIndexAggregate & shadow, Context & ctxt) private
Definition at line 1638 of file Engine.cpp.
                           : viewInfo) {
         newCtxt.createView(*getRelationHandle(info[0]), info[1], info[2]);
     }
     // init temporary tuple for this level
     constexpr size_t Arity = Rel::Arity;
     const auto& superInfo = shadow.getSuperInst();
     // get lower and upper boundaries for iteration
     souffle::Tuple<RamDomain, Arity> low;
     souffle::Tuple<RamDomain, Arity> high;
     CAL_SEARCH_BOUND(superInfo, low, high);
     size_t viewId = shadow.getViewId();
     auto view = Rel::castView(newCtxt.getView(viewId));
     return evalAggregate(cur, *shadow.getCondition(), shadow.getExpr(), *shadow.getNestedOperation(),
             view->range(low, high), newCtxt);
 }
 template <typename Rel>
 RamDomain Engine::evalIndexAggregate(
         const ram::IndexAggregate& cur, const IndexAggregate& shadow, Context& ctxt) {
     // init temporary tuple for this level
evalParallelIndexChoice()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalParallelIndexChoice (const Rel & rel, const ram::ParallelIndexChoice & cur, const ParallelIndexChoice & shadow, Context & ctxt) private
Definition at line 1475 of file Engine.cpp.
                               : viewInfo) {
             newCtxt.createView(*getRelationHandle(info[0]), info[1], info[2]);
         }
         pfor(auto it = pStream.begin(); it < pStream.end(); it++) {
             for (const auto& tuple : *it) {
                 newCtxt[cur.getTupleId()] = tuple.data();
                 if (execute(shadow.getCondition(), newCtxt)) {
                     execute(shadow.getNestedOperation(), newCtxt);
                     break;
                 }
             }
         }
     PARALLEL_END
     return true;
 }
 template <typename Aggregate, typename Iter>
 RamDomain Engine::evalAggregate(const Aggregate& aggregate, const Node& filter, const Node* expression,
         const Node& nestedOperation, const Iter& ranges, Context& ctxt) {
     bool shouldRunNested = false;
evalParallelIndexScan()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalParallelIndexScan (const Rel & rel, const ram::ParallelIndexScan & cur, const ParallelIndexScan & shadow, Context & ctxt) private
Definition at line 1384 of file Engine.cpp.
                               : viewInfo) {
             newCtxt.createView(*getRelationHandle(info[0]), info[1], info[2]);
         }
         pfor(auto it = pStream.begin(); it < pStream.end(); it++) {
             for (const auto& tuple : *it) {
                 newCtxt[cur.getTupleId()] = tuple.data();
                 if (!execute(shadow.getNestedOperation(), newCtxt)) {
                     break;
                 }
             }
         }
     PARALLEL_END
     return true;
 }
 template <typename Rel>
 RamDomain Engine::evalChoice(const Rel& rel, const ram::Choice& cur, const Choice& shadow, Context& ctxt) {
     // use simple iterator
     for (const auto& tuple : rel.scan()) {
evalParallelScan()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalParallelScan (const Rel & rel, const ram::ParallelScan & cur, const ParallelScan & shadow, Context & ctxt) private
Definition at line 1338 of file Engine.cpp.
                               : viewInfo) {
             newCtxt.createView(*getRelationHandle(info[0]), info[1], info[2]);
         }
         pfor(auto it = pStream.begin(); it < pStream.end(); it++) {
             for (const auto& tuple : *it) {
                 newCtxt[cur.getTupleId()] = tuple.data();
                 if (!execute(shadow.getNestedOperation(), newCtxt)) {
                     break;
                 }
             }
         }
     PARALLEL_END
     return true;
 }
 template <typename Rel>
 RamDomain Engine::evalIndexScan(const ram::IndexScan& cur, const IndexScan& shadow, Context& ctxt) {
     constexpr size_t Arity = Rel::Arity;
     // create pattern tuple for range query
evalProject()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalProject (Rel & rel, const Project & shadow, Context & ctxt) private
Definition at line 1681 of file Engine.cpp.
                                   : superInfo.tupleFirst) {
         tuple[tupleElement[0]] = ctxt[tupleElement[1]][tupleElement[2]];
     }
     /* Generic */
     for (const auto& expr : superInfo.exprFirst) {
         tuple[expr.first] = execute(expr.second.get(), ctxt);
     }
     // insert in target relation
     rel.insert(tuple);
     return true;
 }
 }  // namespace souffle::interpreter
evalProvenanceExistenceCheck()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalProvenanceExistenceCheck (const ProvenanceExistenceCheck & shadow, Context & ctxt) private
Definition at line 1282 of file Engine.cpp.
                                   : superInfo.tupleFirst) {
         low[tupleElement[0]] = ctxt[tupleElement[1]][tupleElement[2]];
         high[tupleElement[0]] = low[tupleElement[0]];
     }
     /* Generic */
     for (const auto& expr : superInfo.exprFirst) {
         assert(expr.second.get() != nullptr &&
                 "ProvenanceExistenceCheck should always be specified for payload");
         low[expr.first] = execute(expr.second.get(), ctxt);
         high[expr.first] = low[expr.first];
     }
     low[Arity - 2] = MIN_RAM_SIGNED;
     low[Arity - 1] = MIN_RAM_SIGNED;
     high[Arity - 2] = MAX_RAM_SIGNED;
     high[Arity - 1] = MAX_RAM_SIGNED;
     // obtain view
     size_t viewPos = shadow.getViewId();
     // get an equalRange
     auto equalRange = Rel::castView(ctxt.getView(viewPos))->range(low, high);
     // if range is empty
     if (equalRange.begin() == equalRange.end()) {
         return false;
     }
     // check whether the height is less than the current height
     return (*equalRange.begin())[Arity - 1] <= execute(shadow.getChild(), ctxt);
 }
 template <typename Rel>
 RamDomain Engine::evalScan(const Rel& rel, const ram::Scan& cur, const Scan& shadow, Context& ctxt) {
     for (const auto& tuple : rel.scan()) {
         ctxt[cur.getTupleId()] = tuple.data();
evalScan()
template<typename Rel > RamDomain souffle::interpreter::Engine::evalScan (const Rel & rel, const ram::Scan & cur, const Scan & shadow, Context & ctxt) private
Definition at line 1327 of file Engine.cpp.
{
     auto viewContext = shadow.getViewContext();
execute()
RamDomain souffle::interpreter::Engine::execute (const Node * node, Context & ctxt) private
Execute the program.
Unary Functor Operators
numeric coersions follow C++ semantics.
Binary Functor Operators
Ternary Functor Operators
Definition at line 359 of file Engine.cpp.
                    : {  \
         return [&]() -> RamDomain { \
             [[maybe_unused]] const auto& shadow = *static_cast<const interpreter::Kind*>(node); \
             [[maybe_unused]] const auto& cur = *static_cast<const ram::Kind*>(node->getShadow());
 // EXTEND_CASE also defer the relation type
 #define EXTEND_CASE(Kind, Structure, Arity)    \
     case (I_##Kind##_##Structure##_##Arity): { \
         return [&]() -> RamDomain { \
             [[maybe_unused]] const auto& shadow = *static_cast<const interpreter::Kind*>(node); \
             [[maybe_unused]] const auto& cur = *static_cast<const ram::Kind*>(node->getShadow());\
             using RelType = Relation<Arity, interpreter::Structure>;
 #define ESAC(Kind) \
     }              \
     ();            \
     }
 #define TUPLE_COPY_FROM(dst, src)     \
     assert(dst.size() == src.size()); \
     std::copy_n(src.begin(), dst.size(), dst.begin())
 #define CAL_SEARCH_BOUND(superInfo, low, high)                          \
     /** Unbounded and Constant */                                       \
     TUPLE_COPY_FROM(low, superInfo.first);                              \
     TUPLE_COPY_FROM(high, superInfo.second);                            \
     /* TupleElement */                                                  \
     for (const auto& tupleElement : superInfo.tupleFirst) {             \
         low[tupleElement[0]] = ctxt[tupleElement[1]][tupleElement[2]];  \
     }                                                                   \
     for (const auto& tupleElement : superInfo.tupleSecond) {            \
         high[tupleElement[0]] = ctxt[tupleElement[1]][tupleElement[2]]; \
     }                                                                   \
     /* Generic */                                                       \
     for (const auto& expr : superInfo.exprFirst) {                      \
         low[expr.first] = execute(expr.second.get(), ctxt);             \
     }                                                                   \
     for (const auto& expr : superInfo.exprSecond) {                     \
         high[expr.first] = execute(expr.second.get(), ctxt);            \
     }
     switch (node->getType()) {
         CASE(Constant)
             return cur.getConstant();
         ESAC(Constant)
         CASE(TupleElement)
             return ctxt[shadow.getTupleId()][shadow.getElement()];
         ESAC(TupleElement)
         CASE(AutoIncrement)
             return incCounter();
         ESAC(AutoIncrement)
         CASE(IntrinsicOperator)
 // clang-format off
 #define BINARY_OP_TYPED(ty, op) return ramBitCast(static_cast<ty>(EVAL_CHILD(ty, 0) op EVAL_CHILD(ty, 1)))
 #define BINARY_OP_LOGICAL(opcode, op) BINARY_OP_INTEGRAL(opcode, op)
 #define BINARY_OP_INTEGRAL(opcode, op)                           \
     case FunctorOp::   opcode: BINARY_OP_TYPED(RamSigned  , op); \
     case FunctorOp::U##opcode: BINARY_OP_TYPED(RamUnsigned, op);
 #define BINARY_OP_NUMERIC(opcode, op)                         \
     BINARY_OP_INTEGRAL(opcode, op)                            \
     case FunctorOp::F##opcode: BINARY_OP_TYPED(RamFloat, op);
 #define BINARY_OP_SHIFT_MASK(ty, op)                                                 \
     return ramBitCast(EVAL_CHILD(ty, 0) op (EVAL_CHILD(ty, 1) & RAM_BIT_SHIFT_MASK))
 #define BINARY_OP_INTEGRAL_SHIFT(opcode, op, tySigned, tyUnsigned)    \
     case FunctorOp::   opcode: BINARY_OP_SHIFT_MASK(tySigned   , op); \
     case FunctorOp::U##opcode: BINARY_OP_SHIFT_MASK(tyUnsigned , op);
 #define MINMAX_OP_SYM(op)                                        \
     {                                                            \
         auto result = EVAL_CHILD(RamDomain, 0);                  \
         auto* result_val = &getSymbolTable().resolve(result);    \
         for (size_t i = 1; i < args.size(); i++) {               \
             auto alt = EVAL_CHILD(RamDomain, i);                 \
             if (alt == result) continue;                         \
                                                                  \
             const auto& alt_val = getSymbolTable().resolve(alt); \
             if (*result_val op alt_val) {                        \
                 result_val = &alt_val;                           \
                 result = alt;                                    \
             }                                                    \
         }                                                        \
         return result;                                           \
     }
 #define MINMAX_OP(ty, op)                           \
     {                                               \
         auto result = EVAL_CHILD(ty, 0);            \
         for (size_t i = 1; i < args.size(); i++) {  \
             result = op(result, EVAL_CHILD(ty, i)); \
         }                                           \
         return ramBitCast(result);                  \
     }
 #define MINMAX_NUMERIC(opCode, op)                        \
     case FunctorOp::   opCode: MINMAX_OP(RamSigned  , op) \
     case FunctorOp::U##opCode: MINMAX_OP(RamUnsigned, op) \
     case FunctorOp::F##opCode: MINMAX_OP(RamFloat   , op)
 #define UNARY_OP(op, ty, func)                                      \
     case FunctorOp::op: { \
         auto x = EVAL_CHILD(ty, 0); \
         return ramBitCast(func(x)); \
     }
 #define CONV_TO_STRING(op, ty)                                                             \
     case FunctorOp::op: return getSymbolTable().lookup(std::to_string(EVAL_CHILD(ty, 0)));
 #define CONV_FROM_STRING(op, ty)                              \
     case FunctorOp::op: return evaluator::symbol2numeric<ty>( \
         getSymbolTable().resolve(EVAL_CHILD(RamDomain, 0)));
             // clang-format on
             const auto& args = cur.getArguments();
             switch (cur.getOperator()) {
                 /** Unary Functor Operators */
                 case FunctorOp::ORD: return execute(shadow.getChild(0), ctxt);
                 case FunctorOp::STRLEN:
                     return getSymbolTable().resolve(execute(shadow.getChild(0), ctxt)).size();
                 case FunctorOp::NEG: return -execute(shadow.getChild(0), ctxt);
                 case FunctorOp::FNEG: {
                     RamDomain result = execute(shadow.getChild(0), ctxt);
                     return ramBitCast(-ramBitCast<RamFloat>(result));
                 }
                 case FunctorOp::BNOT: return ~execute(shadow.getChild(0), ctxt);
                 case FunctorOp::UBNOT: {
                     RamDomain result = execute(shadow.getChild(0), ctxt);
                     return ramBitCast(~ramBitCast<RamUnsigned>(result));
                 }
                 case FunctorOp::LNOT: return !execute(shadow.getChild(0), ctxt);
                 case FunctorOp::ULNOT: {
                     RamDomain result = execute(shadow.getChild(0), ctxt);
                     // Casting is a bit tricky here, since ! returns a boolean.
                     return ramBitCast(static_cast<RamUnsigned>(!ramBitCast<RamUnsigned>(result)));
                 }
                     // clang-format off
                 /** numeric coersions follow C++ semantics. */
                 UNARY_OP(F2I, RamFloat   , static_cast<RamSigned>)
                 UNARY_OP(F2U, RamFloat   , static_cast<RamUnsigned>)
                 UNARY_OP(I2U, RamSigned  , static_cast<RamUnsigned>)
                 UNARY_OP(I2F, RamSigned  , static_cast<RamFloat>)
                 UNARY_OP(U2I, RamUnsigned, static_cast<RamSigned>)
                 UNARY_OP(U2F, RamUnsigned, static_cast<RamFloat>)
                 CONV_TO_STRING(F2S, RamFloat)
                 CONV_TO_STRING(I2S, RamSigned)
                 CONV_TO_STRING(U2S, RamUnsigned)
                 CONV_FROM_STRING(S2F, RamFloat)
                 CONV_FROM_STRING(S2I, RamSigned)
                 CONV_FROM_STRING(S2U, RamUnsigned)
                 /** Binary Functor Operators */
                 BINARY_OP_NUMERIC(ADD, +)
                 BINARY_OP_NUMERIC(SUB, -)
                 BINARY_OP_NUMERIC(MUL, *)
                 BINARY_OP_NUMERIC(DIV, /)
                     // clang-format on
                 case FunctorOp::EXP: {
                     return std::pow(execute(shadow.getChild(0), ctxt), execute(shadow.getChild(1), ctxt));
                 }
                 case FunctorOp::UEXP: {
                     auto first = ramBitCast<RamUnsigned>(execute(shadow.getChild(0), ctxt));
                     auto second = ramBitCast<RamUnsigned>(execute(shadow.getChild(1), ctxt));
                     // Extra casting required: pow returns a floating point.
                     return ramBitCast(static_cast<RamUnsigned>(std::pow(first, second)));
                 }
                 case FunctorOp::FEXP: {
                     auto first = ramBitCast<RamFloat>(execute(shadow.getChild(0), ctxt));
                     auto second = ramBitCast<RamFloat>(execute(shadow.getChild(1), ctxt));
                     return ramBitCast(static_cast<RamFloat>(std::pow(first, second)));
                 }
                     // clang-format off
                 BINARY_OP_INTEGRAL(MOD, %)
                 BINARY_OP_INTEGRAL(BAND, &)
                 BINARY_OP_INTEGRAL(BOR, |)
                 BINARY_OP_INTEGRAL(BXOR, ^)
                 // Handle left-shift as unsigned to match Java semantics of `<<`, namely:
                 //  "... `n << s` is `n` left-shifted `s` bit positions; ..."
                 // Using `RamSigned` would imply UB due to signed overflow when shifting negatives.
                 BINARY_OP_INTEGRAL_SHIFT(BSHIFT_L         , <<, RamUnsigned, RamUnsigned)
                 // For right-shift, we do need sign extension.
                 BINARY_OP_INTEGRAL_SHIFT(BSHIFT_R         , >>, RamSigned  , RamUnsigned)
                 BINARY_OP_INTEGRAL_SHIFT(BSHIFT_R_UNSIGNED, >>, RamUnsigned, RamUnsigned)
                 BINARY_OP_LOGICAL(LAND, &&)
                 BINARY_OP_LOGICAL(LOR , ||)
                 BINARY_OP_LOGICAL(LXOR, + souffle::evaluator::lxor_infix() +)
                 MINMAX_NUMERIC(MAX, std::max)
                 MINMAX_NUMERIC(MIN, std::min)
                 case FunctorOp::SMAX: MINMAX_OP_SYM(<)
                 case FunctorOp::SMIN: MINMAX_OP_SYM(>)
                     // clang-format on
                 case FunctorOp::CAT: {
                     std::stringstream ss;
                     for (size_t i = 0; i < args.size(); i++) {
                         ss << getSymbolTable().resolve(execute(shadow.getChild(i), ctxt));
                     }
                     return getSymbolTable().lookup(ss.str());
                 }
                 /** Ternary Functor Operators */
                 case FunctorOp::SUBSTR: {
                     auto symbol = execute(shadow.getChild(0), ctxt);
                     const std::string& str = getSymbolTable().resolve(symbol);
                     auto idx = execute(shadow.getChild(1), ctxt);
                     auto len = execute(shadow.getChild(2), ctxt);
                     std::string sub_str;
                     try {
                         sub_str = str.substr(idx, len);
                     } catch (...) {
                         std::cerr << "warning: wrong index position provided by substr(\"";
                         std::cerr << str << "\"," << (int32_t)idx << "," << (int32_t)len << ") functor.\n";
                     }
                     return getSymbolTable().lookup(sub_str);
                 }
                 case FunctorOp::RANGE:
                 case FunctorOp::URANGE:
                 case FunctorOp::FRANGE:
                     fatal("ICE: functor `%s` must map onto `NestedIntrinsicOperator`", cur.getOperator());
             }
             { UNREACHABLE_BAD_CASE_ANALYSIS }
 #undef BINARY_OP_LOGICAL
 #undef BINARY_OP_INTEGRAL
 #undef BINARY_OP_NUMERIC
 #undef BINARY_OP_SHIFT_MASK
 #undef BINARY_OP_INTEGRAL_SHIFT
 #undef MINMAX_OP_SYM
 #undef MINMAX_OP
 #undef MINMAX_NUMERIC
 #undef UNARY_OP
 #undef CONV_TO_STRING
 #undef CONV_FROM_STRING
         ESAC(IntrinsicOperator)
         CASE(NestedIntrinsicOperator)
             auto numArgs = cur.getArguments().size();
             auto runNested = [&](auto&& tuple) {
                 ctxt[cur.getTupleId()] = tuple.data();
                 execute(shadow.getChild(numArgs), ctxt);
             };
 #define RUN_RANGE(ty)                                                                                     \
     numArgs == 3                                                                                          \
             ? evaluator::runRange<ty>(EVAL_CHILD(ty, 0), EVAL_CHILD(ty, 1), EVAL_CHILD(ty, 2), runNested) \
             : evaluator::runRange<ty>(EVAL_CHILD(ty, 0), EVAL_CHILD(ty, 1), runNested),                   \
             true
             switch (cur.getFunction()) {
                 case ram::NestedIntrinsicOp::RANGE: return RUN_RANGE(RamSigned);
                 case ram::NestedIntrinsicOp::URANGE: return RUN_RANGE(RamUnsigned);
                 case ram::NestedIntrinsicOp::FRANGE: return RUN_RANGE(RamFloat);
             }
             { UNREACHABLE_BAD_CASE_ANALYSIS }
 #undef RUN_RANGE
         ESAC(NestedIntrinsicOperator)
         CASE(UserDefinedOperator)
             const std::string& name = cur.getName();
             auto fn = reinterpret_cast<void (*)()>(getMethodHandle(name));
             if (fn == nullptr) fatal("cannot find user-defined operator `%s`", name);
             size_t arity = cur.getArguments().size();
             if (cur.isStateful()) {
                 // prepare dynamic call environment
                 ffi_cif cif;
                 ffi_type* args[arity + 2];
                 void* values[arity + 2];
                 RamDomain intVal[arity];
                 ffi_arg rc;
                 /* Initialize arguments for ffi-call */
                 args[0] = args[1] = &ffi_type_pointer;
                 void* symbolTable = (void*)&getSymbolTable();
                 values[0] = &symbolTable;
                 void* recordTable = (void*)&getRecordTable();
                 values[1] = &recordTable;
                 for (size_t i = 0; i < arity; i++) {
                     intVal[i] = execute(shadow.getChild(i), ctxt);
                     args[i + 2] = &FFI_RamSigned;
                     values[i + 2] = &intVal[i];
                 }
                 // Set codomain.
                 auto codomain = &FFI_RamSigned;
                 // Call the external function.
                 const auto prepStatus = ffi_prep_cif(&cif, FFI_DEFAULT_ABI, arity + 2, codomain, args);
                 if (prepStatus != FFI_OK) {
                     fatal("Failed to prepare CIF for user-defined operator `%s`; error code = %d", name,
                             prepStatus);
                 }
                 ffi_call(&cif, fn, &rc, values);
                 return static_cast<RamDomain>(rc);
             } else {
                 // get name and type
                 const std::vector<TypeAttribute>& type = cur.getArgsTypes();
                 // prepare dynamic call environment
                 ffi_cif cif;
                 ffi_type* args[arity];
                 void* values[arity];
                 RamDomain intVal[arity];
                 RamUnsigned uintVal[arity];
                 RamFloat floatVal[arity];
                 const char* strVal[arity];
                 ffi_arg rc;
                 /* Initialize arguments for ffi-call */
                 for (size_t i = 0; i < arity; i++) {
                     RamDomain arg = execute(shadow.getChild(i), ctxt);
                     switch (type[i]) {
                         case TypeAttribute::Symbol:
                             args[i] = &FFI_Symbol;
                             strVal[i] = getSymbolTable().resolve(arg).c_str();
                             values[i] = &strVal[i];
                             break;
                         case TypeAttribute::Signed:
                             args[i] = &FFI_RamSigned;
                             intVal[i] = arg;
                             values[i] = &intVal[i];
                             break;
                         case TypeAttribute::Unsigned:
                             args[i] = &FFI_RamUnsigned;
                             uintVal[i] = ramBitCast<RamUnsigned>(arg);
                             values[i] = &uintVal[i];
                             break;
                         case TypeAttribute::Float:
                             args[i] = &FFI_RamFloat;
                             floatVal[i] = ramBitCast<RamFloat>(arg);
                             values[i] = &floatVal[i];
                             break;
                         case TypeAttribute::ADT: fatal("ADT support is not implemented");
                         case TypeAttribute::Record: fatal("Record support is not implemented");
                     }
                 }
                 // Get codomain.
                 auto codomain = &FFI_RamSigned;
                 switch (cur.getReturnType()) {
                     // initialize for string value.
                     case TypeAttribute::Symbol: codomain = &FFI_Symbol; break;
                     case TypeAttribute::Signed: codomain = &FFI_RamSigned; break;
                     case TypeAttribute::Unsigned: codomain = &FFI_RamUnsigned; break;
                     case TypeAttribute::Float: codomain = &FFI_RamFloat; break;
                     case TypeAttribute::ADT: fatal("Not implemented");
                     case TypeAttribute::Record: fatal("Not implemented");
                 }
                 // Call the external function.
                 const auto prepStatus = ffi_prep_cif(&cif, FFI_DEFAULT_ABI, arity, codomain, args);
                 if (prepStatus != FFI_OK) {
                     fatal("Failed to prepare CIF for user-defined operator `%s`; error code = %d", name,
                             prepStatus);
                 }
                 ffi_call(&cif, fn, &rc, values);
                 switch (cur.getReturnType()) {
                     case TypeAttribute::Signed: return static_cast<RamDomain>(rc);
                     case TypeAttribute::Symbol:
                         return getSymbolTable().lookup(reinterpret_cast<const char*>(rc));
                     case TypeAttribute::Unsigned: return ramBitCast(static_cast<RamUnsigned>(rc));
                     case TypeAttribute::Float: return ramBitCast(static_cast<RamFloat>(rc));
                     case TypeAttribute::ADT: fatal("Not implemented");
                     case TypeAttribute::Record: fatal("Not implemented");
                 }
                 fatal("Unsupported user defined operator");
             }
         ESAC(UserDefinedOperator)
         CASE(PackRecord)
             auto values = cur.getArguments();
             size_t arity = values.size();
             RamDomain data[arity];
             for (size_t i = 0; i < arity; ++i) {
                 data[i] = execute(shadow.getChild(i), ctxt);
             }
             return getRecordTable().pack(data, arity);
         ESAC(PackRecord)
         CASE(SubroutineArgument)
             return ctxt.getArgument(cur.getArgument());
         ESAC(SubroutineArgument)
         CASE(True)
             return true;
         ESAC(True)
         CASE(False)
             return false;
         ESAC(False)
         CASE(Conjunction)
             return execute(shadow.getLhs(), ctxt) && execute(shadow.getRhs(), ctxt);
         ESAC(Conjunction)
         CASE(Negation)
             return !execute(shadow.getChild(), ctxt);
         ESAC(Negation)
 #define EMPTINESS_CHECK(Structure, Arity, ...)                         \
     CASE(EmptinessCheck, Structure, Arity)                             \
         const auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return rel.empty();                                            \
     ESAC(EmptinessCheck)
         FOR_EACH(EMPTINESS_CHECK)
 #undef EMPTINESS_CHECK
 #define RELATION_SIZE(Structure, Arity, ...)                           \
     CASE(RelationSize, Structure, Arity)                               \
         const auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return rel.size();                                             \
     ESAC(RelationSize)
         FOR_EACH(RELATION_SIZE)
 #undef RELATION_SIZE
 #define EXISTENCE_CHECK(Structure, Arity, ...)            \
     CASE(ExistenceCheck, Structure, Arity)                \
         return evalExistenceCheck<RelType>(shadow, ctxt); \
     ESAC(ExistenceCheck)
         FOR_EACH(EXISTENCE_CHECK)
 #undef EXISTENCE_CHECK
 #define PROVENANCE_EXISTENCE_CHECK(Structure, Arity, ...)           \
     CASE(ProvenanceExistenceCheck, Structure, Arity)                \
         return evalProvenanceExistenceCheck<RelType>(shadow, ctxt); \
     ESAC(ProvenanceExistenceCheck)
         FOR_EACH_PROVENANCE(PROVENANCE_EXISTENCE_CHECK)
 #undef PROVENANCE_EXISTENCE_CHECK
         CASE(Constraint)
         // clang-format off
 #define COMPARE_NUMERIC(ty, op) return EVAL_LEFT(ty) op EVAL_RIGHT(ty)
 #define COMPARE_STRING(op)                                        \
     return (getSymbolTable().resolve(EVAL_LEFT(RamDomain)) op \
             getSymbolTable().resolve(EVAL_RIGHT(RamDomain)))
 #define COMPARE_EQ_NE(opCode, op)                                         \
     case BinaryConstraintOp::   opCode: COMPARE_NUMERIC(RamDomain  , op); \
     case BinaryConstraintOp::F##opCode: COMPARE_NUMERIC(RamFloat   , op);
 #define COMPARE(opCode, op)                                               \
     case BinaryConstraintOp::   opCode: COMPARE_NUMERIC(RamSigned  , op); \
     case BinaryConstraintOp::U##opCode: COMPARE_NUMERIC(RamUnsigned, op); \
     case BinaryConstraintOp::F##opCode: COMPARE_NUMERIC(RamFloat   , op); \
     case BinaryConstraintOp::S##opCode: COMPARE_STRING(op);
             // clang-format on
             switch (cur.getOperator()) {
                 COMPARE_EQ_NE(EQ, ==)
                 COMPARE_EQ_NE(NE, !=)
                 COMPARE(LT, <)
                 COMPARE(LE, <=)
                 COMPARE(GT, >)
                 COMPARE(GE, >=)
                 case BinaryConstraintOp::MATCH: {
                     RamDomain left = execute(shadow.getLhs(), ctxt);
                     RamDomain right = execute(shadow.getRhs(), ctxt);
                     const std::string& pattern = getSymbolTable().resolve(left);
                     const std::string& text = getSymbolTable().resolve(right);
                     bool result = false;
                     try {
                         result = std::regex_match(text, std::regex(pattern));
                     } catch (...) {
                         std::cerr << "warning: wrong pattern provided for match(\"" << pattern << "\",\""
                                   << text << "\").\n";
                     }
                     return result;
                 }
                 case BinaryConstraintOp::NOT_MATCH: {
                     RamDomain left = execute(shadow.getLhs(), ctxt);
                     RamDomain right = execute(shadow.getRhs(), ctxt);
                     const std::string& pattern = getSymbolTable().resolve(left);
                     const std::string& text = getSymbolTable().resolve(right);
                     bool result = false;
                     try {
                         result = !std::regex_match(text, std::regex(pattern));
                     } catch (...) {
                         std::cerr << "warning: wrong pattern provided for !match(\"" << pattern << "\",\""
                                   << text << "\").\n";
                     }
                     return result;
                 }
                 case BinaryConstraintOp::CONTAINS: {
                     RamDomain left = execute(shadow.getLhs(), ctxt);
                     RamDomain right = execute(shadow.getRhs(), ctxt);
                     const std::string& pattern = getSymbolTable().resolve(left);
                     const std::string& text = getSymbolTable().resolve(right);
                     return text.find(pattern) != std::string::npos;
                 }
                 case BinaryConstraintOp::NOT_CONTAINS: {
                     RamDomain left = execute(shadow.getLhs(), ctxt);
                     RamDomain right = execute(shadow.getRhs(), ctxt);
                     const std::string& pattern = getSymbolTable().resolve(left);
                     const std::string& text = getSymbolTable().resolve(right);
                     return text.find(pattern) == std::string::npos;
                 }
             }
             { UNREACHABLE_BAD_CASE_ANALYSIS }
 #undef COMPARE_NUMERIC
 #undef COMPARE_STRING
 #undef COMPARE
 #undef COMPARE_EQ_NE
         ESAC(Constraint)
         CASE(TupleOperation)
             bool result = execute(shadow.getChild(), ctxt);
             if (profileEnabled && !cur.getProfileText().empty()) {
                 auto& currentFrequencies = frequencies[cur.getProfileText()];
                 while (currentFrequencies.size() <= getIterationNumber()) {
 #pragma omp critical(frequencies)
                     currentFrequencies.emplace_back(0);
                 }
                 frequencies[cur.getProfileText()][getIterationNumber()]++;
             }
             return result;
         ESAC(TupleOperation)
 #define SCAN(Structure, Arity, ...)                                    \
     CASE(Scan, Structure, Arity)                                       \
         const auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return evalScan(rel, cur, shadow, ctxt);                       \
     ESAC(Scan)
         FOR_EACH(SCAN)
 #undef SCAN
 #define PARALLEL_SCAN(Structure, Arity, ...)                           \
     CASE(ParallelScan, Structure, Arity)                               \
         const auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return evalParallelScan(rel, cur, shadow, ctxt);               \
     ESAC(ParallelScan)
         FOR_EACH(PARALLEL_SCAN)
 #undef PARALLEL_SCAN
 #define INDEX_SCAN(Structure, Arity, ...)                 \
     CASE(IndexScan, Structure, Arity)                     \
         return evalIndexScan<RelType>(cur, shadow, ctxt); \
     ESAC(IndexScan)
         FOR_EACH(INDEX_SCAN)
 #undef INDEX_SCAN
 #define PARALLEL_INDEX_SCAN(Structure, Arity, ...)                     \
     CASE(ParallelIndexScan, Structure, Arity)                          \
         const auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return evalParallelIndexScan(rel, cur, shadow, ctxt);          \
     ESAC(ParallelIndexScan)
         FOR_EACH(PARALLEL_INDEX_SCAN)
 #undef PARALLEL_INDEX_SCAN
 #define CHOICE(Structure, Arity, ...)                                  \
     CASE(Choice, Structure, Arity)                                     \
         const auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return evalChoice(rel, cur, shadow, ctxt);                     \
     ESAC(Choice)
         FOR_EACH(CHOICE)
 #undef CHOICE
 #define PARALLEL_CHOICE(Structure, Arity, ...)                         \
     CASE(ParallelChoice, Structure, Arity)                             \
         const auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return evalParallelChoice(rel, cur, shadow, ctxt);             \
     ESAC(ParallelChoice)
         FOR_EACH(PARALLEL_CHOICE)
 #undef PARALLEL_CHOICE
 #define INDEX_CHOICE(Structure, Arity, ...)                 \
     CASE(IndexChoice, Structure, Arity)                     \
         return evalIndexChoice<RelType>(cur, shadow, ctxt); \
     ESAC(IndexChoice)
         FOR_EACH(INDEX_CHOICE)
 #undef INDEX_CHOICE
 #define PARALLEL_INDEX_CHOICE(Structure, Arity, ...)                   \
     CASE(ParallelIndexChoice, Structure, Arity)                        \
         const auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return evalParallelIndexChoice(rel, cur, shadow, ctxt);        \
     ESAC(ParallelIndexChoice)
         FOR_EACH(PARALLEL_INDEX_CHOICE)
 #undef PARALLEL_INDEX_CHOICE
         CASE(UnpackRecord)
             RamDomain ref = execute(shadow.getExpr(), ctxt);
             // check for nil
             if (ref == 0) {
                 return true;
             }
             // update environment variable
             size_t arity = cur.getArity();
             const RamDomain* tuple = getRecordTable().unpack(ref, arity);
             // save reference to temporary value
             ctxt[cur.getTupleId()] = tuple;
             // run nested part - using base class visitor
             return execute(shadow.getNestedOperation(), ctxt);
         ESAC(UnpackRecord)
 #define PARALLEL_AGGREGATE(Structure, Arity, ...)                      \
     CASE(ParallelAggregate, Structure, Arity)                          \
         const auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return evalParallelAggregate(rel, cur, shadow, ctxt);          \
     ESAC(ParallelAggregate)
         FOR_EACH(PARALLEL_AGGREGATE)
 #undef PARALLEL_AGGREGATE
 #define AGGREGATE(Structure, Arity, ...)                                                                  \
     CASE(Aggregate, Structure, Arity)                                                                     \
         const auto& rel = *static_cast<RelType*>(node->getRelation());                                    \
         return evalAggregate(cur, *shadow.getCondition(), shadow.getExpr(), *shadow.getNestedOperation(), \
                 rel.scan(), ctxt);                                                                        \
     ESAC(Aggregate)
         FOR_EACH(AGGREGATE)
 #undef AGGREGATE
 #define PARALLEL_INDEX_AGGREGATE(Structure, Arity, ...)                \
     CASE(ParallelIndexAggregate, Structure, Arity)                     \
         return evalParallelIndexAggregate<RelType>(cur, shadow, ctxt); \
     ESAC(ParallelIndexAggregate)
         FOR_EACH(PARALLEL_INDEX_AGGREGATE)
 #undef PARALLEL_INDEX_AGGREGATE
 #define INDEX_AGGREGATE(Structure, Arity, ...)                 \
     CASE(IndexAggregate, Structure, Arity)                     \
         return evalIndexAggregate<RelType>(cur, shadow, ctxt); \
     ESAC(IndexAggregate)
         FOR_EACH(INDEX_AGGREGATE)
 #undef INDEX_AGGREGATE
         CASE(Break)
             // check condition
             if (execute(shadow.getCondition(), ctxt)) {
                 return false;
             }
             return execute(shadow.getNestedOperation(), ctxt);
         ESAC(Break)
         CASE(Filter)
             bool result = true;
             // check condition
             if (execute(shadow.getCondition(), ctxt)) {
                 // process nested
                 result = execute(shadow.getNestedOperation(), ctxt);
             }
             if (profileEnabled && !cur.getProfileText().empty()) {
                 auto& currentFrequencies = frequencies[cur.getProfileText()];
                 while (currentFrequencies.size() <= getIterationNumber()) {
                     currentFrequencies.emplace_back(0);
                 }
                 frequencies[cur.getProfileText()][getIterationNumber()]++;
             }
             return result;
         ESAC(Filter)
 #define PROJECT(Structure, Arity, ...)                           \
     CASE(Project, Structure, Arity)                              \
         auto& rel = *static_cast<RelType*>(node->getRelation()); \
         return evalProject(rel, shadow, ctxt);                   \
     ESAC(Project)
         FOR_EACH(PROJECT)
 #undef PROJECT
         CASE(SubroutineReturn)
             for (size_t i = 0; i < cur.getValues().size(); ++i) {
                 if (shadow.getChild(i) == nullptr) {
                     ctxt.addReturnValue(0);
                 } else {
                     ctxt.addReturnValue(execute(shadow.getChild(i), ctxt));
                 }
             }
             return true;
         ESAC(SubroutineReturn)
         CASE(Sequence)
             for (const auto& child : shadow.getChildren()) {
                 if (!execute(child.get(), ctxt)) {
                     return false;
                 }
             }
             return true;
         ESAC(Sequence)
         CASE(Parallel)
             for (const auto& child : shadow.getChildren()) {
                 if (!execute(child.get(), ctxt)) {
                     return false;
                 }
             }
             return true;
         ESAC(Parallel)
         CASE(Loop)
             resetIterationNumber();
             while (execute(shadow.getChild(), ctxt)) {
                 incIterationNumber();
             }
             resetIterationNumber();
             return true;
         ESAC(Loop)
         CASE(Exit)
             return !execute(shadow.getChild(), ctxt);
         ESAC(Exit)
         CASE(LogRelationTimer)
             Logger logger(cur.getMessage(), getIterationNumber(),
                     std::bind(&RelationWrapper::size, node->getRelation()));
             return execute(shadow.getChild(), ctxt);
         ESAC(LogRelationTimer)
         CASE(LogTimer)
             Logger logger(cur.getMessage(), getIterationNumber());
             return execute(shadow.getChild(), ctxt);
         ESAC(LogTimer)
         CASE(DebugInfo)
             SignalHandler::instance()->setMsg(cur.getMessage().c_str());
             return execute(shadow.getChild(), ctxt);
         ESAC(DebugInfo)
 #define CLEAR(Structure, Arity, ...)                             \
     CASE(Clear, Structure, Arity)                                \
         auto& rel = *static_cast<RelType*>(node->getRelation()); \
         rel.__purge();                                           \
         return true;                                             \
     ESAC(Clear)
         FOR_EACH(CLEAR)
 #undef CLEAR
         CASE(Call)
             execute(subroutine[shadow.getSubroutineId()].get(), ctxt);
             return true;
         ESAC(Call)
         CASE(LogSize)
             const auto& rel = *node->getRelation();
             ProfileEventSingleton::instance().makeQuantityEvent(
                     cur.getMessage(), rel.size(), getIterationNumber());
             return true;
         ESAC(LogSize)
         CASE(IO)
             const auto& directive = cur.getDirectives();
             const std::string& op = cur.get("operation");
             auto& rel = *node->getRelation();
             if (op == "input") {
                 try {
                     IOSystem::getInstance()
                             .getReader(directive, getSymbolTable(), getRecordTable())
                             ->readAll(rel);
                 } catch (std::exception& e) {
                     std::cerr << "Error loading data: " << e.what() << "\n";
                 }
                 return true;
             } else if (op == "output" || op == "printsize") {
                 try {
                     IOSystem::getInstance()
                             .getWriter(directive, getSymbolTable(), getRecordTable())
                             ->writeAll(rel);
                 } catch (std::exception& e) {
                     std::cerr << e.what();
                     exit(EXIT_FAILURE);
                 }
                 return true;
             } else {
                 assert("wrong i/o operation");
                 return true;
             }
         ESAC(IO)
         CASE(Query)
             ViewContext* viewContext = shadow.getViewContext();
             // Execute view-free operations in outer filter if any.
             auto& viewFreeOps = viewContext->getOuterFilterViewFreeOps();
             for (auto& op : viewFreeOps) {
                 if (!execute(op.get(), ctxt)) {
                     return true;
                 }
             }
             // Create Views for outer filter operation if any.
             auto& viewsForOuter = viewContext->getViewInfoForFilter();
             for (auto& info : viewsForOuter) {
                 ctxt.createView(*getRelationHandle(info[0]), info[1], info[2]);
             }
             // Execute outer filter operation.
             auto& viewOps = viewContext->getOuterFilterViewOps();
             for (auto& op : viewOps) {
                 if (!execute(op.get(), ctxt)) {
                     return true;
                 }
             }
             if (viewContext->isParallel) {
                 // If Parallel is true, holds views creation unitl parallel instructions.
             } else {
                 // Issue views for nested operation.
                 auto& viewsForNested = viewContext->getViewInfoForNested();
                 for (auto& info : viewsForNested) {
                     ctxt.createView(*getRelationHandle(info[0]), info[1], info[2]);
                 }
             }
             execute(shadow.getChild(), ctxt);
             return true;
         ESAC(Query)
         CASE(Extend)
             auto& src = *static_cast<EqrelRelation*>(getRelationHandle(shadow.getSourceId()).get());
             auto& trg = *static_cast<EqrelRelation*>(getRelationHandle(shadow.getTargetId()).get());
             src.extend(trg);
             trg.insert(src);
             return true;
         ESAC(Extend)
         CASE(Swap)
             swapRelation(shadow.getSourceId(), shadow.getTargetId());
             return true;
         ESAC(Swap)
     }
     UNREACHABLE_BAD_CASE_ANALYSIS
 #undef EVAL_CHILD
 #undef DEBUG
 }
 template <typename Rel>
 RamDomain Engine::evalExistenceCheck(const ExistenceCheck& shadow, Context& ctxt) {
     constexpr size_t Arity = Rel::Arity;
     size_t viewPos = shadow.getViewId();
References souffle::ADD, souffle::interpreter::Context::addReturnValue(), AGGREGATE, souffle::BAND, BINARY_OP_INTEGRAL, BINARY_OP_INTEGRAL_SHIFT, BINARY_OP_LOGICAL, BINARY_OP_NUMERIC, souffle::BOR, souffle::BSHIFT_L, souffle::BSHIFT_R, souffle::BSHIFT_R_UNSIGNED, souffle::BXOR, CASE, CHOICE, CLEAR, COMPARE, COMPARE_EQ_NE, CONV_FROM_STRING, CONV_TO_STRING, souffle::interpreter::Context::createView(), TCB_SPAN_NAMESPACE_NAME::detail::data(), souffle::tuple::data, souffle::DIV, e, EMPTINESS_CHECK, souffle::EQ, ESAC, EXISTENCE_CHECK, souffle::interpreter::EqrelRelation::extend(), souffle::F2I, souffle::F2S, souffle::F2U, souffle::fatal(), FFI_RamFloat, FFI_RamSigned, FFI_RamUnsigned, FFI_Symbol, FOR_EACH, FOR_EACH_PROVENANCE, souffle::GE, souffle::interpreter::Context::getArgument(), souffle::getInstance(), souffle::interpreter::ViewContext::getOuterFilterViewFreeOps(), souffle::interpreter::ViewContext::getOuterFilterViewOps(), souffle::interpreter::Node::getRelation(), souffle::interpreter::ViewContext::getViewInfoForFilter(), souffle::interpreter::ViewContext::getViewInfoForNested(), souffle::GT, i, souffle::I2F, souffle::I2S, souffle::I2U, INDEX_AGGREGATE, INDEX_CHOICE, INDEX_SCAN, souffle::interpreter::ViewContext::isParallel, souffle::LAND, souffle::LE, souffle::LOR, souffle::LT, souffle::LXOR, souffle::MAX, souffle::MIN, MINMAX_NUMERIC, MINMAX_OP_SYM, souffle::MOD, souffle::MUL, souffle::NE, PARALLEL_AGGREGATE, PARALLEL_CHOICE, PARALLEL_INDEX_AGGREGATE, PARALLEL_INDEX_CHOICE, PARALLEL_INDEX_SCAN, PARALLEL_SCAN, PROJECT, PROVENANCE_EXISTENCE_CHECK, souffle::ramBitCast(), rel(), RELATION_SIZE, RUN_RANGE, souffle::S2F, souffle::S2I, souffle::S2U, SCAN, TCB_SPAN_NAMESPACE_NAME::detail::size(), souffle::profile::ss, str, souffle::SUB, souffle::U2F, souffle::U2I, souffle::U2S, UNARY_OP, and UNREACHABLE_BAD_CASE_ANALYSIS.
executeMain()
void souffle::interpreter::Engine::executeMain ()
Execute the main program.
Definition at line 272 of file Engine.cpp.
{
         Context ctxt;
         execute(main.get(), ctxt);
     } else {
         ProfileEventSingleton::instance().setOutputFile(Global::config().get("profile"));
         // Prepare the frequency table for threaded use
         const ram::Program& program = tUnit.getProgram();
         ram::visitDepthFirst(program, [&](const ram::TupleOperation& node) {
             if (!node.getProfileText().empty()) {
                 frequencies.emplace(node.getProfileText(), std::deque<std::atomic<size_t>>());
                 frequencies[node.getProfileText()].emplace_back(0);
             }
         });
         // Enable profiling for execution of main
         ProfileEventSingleton::instance().startTimer();
         ProfileEventSingleton::instance().makeTimeEvent("@time;starttime");
         // Store configuration
         for (const auto& cur : Global::config().data()) {
             ProfileEventSingleton::instance().makeConfigRecord(cur.first, cur.second);
         }
         // Store count of relations
         size_t relationCount = 0;
         for (auto rel : tUnit.getProgram().getRelations()) {
             if (rel->getName()[0] != '@') {
                 ++relationCount;
                 reads[rel->getName()] = 0;
             }
         }
         ProfileEventSingleton::instance().makeConfigRecord("relationCount", std::to_string(relationCount));
         // Store count of rules
         size_t ruleCount = 0;
         ram::visitDepthFirst(program, [&](const ram::Query&) { ++ruleCount; });
         ProfileEventSingleton::instance().makeConfigRecord("ruleCount", std::to_string(ruleCount));
         Context ctxt;
         execute(main.get(), ctxt);
         ProfileEventSingleton::instance().stopTimer();
         for (auto const& cur : frequencies) {
             for (size_t i = 0; i < cur.second.size(); ++i) {
                 ProfileEventSingleton::instance().makeQuantityEvent(cur.first, cur.second[i], i);
             }
         }
         for (auto const& cur : reads) {
             ProfileEventSingleton::instance().makeQuantityEvent(
                     "@relation-reads;" + cur.first, cur.second, 0);
         }
     }
     SignalHandler::instance()->reset();
 }
 void Engine::generateIR() {
     const ram::Program& program = tUnit.getProgram();
     NodeGenerator generator(*this);
     if (subroutine.empty()) {
executeSubroutine()
void souffle::interpreter::Engine::executeSubroutine (const std::string & name, const std::vector< RamDomain > & args, std::vector< RamDomain > & ret)
Execute the subroutine program.
Definition at line 347 of file Engine.cpp.
{
 #define DEBUG(Kind) std::cout << "Running Node: " << #Kind << "\n";
 #define EVAL_CHILD(ty, idx) ramBitCast<ty>(execute(shadow.getChild(idx), ctxt))
 #define EVAL_LEFT(ty) ramBitCast<ty>(execute(shadow.getLhs(), ctxt))
generateIR()
void souffle::interpreter::Engine::generateIR () private
Generate intermediate representation from RAM.
Definition at line 334 of file Engine.cpp.
{
         main = generator.generateTree(program.getMain());
     }
 }
 void Engine::executeSubroutine(
         const std::string& name, const std::vector<RamDomain>& args, std::vector<RamDomain>& ret) {
     Context ctxt;
     ctxt.setReturnValues(ret);
getIterationNumber()
size_t souffle::interpreter::Engine::getIterationNumber () const private
Return current iteration number for loop operation.
Definition at line 262 of file Engine.cpp.
{
     iteration = 0;
getMethodHandle()
void * souffle::interpreter::Engine::getMethodHandle (const std::string & method) private
Return method handler.
Definition at line 183 of file Engine.cpp.
{
     return relations;
 }
getRecordTable()
RecordTable & souffle::interpreter::Engine::getRecordTable () private
Return the record table.
Definition at line 175 of file Engine.cpp.
getRelationHandle()
Engine::RelationHandle & souffle::interpreter::Engine::getRelationHandle (const size_t idx) private
Return a reference to the relation on the given index.
Definition at line 157 of file Engine.cpp.
getRelationMap()
VecOwn< Engine::RelationHandle > & souffle::interpreter::Engine::getRelationMap () private
Return the relation map.
Definition at line 194 of file Engine.cpp.
{
         relations.resize(idx + 1);
     }
References relations.
getSymbolTable()
SymbolTable & souffle::interpreter::Engine::getSymbolTable () private
Return the string symbol table.
Definition at line 171 of file Engine.cpp.
getTranslationUnit()
ram::TranslationUnit & souffle::interpreter::Engine::getTranslationUnit () private
Return the ram::TranslationUnit.
Definition at line 179 of file Engine.cpp.
                          : loadDLL()) {
         auto* methodHandle = dlsym(libHandle, method.c_str());
incCounter()
int souffle::interpreter::Engine::incCounter () private
Increment the counter.
Definition at line 167 of file Engine.cpp.
incIterationNumber()
void souffle::interpreter::Engine::incIterationNumber () private
Increase iteration number by one.
Definition at line 265 of file Engine.cpp.
{
loadDLL()
const std::vector< void * > & souffle::interpreter::Engine::loadDLL () private
Load DLL.
Definition at line 217 of file Engine.cpp.
{
         Global::config().set("libraries", "functors");
     }
     if (!Global::config().has("library-dir")) {
         Global::config().set("library-dir", ".");
     }
     for (const std::string& library : splitString(Global::config().get("libraries"), ' ')) {
         // The library may be blank
         if (library.empty()) {
             continue;
         }
         auto paths = splitString(Global::config().get("library-dir"), ' ');
         // Set up our paths to have a library appended
         for (std::string& path : paths) {
             if (path.back() != '/') {
                 path += '/';
             }
         }
         if (library.find('/') != std::string::npos) {
             paths.clear();
         }
         paths.push_back("");
         void* tmp = nullptr;
         for (const std::string& path : paths) {
             std::string fullpath = path + "lib" + library + dynamicLibSuffix;
             tmp = dlopen(fullpath.c_str(), RTLD_LAZY);
             if (tmp != nullptr) {
                 dll.push_back(tmp);
                 break;
             }
         }
     }
     return dll;
 }
 size_t Engine::getIterationNumber() const {
     return iteration;
 }
 void Engine::incIterationNumber() {
resetIterationNumber()
void souffle::interpreter::Engine::resetIterationNumber () private
Reset iteration number.
Definition at line 268 of file Engine.cpp.
{
         SignalHandler::instance()->enableLogging();
swapRelation()
void souffle::interpreter::Engine::swapRelation (const size_t ramRel1, const size_t ramRel2) private
Swap the content of two relations.
Definition at line 161 of file Engine.cpp.
{
     return counter++;
 }
Field Documentation
counter
std::atomic<RamDomain> souffle::interpreter::Engine::counter {0} private
Profile counter.
Definition at line 168 of file Engine.h.
dll
std::vector<void*> souffle::interpreter::Engine::dll private
DLL.
Definition at line 176 of file Engine.h.
frequencies
std::map<std::string, std::deque<std::atomic<size_t> > > souffle::interpreter::Engine::frequencies private
Profile for rule frequencies.
Definition at line 172 of file Engine.h.
isa
ram::analysis::IndexAnalysis* souffle::interpreter::Engine::isa private
IndexAnalysis.
Definition at line 180 of file Engine.h.
isProvenance
const bool souffle::interpreter::Engine::isProvenance private
If running a provenance program.
Definition at line 160 of file Engine.h.
iteration
size_t souffle::interpreter::Engine::iteration = 0 private
Loop iteration counter.
Definition at line 170 of file Engine.h.
main
Own<Node> souffle::interpreter::Engine::main private
main program
Definition at line 164 of file Engine.h.
NodeGenerator
friend souffle::interpreter::Engine::NodeGenerator private
Definition at line 59 of file Engine.h.
numOfThreads
size_t souffle::interpreter::Engine::numOfThreads private
Number of threads enabled for this program.
Definition at line 166 of file Engine.h.
profileEnabled
const bool souffle::interpreter::Engine::profileEnabled private
If profile is enable in this program.
Definition at line 158 of file Engine.h.
ProgInterface
friend souffle::interpreter::Engine::ProgInterface private
Definition at line 58 of file Engine.h.
reads
std::map<std::string, std::atomic<size_t> > souffle::interpreter::Engine::reads private
Profile for relation reads.
Definition at line 174 of file Engine.h.
recordTable
RecordTable souffle::interpreter::Engine::recordTable private
Record Table.
Definition at line 182 of file Engine.h.
relations
VecOwn<RelationHandle> souffle::interpreter::Engine::relations private
Symbol table for relations.
Definition at line 184 of file Engine.h.
subroutine
VecOwn<Node> souffle::interpreter::Engine::subroutine private
subroutines
Definition at line 162 of file Engine.h.
tUnit
ram::TranslationUnit& souffle::interpreter::Engine::tUnit private
Program.
Definition at line 178 of file Engine.h.
The documentation for this class was generated from the following files:
interpreter/Engine.h
interpreter/Engine.cpp