souffle: souffle::interpreter::BinRelOperation Class Reference
souffle::interpreter::BinRelOperation Class Reference
operation that involves with two relations should inherit from this class. E.g. Swap, Extend
#include <Node.h>
Public Member Functions
BinRelOperation (size_t src, size_t target)
size_t getSourceId () const
size_t getTargetId () const
Protected Attributes
const size_t src
const size_t target
Detailed Description
operation that involves with two relations should inherit from this class. E.g. Swap, Extend
Definition at line 366 of file Node.h.
Constructor & Destructor Documentation
BinRelOperation()
souffle::interpreter::BinRelOperation::BinRelOperation (size_t src, size_t target) inline
Definition at line 368 of file Node.h.
 {
Referenced by souffle::interpreter::ViewOperation::getViewId().
Member Function Documentation
getSourceId()
size_t souffle::interpreter::BinRelOperation::getSourceId () const inline
Definition at line 370 of file Node.h.
                       {
Referenced by souffle::interpreter::ViewOperation::getViewId().
getTargetId()
size_t souffle::interpreter::BinRelOperation::getTargetId () const inline
Definition at line 374 of file Node.h.
                       {
 public:
     NestedOperation(Own<Node> nested) : nested(std::move(nested)) {}
References souffle::interpreter::NestedOperation::getNestedOperation(), souffle::interpreter::NestedOperation::nested, and souffle::interpreter::NestedOperation::NestedOperation().
Field Documentation
src
const size_t souffle::interpreter::BinRelOperation::src protected
Definition at line 379 of file Node.h.
Referenced by souffle::interpreter::ViewOperation::getViewId().
target
const size_t souffle::interpreter::BinRelOperation::target protected
Definition at line 380 of file Node.h.
Referenced by souffle::interpreter::ViewOperation::getViewId().
The documentation for this class was generated from the following file:
interpreter/Node.h