souffle: souffle::ram::analysis::RelationAnalysis Class Reference
souffle::ram::analysis::RelationAnalysis Class Reference
A RAM Analysis for finding relations by name.
#include <Relation.h>
Public Member Functions
const ram::Relation & lookup (const std::string &name) const
RelationAnalysis (const char *id)
void run (const TranslationUnit &) override
Run analysis for a RAM translation unit.
Public Member Functions inherited from souffle::ram::analysis::Analysis
Analysis (const char *id)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
Print the analysis result in HTML format.
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "relation-analysis"
Protected Attributes
std::map< std::string, const ram::Relation * > relationMap
Protected Attributes inherited from souffle::ram::analysis::Analysis
std::string identifier
name of analysis instance
Detailed Description
A RAM Analysis for finding relations by name.
Definition at line 36 of file Relation.h.
Constructor & Destructor Documentation
RelationAnalysis()
souffle::ram::analysis::RelationAnalysis::RelationAnalysis (const char * id) inline
Definition at line 38 of file Relation.h.
 :
     std::map<std::string, const ram::Relation*> relationMap;
Member Function Documentation
lookup()
const ram::Relation & souffle::ram::analysis::RelationAnalysis::lookup (const std::string & name) const
Definition at line 33 of file Relation.cpp.
{
     visitDepthFirst(translationUnit.getProgram(),
             [&](const Relation& relation) { relationMap[relation.getName()] = &relation; });
 }
References souffle::ram::TranslationUnit::getProgram(), relation, and souffle::ram::visitDepthFirst().
Referenced by souffle::ram::transform::MakeIndexTransformer::makeIndex(), and souffle::ram::transform::ParallelTransformer::parallelizeOperations().
run()
void souffle::ram::analysis::RelationAnalysis::run (const TranslationUnit & translationUnit) override virtual
Run analysis for a RAM translation unit.
Implements souffle::ram::analysis::Analysis.
Definition at line 39 of file Relation.cpp.
Field Documentation
name
constexpr const char* souffle::ram::analysis::RelationAnalysis::name = "relation-analysis" static constexpr
Definition at line 40 of file Relation.h.
relationMap
std::map<std::string, const ram::Relation*> souffle::ram::analysis::RelationAnalysis::relationMap protected
Definition at line 47 of file Relation.h.
The documentation for this class was generated from the following files:
ram/analysis/Relation.h
ram/analysis/Relation.cpp