souffle: souffle::interpreter::ExistenceCheck Class Reference
souffle::interpreter::ExistenceCheck Class Reference
#include <Node.h>
Public Member Functions
ExistenceCheck (enum NodeType ty, const ram::Node *sdw, bool totalSearch, size_t viewId, SuperInstruction superInst, bool tempRelation, std::string relationName)
const std::string & getRelationName () const
bool isTemp () const
bool isTotalSearch () const
Public Member Functions inherited from souffle::interpreter::Node
RelationWrapper * getRelation () const
get relation from handle
const ram::Node * getShadow () const
get shadow node, i.e., RAM node
enum NodeType getType () const
get node type
Node (enum NodeType ty, const ram::Node *sdw, RelationHandle *relHandle=nullptr)
virtual ~Node ()=default
Public Member Functions inherited from souffle::interpreter::SuperOperation
const SuperInstruction & getSuperInst () const
SuperOperation (SuperInstruction superInst)
Public Member Functions inherited from souffle::interpreter::ViewOperation
size_t getViewId () const
ViewOperation (size_t id)
Private Attributes
const std::string relationName
const bool tempRelation
const bool totalSearch
Additional Inherited Members
Public Types inherited from souffle::interpreter::Node
using RelationHandle = Own< RelationWrapper >
Protected Attributes inherited from souffle::interpreter::Node
RelationHandle *const relHandle
const ram::Node * shadow
enum NodeType type
Protected Attributes inherited from souffle::interpreter::SuperOperation
const SuperInstruction superInst
Protected Attributes inherited from souffle::interpreter::ViewOperation
size_t viewId
Detailed Description
Definition at line 530 of file Node.h.
Constructor & Destructor Documentation
ExistenceCheck()
souffle::interpreter::ExistenceCheck::ExistenceCheck (enum NodeType ty, const ram::Node * sdw, bool totalSearch, size_t viewId, SuperInstruction superInst, bool tempRelation, std::string relationName) inline
Definition at line 532 of file Node.h.
{
         return relationName;
     }
References relationName.
Member Function Documentation
getRelationName()
const std::string& souffle::interpreter::ExistenceCheck::getRelationName () const inline
Definition at line 545 of file Node.h.
                                : public UnaryNode, public SuperOperation, public ViewOperation {
 public:
     ProvenanceExistenceCheck(enum NodeType ty, const ram::Node* sdw, Own<Node> child, size_t viewId,
References souffle::interpreter::UnaryNode::child, souffle::interpreter::ProvenanceExistenceCheck::ProvenanceExistenceCheck(), souffle::interpreter::SuperOperation::superInst, souffle::interpreter::SuperOperation::SuperOperation(), souffle::interpreter::UnaryNode::UnaryNode(), and souffle::interpreter::ViewOperation::viewId.
isTemp()
bool souffle::interpreter::ExistenceCheck::isTemp () const inline
Definition at line 541 of file Node.h.
                                : public UnaryNode, public SuperOperation, public ViewOperation {
isTotalSearch()
bool souffle::interpreter::ExistenceCheck::isTotalSearch () const inline
Definition at line 537 of file Node.h.
                                : public UnaryNode, public SuperOperation, public ViewOperation {
Field Documentation
relationName
const std::string souffle::interpreter::ExistenceCheck::relationName private
Definition at line 552 of file Node.h.
Referenced by ExistenceCheck().
tempRelation
const bool souffle::interpreter::ExistenceCheck::tempRelation private
Definition at line 551 of file Node.h.
totalSearch
const bool souffle::interpreter::ExistenceCheck::totalSearch private
Definition at line 550 of file Node.h.
The documentation for this class was generated from the following file:
interpreter/Node.h