souffle: souffle::interpreter::ConditionalOperation Class Reference
souffle::interpreter::ConditionalOperation Class Reference
Encode a conditional operation for the interpreter node. E.g. Exit, Filter.
#include <Node.h>
Public Member Functions
ConditionalOperation (Own< Node > cond)
const Node * getCondition () const
Protected Attributes
Own< Node > cond
Detailed Description
Encode a conditional operation for the interpreter node. E.g. Exit, Filter.
Definition at line 403 of file Node.h.
Constructor & Destructor Documentation
ConditionalOperation()
souffle::interpreter::ConditionalOperation::ConditionalOperation (Own< Node > cond) inline
Definition at line 405 of file Node.h.
 : public Node {
References souffle::interpreter::Node::Node().
Referenced by souffle::interpreter::IndexAggregate::IndexAggregate(), and souffle::interpreter::IndexScan::IndexScan().
Member Function Documentation
getCondition()
const Node* souffle::interpreter::ConditionalOperation::getCondition () const inline
Definition at line 407 of file Node.h.
                    : public Node {
Field Documentation
cond
Own<Node> souffle::interpreter::ConditionalOperation::cond protected
Definition at line 409 of file Node.h.
Referenced by souffle::interpreter::Choice::Choice(), souffle::interpreter::IndexAggregate::IndexAggregate(), and souffle::interpreter::IndexScan::IndexScan().
The documentation for this class was generated from the following file:
interpreter/Node.h