souffle: souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator Class Reference
souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator Class Reference
The iterator type to be utilized for scanning through btree instances.
#include <BTree.h>
Public Types
using difference_type = ptrdiff_t
using iterator_category = std::forward_iterator_tag
using pointer = value_type *
using reference = value_type &
using value_type = Key
Public Member Functions
iterator ()
iterator (const iterator &other)
iterator (node const *cur, field_index_type pos)
bool operator!= (const iterator &other) const
const Key & operator* () const
iterator & operator++ ()
iterator & operator= (const iterator &other)
bool operator== (const iterator &other) const
void print (std::ostream &out=std::cout) const
Private Attributes
node const * cur
field_index_type pos = 0
Detailed Description
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>>
class souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator
The iterator type to be utilized for scanning through btree instances.
Definition at line 1114 of file BTree.h.
Member Typedef Documentation
difference_type
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::difference_type = ptrdiff_t
Definition at line 1124 of file BTree.h.
iterator_category
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::iterator_category = std::forward_iterator_tag
Definition at line 1122 of file BTree.h.
pointer
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::pointer = value_type*
Definition at line 1125 of file BTree.h.
reference
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::reference = value_type&
Definition at line 1126 of file BTree.h.
value_type
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::value_type = Key
Definition at line 1123 of file BTree.h.
Constructor & Destructor Documentation
iterator() [1/3]
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::iterator () inline
Definition at line 1129 of file BTree.h.
 {
iterator() [2/3]
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::iterator (node const * cur, field_index_type pos) inline
Definition at line 1132 of file BTree.h.
 {
iterator() [3/3]
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::iterator (const iterator & other) inline
Definition at line 1135 of file BTree.h.
 {
Member Function Documentation
operator!=()
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator!= (const iterator & other) const inline
Definition at line 1150 of file BTree.h.
{
operator*()
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> const Key& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator* () const inline
Definition at line 1155 of file BTree.h.
{
                 cur = cur->getChildren()[pos + 1];
                 while (!cur->isLeaf()) {
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::getChildren(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::base::isLeaf().
operator++()
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator++ () inline
Definition at line 1160 of file BTree.h.
{
                     return *this;
                 }
             }
             // B) we are at the right-most element of a leaf => go to next inner node
             assert(cur->isLeaf());
             assert(pos == cur->getNumElements());
             while (cur != nullptr && pos == cur->getNumElements()) {
                 pos = cur->getPositionInParent();
                 cur = cur->getParent();
             }
             return *this;
         }
         // prints a textual representation of this iterator to the given stream (mainly for debugging)
         void print(std::ostream& out = std::cout) const {
             out << cur << "[" << (int)pos << "]";
         }
     };
     /**
      * A collection of operation hints speeding up some of the involved operations
      * by exploiting temporal locality.
      */
     template <unsigned size = 1>
     struct btree_operation_hints {
         using node_cache = LRUCache<node*, size>;
operator=()
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator= (const iterator & other) inline
Definition at line 1138 of file BTree.h.
{
             return cur->keys[pos];
operator==()
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator== (const iterator & other) const inline
Definition at line 1145 of file BTree.h.
{
             // the quick mode -- if in a leaf and there are elements left
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::base::getNumElements(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::base::isLeaf().
print()
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::print (std::ostream & out = std::cout) const inline
Definition at line 1194 of file BTree.h.
                      {
Field Documentation
cur
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> node const* souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::cur private
Definition at line 1116 of file BTree.h.
pos
template<typename Key , typename Comparator , typename Allocator , unsigned blockSize, typename SearchStrategy , bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> field_index_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::pos = 0 private
Definition at line 1119 of file BTree.h.
The documentation for this class was generated from the following file:
include/souffle/datastructure/BTree.h