souffle: souffle::interpreter::Node Class Reference
souffle::interpreter::Node Class Reference
This is a shadow node for a ram::Node that is enriched for with local information so that the interpreter is executing quickly.
#include <Node.h>
Public Types
using RelationHandle = Own< RelationWrapper >
Public Member Functions
RelationWrapper * getRelation () const
get relation from handle
const ram::Node * getShadow () const
get shadow node, i.e., RAM node
enum NodeType getType () const
get node type
Node (enum NodeType ty, const ram::Node *sdw, RelationHandle *relHandle=nullptr)
virtual ~Node ()=default
Protected Attributes
RelationHandle *const relHandle
const ram::Node * shadow
enum NodeType type
Detailed Description
This is a shadow node for a ram::Node that is enriched for with local information so that the interpreter is executing quickly.
Definition at line 178 of file Node.h.
Member Typedef Documentation
RelationHandle
using souffle::interpreter::Node::RelationHandle = Own<RelationWrapper>
Definition at line 180 of file Node.h.
Constructor & Destructor Documentation
Node()
souffle::interpreter::Node::Node (enum NodeType ty, const ram::Node * sdw, RelationHandle * relHandle = nullptr) inline
Definition at line 182 of file Node.h.
{
References relHandle.
Referenced by souffle::interpreter::Call::Call(), souffle::interpreter::ConditionalOperation::ConditionalOperation(), souffle::interpreter::IndexAggregate::IndexAggregate(), souffle::interpreter::IndexChoice::IndexChoice(), and souffle::interpreter::IndexScan::IndexScan().
~Node()
virtual souffle::interpreter::Node::~Node () virtual default
Member Function Documentation
getRelation()
RelationWrapper* souffle::interpreter::Node::getRelation () const inline
get relation from handle
Definition at line 197 of file Node.h.
                    : public Node {
     using NodePtrVec = VecOwn<Node>;
Referenced by souffle::interpreter::Engine::execute().
getShadow()
const ram::Node* souffle::interpreter::Node::getShadow () const inline
get shadow node, i.e., RAM node
Definition at line 192 of file Node.h.
                    : public Node {
getType()
enum NodeType souffle::interpreter::Node::getType () const inline
get node type
Definition at line 187 of file Node.h.
          :
     enum NodeType type;
Field Documentation
relHandle
RelationHandle* const souffle::interpreter::Node::relHandle protected
Definition at line 205 of file Node.h.
Referenced by souffle::interpreter::Choice::Choice(), souffle::interpreter::IndexScan::IndexScan(), Node(), and souffle::interpreter::Scan::Scan().
shadow
const ram::Node* souffle::interpreter::Node::shadow protected
Definition at line 204 of file Node.h.
type
enum NodeType souffle::interpreter::Node::type protected
Definition at line 203 of file Node.h.
The documentation for this class was generated from the following file:
interpreter/Node.h