souffle: souffle::interpreter::ViewOperation Class Reference
souffle::interpreter::ViewOperation Class Reference
operation that utilizes the index view from underlying relation should inherit from this class.
#include <Node.h>
Public Member Functions
size_t getViewId () const
ViewOperation (size_t id)
Protected Attributes
size_t viewId
Detailed Description
operation that utilizes the index view from underlying relation should inherit from this class.
Definition at line 349 of file Node.h.
Constructor & Destructor Documentation
ViewOperation()
souffle::interpreter::ViewOperation::ViewOperation (size_t id) inline
Definition at line 351 of file Node.h.
 {
Referenced by souffle::interpreter::Choice::Choice(), souffle::interpreter::Scan::Scan(), and souffle::interpreter::AbstractParallel::setViewContext().
Member Function Documentation
getViewId()
size_t souffle::interpreter::ViewOperation::getViewId () const inline
Definition at line 353 of file Node.h.
                       {
 public:
     BinRelOperation(size_t src, size_t target) : src(src), target(target) {}
References souffle::interpreter::BinRelOperation::BinRelOperation(), souffle::interpreter::BinRelOperation::getSourceId(), souffle::interpreter::BinRelOperation::src, and souffle::interpreter::BinRelOperation::target.
Referenced by souffle::interpreter::AbstractParallel::setViewContext().
Field Documentation
viewId
size_t souffle::interpreter::ViewOperation::viewId protected
Definition at line 358 of file Node.h.
Referenced by souffle::interpreter::Choice::Choice(), souffle::interpreter::ExistenceCheck::getRelationName(), souffle::interpreter::Scan::Scan(), and souffle::interpreter::AbstractParallel::setViewContext().
The documentation for this class was generated from the following file:
interpreter/Node.h