souffle: souffle::interpreter::AbstractParallel Class Reference
souffle::interpreter::AbstractParallel Class Reference
node that utilizes parallel execution should inherit from this class. Enable node with its own view context for parallel execution.
#include <Node.h>
Public Member Functions
ViewContext * getViewContext () const
get view context for operations
void setViewContext (const std::shared_ptr< ViewContext > &v)
set view context
Protected Attributes
std::shared_ptr< ViewContext > viewContext = nullptr
Detailed Description
node that utilizes parallel execution should inherit from this class. Enable node with its own view context for parallel execution.
Definition at line 328 of file Node.h.
Member Function Documentation
getViewContext()
ViewContext* souffle::interpreter::AbstractParallel::getViewContext () const inline
get view context for operations
Definition at line 331 of file Node.h.
                     {
Referenced by souffle::interpreter::SuperOperation::getSuperInst().
setViewContext()
void souffle::interpreter::AbstractParallel::setViewContext (const std::shared_ptr< ViewContext > & v) inline
set view context
Definition at line 336 of file Node.h.
                     {
 public:
     ViewOperation(size_t id) : viewId(id) {}
References souffle::interpreter::ViewOperation::getViewId(), souffle::interpreter::ViewOperation::viewId, and souffle::interpreter::ViewOperation::ViewOperation().
Field Documentation
viewContext
std::shared_ptr<ViewContext> souffle::interpreter::AbstractParallel::viewContext = nullptr protected
Definition at line 341 of file Node.h.
Referenced by souffle::interpreter::SuperOperation::getSuperInst().
The documentation for this class was generated from the following file:
interpreter/Node.h