souffle: souffle::ast::transform::SemanticChecker Class Reference
souffle::ast::transform::SemanticChecker Class Reference
#include <SemanticChecker.h>
Public Member Functions
SemanticChecker * clone () const override
std::string getName () const override
~SemanticChecker () override=default
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Detailed Description
Definition at line 31 of file SemanticChecker.h.
Constructor & Destructor Documentation
~SemanticChecker()
souffle::ast::transform::SemanticChecker::~SemanticChecker () override default
Member Function Documentation
clone()
SemanticChecker* souffle::ast::transform::SemanticChecker::clone () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 45 of file SemanticChecker.h.
getName()
std::string souffle::ast::transform::SemanticChecker::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 41 of file SemanticChecker.h.
transform()
bool souffle::ast::transform::SemanticChecker::transform (TranslationUnit & translationUnit) override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 144 of file SemanticChecker.cpp.
{
         std::vector<std::string> suppressedRelations =
                 splitString(Global::config().get("suppress-warnings"), ',');
References souffle::Global::config(), TCB_SPAN_NAMESPACE_NAME::get(), and souffle::splitString().
The documentation for this class was generated from the following files:
ast/transform/SemanticChecker.h
ast/transform/SemanticChecker.cpp