souffle: souffle::profile::Tui Class Reference
souffle::profile::Tui Class Reference
#include <Tui.h>
Data Structures
struct Usage
Public Member Functions
std::stringstream & genJsonRelations (std::stringstream &ss, const std::string &name, size_t maxRows)
std::stringstream & genJsonTop (std::stringstream &ss)
void runCommand (std::vector< std::string > c)
void runProf ()
Tui ()
Tui (std::string filename, bool live, bool)
~Tui ()
Private Attributes
bool alive = false
std::string f_name
InputReader linereader
bool loaded
OutputProcessor out
int precision = 3
std::shared_ptr< Reader > reader
Table relationTable
size_t resultLimit = 20000
Limit results shown. Default value chosen to approximate unlimited.
Table ruleTable
int sortColumn = 0
std::thread updater
Detailed Description
Definition at line 56 of file Tui.h.
Constructor & Destructor Documentation
Tui() [1/2]
souffle::profile::Tui::Tui (std::string filename, bool live, bool) inline
Definition at line 83 of file Tui.h.
{
         // Set a friendlier output size if we're being interacted with directly.
         if (live) {
             resultLimit = 20;
         }
         this->f_name = filename;
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         this->reader = std::make_shared<Reader>(filename, run);
         this->alive = false;
         updateDB();
         this->loaded = reader->isLoaded();
     }
References souffle::profile::OutputProcessor::getProgramRun(), out, reader, resultLimit, and updateDB().
Tui() [2/2]
souffle::profile::Tui::Tui () inline
Definition at line 99 of file Tui.h.
           {
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         this->reader = std::make_shared<Reader>(run);
         this->loaded = true;
         this->alive = true;
         updateDB();
         updater = std::thread([this]() {
             // Update the display every 30s. Check for input every 0.5s
             std::chrono::milliseconds interval(30000);
             auto nextUpdateTime = std::chrono::high_resolution_clock::now();
             do {
                 std::this_thread::sleep_for(std::chrono::milliseconds(500));
                 if (nextUpdateTime < std::chrono::high_resolution_clock::now()) {
                     runCommand({});
                     nextUpdateTime = std::chrono::high_resolution_clock::now() + interval;
                 }
             } while (reader->isLive() && !linereader.hasReceivedInput());
         });
     }
References souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::InputReader::hasReceivedInput(), linereader, souffle::now(), out, reader, runCommand(), updateDB(), and updater.
~Tui()
souffle::profile::Tui::~Tui () inline
Definition at line 119 of file Tui.h.
            {
         if (updater.joinable()) {
             updater.join();
         }
     }
References updater.
Member Function Documentation
genJsonRelations()
std::stringstream& souffle::profile::Tui::genJsonRelations (std::stringstream & ss, const std::string & name, size_t maxRows) inline
Definition at line 269 of file Tui.h.
References souffle::profile::Tools::cleanJsonOut(), souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::Table::getRows(), i, out, relationTable, ruleTable, souffle::profile::ss, and souffle::toString().
Referenced by genJson().
genJsonTop()
std::stringstream& souffle::profile::Tui::genJsonTop (std::stringstream & ss) inline
Definition at line 258 of file Tui.h.
{
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         auto beginTime = run->getStarttime();
         auto endTime = run->getEndtime();
         ss << R"_({"top":[)_" << (endTime - beginTime).count() / 1000000.0 << "," << run->getTotalSize()
            << "," << run->getTotalLoadtime().count() / 1000000.0 << ","
            << run->getTotalSavetime().count() / 1000000.0 << "]";
         return ss;
     }
References souffle::test::count(), souffle::profile::OutputProcessor::getProgramRun(), out, and souffle::profile::ss.
Referenced by genJson().
runCommand()
void souffle::profile::Tui::runCommand (std::vector< std::string > c) inline
Definition at line 125 of file Tui.h.
{
         if (linereader.hasReceivedInput() && c.empty()) {
             return;
         }
         if (!loaded) {
             std::cout << "Error: File cannot be loaded\n";
             return;
         }
         if (alive) {
             updateDB();
             // remake tables to get new data
             ruleTable = out.getRulTable();
             relationTable = out.getRelTable();
             setupTabCompletion();
         }
         // If we have not received any input yet in live mode then run top.
         if ((!linereader.hasReceivedInput() && c.empty())) {
             // Move up n lines and overwrite the previous top output.
             std::cout << "\x1b[3D";
             std::cout << "\x1b[27A";
             top();
             std::cout << "\x1b[B> ";
         } else if (c[0] == "top") {
             top();
         } else if (c[0] == "rel") {
             if (c.size() == 2) {
                 relRul(c[1]);
             } else if (c.size() == 1) {
                 rel(resultLimit);
             } else {
                 std::cout << "Invalid parameters to rel command.\n";
             }
         } else if (c[0] == "rul") {
             if (c.size() > 1) {
                 if (c.size() == 3 && c[1] == "id") {
                     std::printf("%7s%2s%s\n\n", "ID", "", "NAME");
                     id(c[2]);
                 } else if (c.size() == 2 && c[1] == "id") {
                     id("0");
                 } else if (c.size() == 2) {
                     verRul(c[1]);
                 } else {
                     std::cout << "Invalid parameters to rul command.\n";
                 }
             } else {
                 rul(resultLimit);
             }
         } else if (c[0] == "graph") {
             if (c.size() == 3 && c[1].find(".") == std::string::npos) {
                 iterRel(c[1], c[2]);
             } else if (c.size() == 3 && c[1].at(0) == 'C') {
                 iterRul(c[1], c[2]);
             } else if (c.size() == 4 && c[1] == "ver" && c[2].at(0) == 'C') {
                 verGraph(c[2], c[3]);
             } else {
                 std::cout << "Invalid parameters to graph command.\n";
             }
         } else if (c[0] == "memory") {
             memoryUsage();
         } else if (c[0] == "usage") {
             if (c.size() > 1) {
                 if (c[1][0] == 'R') {
                     usageRelation(c[1]);
                 } else {
                     usageRule(c[1]);
                 }
             } else {
                 usage();
             }
         } else if (c[0] == "help") {
             help();
         } else if (c[0] == "limit") {
             if (c.size() == 1) {
                 setResultLimit(20000);
             } else {
                 try {
                     setResultLimit(std::stoul(c[1]));
                 } catch (...) {
                     std::cout << "Invalid parameters to limit command.\n";
                 }
             }
         } else if (c[0] == "configuration") {
             configuration();
         } else {
             std::cout << "Unknown command. Use \"help\" for a list of commands.\n";
         }
     }
References alive, configuration(), souffle::profile::OutputProcessor::getRelTable(), souffle::profile::OutputProcessor::getRulTable(), souffle::profile::InputReader::hasReceivedInput(), help(), id(), iterRel(), iterRul(), linereader, loaded, memoryUsage(), out, tinyformat::printf(), rel(), relationTable, relRul(), resultLimit, rul(), ruleTable, setResultLimit(), setupTabCompletion(), top(), updateDB(), usage(), usageRelation(), usageRule(), verGraph(), and verRul().
Referenced by souffle::profile::Cli::parse(), runProf(), and Tui().
runProf()
void souffle::profile::Tui::runProf () inline
Definition at line 216 of file Tui.h.
                    {
         if (!loaded && !f_name.empty()) {
             std::cout << "Error: File cannot be floaded\n";
             return;
         }
         if (loaded) {
             std::cout << "SouffleProf\n";
             top();
         }
         linereader.setPrompt("\n> ");
         setupTabCompletion();
         while (true) {
             std::string untrimmedInput = linereader.getInput();
             std::string input = Tools::trimWhitespace(untrimmedInput);
             std::cout << std::endl;
             if (input.empty()) {
                 std::cout << "Unknown command. Type help for a list of commands.\n";
                 continue;
             }
             linereader.addHistory(input);
             std::vector<std::string> c = Tools::split(input, " ");
             if (c[0] == "q" || c[0] == "quit") {
                 quit();
                 break;
             } else if (c[0] == "sort") {
                 if (c.size() == 2 && std::stoi(c[1]) < 7) {
                     sortColumn = std::stoi(c[1]);
                 } else {
                     std::cout << "Invalid column, please select a number between 0 and 6.\n";
                 }
             } else {
                 runCommand(c);
             }
         }
     }
References souffle::profile::InputReader::addHistory(), f_name, souffle::profile::InputReader::getInput(), linereader, loaded, quit(), runCommand(), souffle::profile::InputReader::setPrompt(), setupTabCompletion(), sortColumn, souffle::profile::Tools::split(), top(), and souffle::profile::Tools::trimWhitespace().
Referenced by souffle::profile::Cli::parse().
Field Documentation
alive
bool souffle::profile::Tui::alive = false private
Definition at line 61 of file Tui.h.
Referenced by runCommand(), and top().
f_name
std::string souffle::profile::Tui::f_name private
Definition at line 60 of file Tui.h.
Referenced by runProf().
linereader
InputReader souffle::profile::Tui::linereader private
Definition at line 68 of file Tui.h.
Referenced by runCommand(), runProf(), setupTabCompletion(), and Tui().
loaded
bool souffle::profile::Tui::loaded private
Definition at line 59 of file Tui.h.
Referenced by runCommand(), and runProf().
out
OutputProcessor souffle::profile::Tui::out private
Definition at line 58 of file Tui.h.
Referenced by genJsonAtoms(), genJsonRelations(), souffle::genJsonRules(), genJsonTop(), souffle::genJsonUsage(), iterRel(), iterRul(), relRul(), runCommand(), top(), Tui(), updateDB(), usageRelation(), usageRule(), verAtoms(), verGraph(), and verRul().
precision
int souffle::profile::Tui::precision = 3 private
Definition at line 64 of file Tui.h.
Referenced by graphBySize(), id(), iterRul(), rel(), relRul(), rul(), setupTabCompletion(), top(), usageRelation(), usageRule(), verAtoms(), and verRul().
reader
std::shared_ptr<Reader> souffle::profile::Tui::reader private
Definition at line 67 of file Tui.h.
Referenced by Tui(), and updateDB().
relationTable
Table souffle::profile::Tui::relationTable private
Definition at line 65 of file Tui.h.
Referenced by genJson(), genJsonRelations(), souffle::genJsonUsage(), iterRel(), rel(), relRul(), runCommand(), setupTabCompletion(), top(), updateDB(), and usageRelation().
resultLimit
size_t souffle::profile::Tui::resultLimit = 20000 private
Limit results shown. Default value chosen to approximate unlimited.
Definition at line 70 of file Tui.h.
Referenced by rel(), rul(), runCommand(), setResultLimit(), and Tui().
ruleTable
Table souffle::profile::Tui::ruleTable private
Definition at line 66 of file Tui.h.
Referenced by genJson(), genJsonRelations(), souffle::genJsonRules(), id(), iterRul(), relRul(), rul(), runCommand(), top(), updateDB(), usageRule(), and verRul().
sortColumn
int souffle::profile::Tui::sortColumn = 0 private
Definition at line 63 of file Tui.h.
Referenced by rel(), relRul(), rul(), runProf(), and verRul().
updater
std::thread souffle::profile::Tui::updater private
Definition at line 62 of file Tui.h.
Referenced by quit(), Tui(), and ~Tui().
The documentation for this class was generated from the following file:
include/souffle/profile/Tui.h