souffle: souffle::profile::Cli Class Reference
souffle::profile::Cli Class Reference
#include <Cli.h>
Public Member Functions
Cli (int argc, char *argv[])
void parse ()
Data Fields
std::map< char, std::string > args
Detailed Description
Definition at line 27 of file Cli.h.
Constructor & Destructor Documentation
Cli()
souffle::profile::Cli::Cli (int argc, char * argv[]) inline
Definition at line 31 of file Cli.h.
                                 : args() {
         int c;
         option longOptions[1];
         longOptions[0] = {nullptr, 0, nullptr, 0};
         while ((c = getopt_long(argc, argv, "c:hj::", longOptions, nullptr)) != EOF) {
             // An invalid argument was given
             if (c == '?') {
                 exit(EXIT_FAILURE);
             }
             if (optarg != nullptr) {
                 if (*optarg == '=') {
                     args[c] = optarg + 1;
                 } else {
                     args[c] = optarg;
                 }
             } else {
                 args[c] = c;
             }
         }
         if (optind < argc && args.count('f') == 0) {
             args['f'] = argv[optind];
         }
     }
References args.
Member Function Documentation
parse()
void souffle::profile::Cli::parse () inline
Definition at line 55 of file Cli.h.
                  {
         if (args.size() == 0) {
             std::cout << "No arguments provided.\nTry souffle-profile -h for help.\n";
             exit(EXIT_FAILURE);
         }
         if (args.count('h') != 0 || args.count('f') == 0) {
             std::cout << "Souffle Profiler" << std::endl
                       << "Usage: souffle-profile <log-file> [ -h | -c <command> [options] | -j ]" << std::endl
                       << "<log-file>            The log file to profile." << std::endl
                       << "-c <command>          Run the given command on the log file, try with  "
                          "'-c help' for a list"
                       << std::endl
                       << "                      of commands." << std::endl
                       << "-j[filename]          Generate a GUI (html/js) version of the profiler."
                       << std::endl
                       << "                      Default filename is profiler_html/[num].html" << std::endl
                       << "-h                    Print this help message." << std::endl;
             exit(0);
         }
         std::string filename = args['f'];
         if (args.count('c') != 0) {
             Tui tui(filename, false, false);
             for (auto& command : Tools::split(args['c'], ";")) {
                 tui.runCommand(Tools::split(command, " "));
             }
         } else if (args.count('j') != 0) {
             if (args['j'] == "j") {
                 Tui(filename, false, true).outputHtml();
             } else {
                 Tui(filename, false, true).outputHtml(args['j']);
             }
         } else {
             Tui(filename, true, false).runProf();
         }
     }
References args, souffle::profile::Tui::runCommand(), souffle::profile::Tui::runProf(), and souffle::profile::Tools::split().
Referenced by main().
Field Documentation
args
std::map<char, std::string> souffle::profile::Cli::args
Definition at line 29 of file Cli.h.
Referenced by Cli(), and parse().
The documentation for this class was generated from the following file:
include/souffle/profile/Cli.h