souffle: souffle::WriteCoutPrintSize Class Reference
souffle::WriteCoutPrintSize Class Reference
#include <WriteStreamCSV.h>
Public Member Functions
WriteCoutPrintSize (const std::map< std::string, std::string > &rwOperation)
~WriteCoutPrintSize () override=default
Public Member Functions inherited from souffle::WriteStream
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Public Member Functions inherited from souffle::SerialisationStream< true >
virtual ~SerialisationStream ()=default
Protected Member Functions
void writeNextTuple (const RamDomain *) override
void writeNullary () override
void writeSize (std::size_t size) override
Protected Member Functions inherited from souffle::WriteStream
void outputADT (std::ostream &destination, const RamDomain value, const std::string &name)
void outputRecord (std::ostream &destination, const RamDomain value, const std::string &name)
template<typename Tuple >
void writeNext (const Tuple tuple)
Protected Member Functions inherited from souffle::SerialisationStream< true >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
Protected Attributes
Lock::Lease lease
Protected Attributes inherited from souffle::WriteStream
const bool summary
Protected Attributes inherited from souffle::SerialisationStream< true >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< true >
using RO = std::conditional_t< readOnlyTables, const A, A >
Detailed Description
Definition at line 188 of file WriteStreamCSV.h.
Constructor & Destructor Documentation
WriteCoutPrintSize()
souffle::WriteCoutPrintSize::WriteCoutPrintSize (const std::map< std::string, std::string > & rwOperation) inline explicit
Definition at line 190 of file WriteStreamCSV.h.
          :
     void writeNullary() override {
References souffle::fatal().
Referenced by souffle::WriteCoutCSV::writeNextTuple().
~WriteCoutPrintSize()
souffle::WriteCoutPrintSize::~WriteCoutPrintSize () override default
Member Function Documentation
writeNextTuple()
void souffle::WriteCoutPrintSize::writeNextTuple (const RamDomain *) inline override protected virtual
Implements souffle::WriteStream.
Definition at line 202 of file WriteStreamCSV.h.
{
         std::cout << size << "\n";
     }
References TCB_SPAN_NAMESPACE_NAME::detail::size().
writeNullary()
void souffle::WriteCoutPrintSize::writeNullary () inline override protected virtual
Implements souffle::WriteStream.
Definition at line 198 of file WriteStreamCSV.h.
{
         fatal("attempting to iterate over a print size operation");
     }
References souffle::fatal().
writeSize()
void souffle::WriteCoutPrintSize::writeSize (std::size_t size) inline override protected virtual
Reimplemented from souffle::WriteStream.
Definition at line 206 of file WriteStreamCSV.h.
                           : public WriteStreamFactory {
Field Documentation
lease
Lock::Lease souffle::WriteCoutPrintSize::lease protected
Definition at line 210 of file WriteStreamCSV.h.
Referenced by souffle::WriteCoutCSV::writeNextTuple().
The documentation for this class was generated from the following file:
include/souffle/io/WriteStreamCSV.h