souffle: souffle::ast::NumericConstant Class Reference
souffle::ast::NumericConstant Class Reference
Numeric Constant.
#include <NumericConstant.h>
Public Types
enum Type { Type::Int, Type::Uint, Type::Float }
Public Member Functions
NumericConstant * clone () const override
Create clone.
std::optional< Type > getFinalType () const
const std::optional< Type > & getFixedType () const
NumericConstant (RamSigned value)
NumericConstant (std::string constant, SrcLocation loc)
NumericConstant (std::string constant, std::optional< Type > fixedType=std::nullopt, SrcLocation loc={})
void setFinalType (Type newType)
Public Member Functions inherited from souffle::ast::Constant
const std::string & getConstant () const
Get string representation of Constant.
Public Member Functions inherited from souffle::ast::Argument
Node (SrcLocation loc={})
Public Member Functions inherited from souffle::ast::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const Node * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the Node.
Node (SrcLocation loc={})
bool operator!= (const Node &other) const
Inequality check for two AST nodes.
bool operator== (const Node &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the Node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Abstract equality check for two AST nodes.
Protected Member Functions inherited from souffle::ast::Constant
Constant (std::string value, SrcLocation loc={})
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
std::optional< Type > finalTranslatorType
std::optional< Type > fixedType
Detailed Description
Numeric Constant.
The constant can be initialized with type. If this is the case, the typesystem will be forced to use it. Otherwise the type is inferred from context.
Definition at line 43 of file NumericConstant.h.
Member Enumeration Documentation
Type
enum souffle::ast::NumericConstant::Type strong
Enumerator
Int
Uint
Float
Definition at line 51 of file NumericConstant.h.
 {
Constructor & Destructor Documentation
NumericConstant() [1/3]
souffle::ast::NumericConstant::NumericConstant (RamSigned value) inline
Definition at line 53 of file NumericConstant.h.
 {
NumericConstant() [2/3]
souffle::ast::NumericConstant::NumericConstant (std::string constant, SrcLocation loc) inline
Definition at line 55 of file NumericConstant.h.
{
             copy->setFinalType(finalTranslatorType.value());
         }
References souffle::detail::brie::copy(), and finalTranslatorType.
NumericConstant() [3/3]
souffle::ast::NumericConstant::NumericConstant (std::string constant, std::optional< Type > fixedType = std::nullopt, SrcLocation loc = {}) inline
Definition at line 59 of file NumericConstant.h.
{
         return fixedType;
Member Function Documentation
clone()
NumericConstant* souffle::ast::NumericConstant::clone () const inline override virtual
Create clone.
Implements souffle::ast::Constant.
Definition at line 64 of file NumericConstant.h.
{
         finalTranslatorType = newType;
     }
     std::optional<Type> getFinalType() const {
         return finalTranslatorType;
     }
References finalTranslatorType.
equal()
bool souffle::ast::NumericConstant::equal (const Node &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::ast::Constant.
Definition at line 86 of file NumericConstant.h.
getFinalType()
std::optional<Type> souffle::ast::NumericConstant::getFinalType () const inline
Definition at line 81 of file NumericConstant.h.
getFixedType()
const std::optional<Type>& souffle::ast::NumericConstant::getFixedType () const inline
Definition at line 73 of file NumericConstant.h.
          :
     bool equal(const Node& node) const override {
         const auto& other = static_cast<const NumericConstant&>(node);
References souffle::ast::Constant::equal(), and fixedType.
Referenced by souffle::ast::analysis::TypeConstraintsAnalysis::visitNumericConstant().
setFinalType()
void souffle::ast::NumericConstant::setFinalType (Type newType) inline
Definition at line 77 of file NumericConstant.h.
        :
     std::optional<Type> fixedType;
Field Documentation
finalTranslatorType
std::optional<Type> souffle::ast::NumericConstant::finalTranslatorType private
Definition at line 95 of file NumericConstant.h.
Referenced by clone(), and NumericConstant().
fixedType
std::optional<Type> souffle::ast::NumericConstant::fixedType private
Definition at line 92 of file NumericConstant.h.
Referenced by getFixedType().
The documentation for this class was generated from the following file:
ast/NumericConstant.h