souffle: souffle::gzfstream::internal::gzfstreambuf Class Reference
souffle::gzfstream::internal::gzfstreambuf Class Reference
#include <gzfstream.h>
Public Member Functions
gzfstreambuf * close ()
gzfstreambuf ()
gzfstreambuf (const gzfstreambuf &)=delete
gzfstreambuf (gzfstreambuf &&old)=default
bool is_open () const
gzfstreambuf * open (const std::string &filename, std::ios_base::openmode mode)
~gzfstreambuf () override
Protected Member Functions
int_type overflow (int c=EOF) override
int sync () override
int_type underflow () override
Private Attributes
char buffer [bufferSize] = {}
gzFile fileHandle = {}
bool isOpen = false
std::ios_base::openmode mode = std::ios_base::in
Static Private Attributes
static constexpr unsigned int bufferSize = 65536
static constexpr unsigned int reserveSize = 16
Detailed Description
Definition at line 45 of file gzfstream.h.
Constructor & Destructor Documentation
gzfstreambuf() [1/3]
souffle::gzfstream::internal::gzfstreambuf::gzfstreambuf () inline
Definition at line 52 of file gzfstream.h.
{
             return nullptr;
         }
gzfstreambuf() [2/3]
souffle::gzfstream::internal::gzfstreambuf::gzfstreambuf (const gzfstreambuf &) delete
gzfstreambuf() [3/3]
souffle::gzfstream::internal::gzfstreambuf::gzfstreambuf (gzfstreambuf && old) default
~gzfstreambuf()
souffle::gzfstream::internal::gzfstreambuf::~gzfstreambuf () inline override
Definition at line 96 of file gzfstream.h.
{
Member Function Documentation
close()
gzfstreambuf* souffle::gzfstream::internal::gzfstreambuf::close () inline
Definition at line 81 of file gzfstream.h.
          :
     int_type overflow(int c = EOF) override {
         if (((mode & std::ios::out) == 0) || !isOpen) {
             return EOF;
         }
         if (c != EOF) {
is_open()
bool souffle::gzfstream::internal::gzfstreambuf::is_open () const inline
Definition at line 92 of file gzfstream.h.
{
Referenced by open().
open()
gzfstreambuf* souffle::gzfstream::internal::gzfstreambuf::open (const std::string & filename, std::ios_base::openmode mode) inline
Definition at line 61 of file gzfstream.h.
{
         if (is_open()) {
             sync();
             isOpen = false;
             if (gzclose(fileHandle) == Z_OK) {
                 return this;
             }
         }
         return nullptr;
     }
     bool is_open() const {
         return isOpen;
     }
     ~gzfstreambuf() override {
         try {
             close();
         } catch (...) {
References fileHandle, is_open(), isOpen, and sync().
overflow()
int_type souffle::gzfstream::internal::gzfstreambuf::overflow (int c = EOF) inline override protected
Definition at line 105 of file gzfstream.h.
{
             return traits_type::to_int_type(*gptr());
         }
         unsigned charsPutBack = gptr() - eback();
         if (charsPutBack > reserveSize) {
             charsPutBack = reserveSize;
         }
         memcpy(buffer + reserveSize - charsPutBack, gptr() - charsPutBack, charsPutBack);
         int charsRead = gzread(fileHandle, buffer + reserveSize, bufferSize - reserveSize);
         if (charsRead <= 0) {
             return EOF;
         }
sync()
int souffle::gzfstream::internal::gzfstreambuf::sync () inline override protected
Definition at line 147 of file gzfstream.h.
                 : virtual public std::ios {
 public:
     gzfstream() {
         init(&buf);
     }
     gzfstream(const std::string& filename, std::ios_base::openmode mode) {
         init(&buf);
         open(filename, mode);
References souffle::gzfstream::internal::gzfstream::buf, souffle::gzfstream::internal::gzfstream::gzfstream(), and souffle::gzfstream::internal::gzfstream::open().
Referenced by open().
underflow()
int_type souffle::gzfstream::internal::gzfstreambuf::underflow () inline override protected
Definition at line 123 of file gzfstream.h.
{
         if ((pptr() != nullptr) && pptr() > pbase()) {
             int toWrite = pptr() - pbase();
             if (gzwrite(fileHandle, pbase(), toWrite) != toWrite) {
                 return -1;
             }
             pbump(-toWrite);
         }
         return 0;
     }
 private:
     static constexpr unsigned int bufferSize = 65536;
     static constexpr unsigned int reserveSize = 16;
     char buffer[bufferSize] = {};
     gzFile fileHandle = {};
     bool isOpen = false;
     std::ios_base::openmode mode = std::ios_base::in;
Field Documentation
buffer
char souffle::gzfstream::internal::gzfstreambuf::buffer[bufferSize] = {} private
Definition at line 162 of file gzfstream.h.
bufferSize
constexpr unsigned int souffle::gzfstream::internal::gzfstreambuf::bufferSize = 65536 static constexpr private
Definition at line 159 of file gzfstream.h.
fileHandle
gzFile souffle::gzfstream::internal::gzfstreambuf::fileHandle = {} private
Definition at line 163 of file gzfstream.h.
Referenced by open().
isOpen
bool souffle::gzfstream::internal::gzfstreambuf::isOpen = false private
Definition at line 164 of file gzfstream.h.
Referenced by open().
mode
std::ios_base::openmode souffle::gzfstream::internal::gzfstreambuf::mode = std::ios_base::in private
Definition at line 165 of file gzfstream.h.
reserveSize
constexpr unsigned int souffle::gzfstream::internal::gzfstreambuf::reserveSize = 16 static constexpr private
Definition at line 160 of file gzfstream.h.
The documentation for this class was generated from the following file:
include/souffle/io/gzfstream.h