souffle: souffle::ast::analysis::PolymorphicObjectsAnalysis Class Reference
souffle::ast::analysis::PolymorphicObjectsAnalysis Class Reference
#include <PolymorphicObjects.h>
Public Member Functions
NumericConstant::Type getInferredType (const NumericConstant *nc) const
FunctorOp getOverloadedFunctionOp (const IntrinsicFunctor *inf) const
AggregateOp getOverloadedOperator (const Aggregator *agg) const
BinaryConstraintOp getOverloadedOperator (const BinaryConstraint *bc) const
bool hasInvalidType (const NumericConstant *nc) const
PolymorphicObjectsAnalysis ()
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Attributes
static constexpr const char * name = "polymorphic-objects"
Private Attributes
const TypeAnalysis * typeAnalysis = nullptr
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Definition at line 39 of file PolymorphicObjects.h.
Constructor & Destructor Documentation
PolymorphicObjectsAnalysis()
souffle::ast::analysis::PolymorphicObjectsAnalysis::PolymorphicObjectsAnalysis () inline
Definition at line 43 of file PolymorphicObjects.h.
 : Analysis(name) {}
Member Function Documentation
getInferredType()
NumericConstant::Type souffle::ast::analysis::PolymorphicObjectsAnalysis::getInferredType (const NumericConstant * nc) const
Definition at line 40 of file PolymorphicObjects.cpp.
{
     return !typeAnalysis->hasValidTypeInfo(nc);
 }
References souffle::ast::analysis::TypeAnalysis::hasValidTypeInfo(), and typeAnalysis.
getOverloadedFunctionOp()
FunctorOp souffle::ast::analysis::PolymorphicObjectsAnalysis::getOverloadedFunctionOp (const IntrinsicFunctor * inf) const
Definition at line 36 of file PolymorphicObjects.cpp.
{
     return typeAnalysis->getPolymorphicNumericConstantType(nc);
 }
References souffle::ast::analysis::TypeAnalysis::getPolymorphicNumericConstantType(), and typeAnalysis.
getOverloadedOperator() [1/2]
AggregateOp souffle::ast::analysis::PolymorphicObjectsAnalysis::getOverloadedOperator (const Aggregator * agg) const
Definition at line 52 of file PolymorphicObjects.cpp.
getOverloadedOperator() [2/2]
BinaryConstraintOp souffle::ast::analysis::PolymorphicObjectsAnalysis::getOverloadedOperator (const BinaryConstraint * bc) const
Definition at line 48 of file PolymorphicObjects.cpp.
{
     return typeAnalysis->getPolymorphicOperator(agg);
 }
References souffle::ast::analysis::TypeAnalysis::getPolymorphicOperator(), and typeAnalysis.
hasInvalidType()
bool souffle::ast::analysis::PolymorphicObjectsAnalysis::hasInvalidType (const NumericConstant * nc) const
Definition at line 44 of file PolymorphicObjects.cpp.
{
     return typeAnalysis->getPolymorphicOperator(bc);
 }
References souffle::ast::analysis::TypeAnalysis::getPolymorphicOperator(), and typeAnalysis.
Referenced by souffle::ast::transform::TypeCheckerImpl::visitStringConstant().
print()
void souffle::ast::analysis::PolymorphicObjectsAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 34 of file PolymorphicObjects.cpp.
run()
void souffle::ast::analysis::PolymorphicObjectsAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 30 of file PolymorphicObjects.cpp.
                                                           {}
 FunctorOp PolymorphicObjectsAnalysis::getOverloadedFunctionOp(const IntrinsicFunctor* inf) const {
Field Documentation
name
constexpr const char* souffle::ast::analysis::PolymorphicObjectsAnalysis::name = "polymorphic-objects" static constexpr
Definition at line 41 of file PolymorphicObjects.h.
typeAnalysis
const TypeAnalysis* souffle::ast::analysis::PolymorphicObjectsAnalysis::typeAnalysis = nullptr private
Definition at line 63 of file PolymorphicObjects.h.
Referenced by getInferredType(), getOverloadedFunctionOp(), getOverloadedOperator(), and hasInvalidType().
The documentation for this class was generated from the following files:
ast/analysis/PolymorphicObjects.h
ast/analysis/PolymorphicObjects.cpp