souffle: souffle::t_info< Arity_ > Class Template Reference
souffle::t_info< Arity_ > Class Template Reference
info relations
#include <CompiledSouffle.h>
Data Structures
struct context
class iterator
Public Types
using t_tuple = Tuple< RamDomain, Arity >
Public Member Functions
iterator begin () const
bool contains (const t_tuple &t) const
bool contains (const t_tuple &t, context &) const
context createContext ()
bool empty () const
iterator end () const
void insert (const RamDomain *ramDomain)
void insert (const t_tuple &t)
void insert (const t_tuple &t, context &)
void printStatistics (std::ostream &) const
void purge ()
std::size_t size () const
t_info ()=default
Static Public Attributes
static constexpr Relation::arity_type Arity = Arity_
Private Attributes
std::vector< Tuple< RamDomain, Arity > > data
Lock insert_lock
Detailed Description
template<Relation::arity_type Arity_>
class souffle::t_info< Arity_ >
info relations
Definition at line 270 of file CompiledSouffle.h.
Member Typedef Documentation
t_tuple
template<Relation::arity_type Arity_> using souffle::t_info< Arity_ >::t_tuple = Tuple<RamDomain, Arity>
Definition at line 275 of file CompiledSouffle.h.
Constructor & Destructor Documentation
t_info()
template<Relation::arity_type Arity_> souffle::t_info< Arity_ >::t_info () default
Member Function Documentation
begin()
template<Relation::arity_type Arity_> iterator souffle::t_info< Arity_ >::begin () const inline
Definition at line 303 of file CompiledSouffle.h.
{
         insert_lock.lock();
         if (!contains(t)) {
References souffle::t_info< Arity_ >::contains(), souffle::t_info< Arity_ >::insert_lock, and souffle::Lock::lock().
contains() [1/2]
template<Relation::arity_type Arity_> bool souffle::t_info< Arity_ >::contains (const t_tuple & t) const inline
Definition at line 328 of file CompiledSouffle.h.
{
         return contains(t);
     }
     std::size_t size() const {
         return data.size();
     }
Referenced by souffle::t_info< Arity_ >::begin().
contains() [2/2]
template<Relation::arity_type Arity_> bool souffle::t_info< Arity_ >::contains (const t_tuple & t, context &) const inline
Definition at line 336 of file CompiledSouffle.h.
{
         return data.size() == 0;
     }
References souffle::t_info< Arity_ >::data.
createContext()
template<Relation::arity_type Arity_> context souffle::t_info< Arity_ >::createContext () inline
Definition at line 277 of file CompiledSouffle.h.
           :
         iterator(const typename std::vector<t_tuple>::const_iterator& o) : it(o) {}
empty()
template<Relation::arity_type Arity_> bool souffle::t_info< Arity_ >::empty () const inline
Definition at line 342 of file CompiledSouffle.h.
                                               {}
 private:
end()
template<Relation::arity_type Arity_> iterator souffle::t_info< Arity_ >::end () const inline
Definition at line 306 of file CompiledSouffle.h.
{
insert() [1/3]
template<Relation::arity_type Arity_> void souffle::t_info< Arity_ >::insert (const RamDomain * ramDomain) inline
Definition at line 319 of file CompiledSouffle.h.
{
         for (const auto& o : data) {
             if (t == o) {
                 return true;
             }
         }
insert() [2/3]
template<Relation::arity_type Arity_> void souffle::t_info< Arity_ >::insert (const t_tuple & t) inline
Definition at line 309 of file CompiledSouffle.h.
{
         insert(t);
     }
     void insert(const RamDomain* ramDomain) {
         insert_lock.lock();
         t_tuple t;
insert() [3/3]
template<Relation::arity_type Arity_> void souffle::t_info< Arity_ >::insert (const t_tuple & t, context &) inline
Definition at line 316 of file CompiledSouffle.h.
{
             t.data[i] = ramDomain[i];
         }
References i.
printStatistics()
template<Relation::arity_type Arity_> void souffle::t_info< Arity_ >::printStatistics (std::ostream &) const inline
Definition at line 348 of file CompiledSouffle.h.
purge()
template<Relation::arity_type Arity_> void souffle::t_info< Arity_ >::purge () inline
Definition at line 345 of file CompiledSouffle.h.
size()
template<Relation::arity_type Arity_> std::size_t souffle::t_info< Arity_ >::size () const inline
Definition at line 339 of file CompiledSouffle.h.
                  {
         data.clear();
     }
References souffle::t_info< Arity_ >::data.
Field Documentation
Arity
template<Relation::arity_type Arity_> constexpr Relation::arity_type souffle::t_info< Arity_ >::Arity = Arity_ static constexpr
Definition at line 272 of file CompiledSouffle.h.
data
template<Relation::arity_type Arity_> std::vector<Tuple<RamDomain, Arity> > souffle::t_info< Arity_ >::data private
Definition at line 351 of file CompiledSouffle.h.
Referenced by souffle::t_info< Arity_ >::contains(), and souffle::t_info< Arity_ >::size().
insert_lock
template<Relation::arity_type Arity_> Lock souffle::t_info< Arity_ >::insert_lock private
Definition at line 352 of file CompiledSouffle.h.
Referenced by souffle::t_info< Arity_ >::begin().
The documentation for this class was generated from the following file:
include/souffle/CompiledSouffle.h