souffle: souffle::profile::NonRecursiveRuleNumberProcessor Class Reference
souffle::profile::NonRecursiveRuleNumberProcessor Class Reference
Non-Recursive Rule Number Profile Event Processor.
#include <EventProcessor.h>
Public Member Functions
NonRecursiveRuleNumberProcessor ()
void process (ProfileDatabase &db, const std::vector< std::string > &signature, va_list &args) override
process event input
Public Member Functions inherited from souffle::profile::EventProcessor
virtual ~EventProcessor ()=default
Detailed Description
Non-Recursive Rule Number Profile Event Processor.
Definition at line 223 of file EventProcessor.h.
Constructor & Destructor Documentation
NonRecursiveRuleNumberProcessor()
souffle::profile::NonRecursiveRuleNumberProcessor::NonRecursiveRuleNumberProcessor () inline
Definition at line 225 of file EventProcessor.h.
                                          : public EventProcessor {
Member Function Documentation
process()
void souffle::profile::NonRecursiveRuleNumberProcessor::process (ProfileDatabase & db, const std::vector< std::string > & signature, va_list & args) inline override virtual
process event input
Reimplemented from souffle::profile::EventProcessor.
Definition at line 229 of file EventProcessor.h.
                                          : public EventProcessor {
 public:
     RecursiveRuleTimingProcessor() {
         EventProcessorSingleton::instance().registerEventProcessor("@t-recursive-rule", this);
     }
     void process(ProfileDatabase& db, const std::vector<std::string>& signature, va_list& args) override {
         const std::string& relation = signature[1];
         const std::string& version = signature[2];
         const std::string& srcLocator = signature[3];
References souffle::profile::EventProcessorSingleton::instance(), souffle::profile::RecursiveRuleTimingProcessor::process(), souffle::profile::RecursiveRuleTimingProcessor::RecursiveRuleTimingProcessor(), souffle::profile::EventProcessorSingleton::registerEventProcessor(), relation, and rule.
The documentation for this class was generated from the following file:
include/souffle/profile/EventProcessor.h