souffle: souffle::WriteCoutCSV Class Reference
souffle::WriteCoutCSV Class Reference
#include <WriteStreamCSV.h>
Public Member Functions
WriteCoutCSV (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
~WriteCoutCSV () override
Public Member Functions inherited from souffle::WriteStream
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Public Member Functions inherited from souffle::SerialisationStream< true >
virtual ~SerialisationStream ()=default
Protected Member Functions
void writeNextTuple (const RamDomain *tuple) override
void writeNullary () override
Protected Member Functions inherited from souffle::WriteStreamCSV
void writeNextTupleCSV (std::ostream &destination, const RamDomain *tuple)
void writeNextTupleElement (std::ostream &destination, const std::string &type, RamDomain value)
WriteStreamCSV (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Protected Member Functions inherited from souffle::WriteStream
void outputADT (std::ostream &destination, const RamDomain value, const std::string &name)
void outputRecord (std::ostream &destination, const RamDomain value, const std::string &name)
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeSize (std::size_t)
Protected Member Functions inherited from souffle::SerialisationStream< true >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< true >
using RO = std::conditional_t< readOnlyTables, const A, A >
Protected Attributes inherited from souffle::WriteStreamCSV
const std::string delimiter
Protected Attributes inherited from souffle::WriteStream
const bool summary
Protected Attributes inherited from souffle::SerialisationStream< true >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Detailed Description
Definition at line 161 of file WriteStreamCSV.h.
Constructor & Destructor Documentation
WriteCoutCSV()
souffle::WriteCoutCSV::WriteCoutCSV (const std::map< std::string, std::string > & rwOperation, const SymbolTable & symbolTable, const RecordTable & recordTable) inline
Definition at line 163 of file WriteStreamCSV.h.
{
             std::cout << "\n" << rwOperation.at("attributeNames");
         }
         std::cout << "\n===============\n";
         std::cout << std::setprecision(std::numeric_limits<RamFloat>::max_digits10);
     }
     ~WriteCoutCSV() override {
         std::cout << "===============\n";
     }
~WriteCoutCSV()
souffle::WriteCoutCSV::~WriteCoutCSV () inline override
Definition at line 174 of file WriteStreamCSV.h.
          :
     void writeNullary() override {
         std::cout << "()\n";
Member Function Documentation
writeNextTuple()
void souffle::WriteCoutCSV::writeNextTuple (const RamDomain * tuple) inline override protected virtual
Implements souffle::WriteStream.
Definition at line 183 of file WriteStreamCSV.h.
                          : public WriteStream {
 public:
References souffle::getOutputLock(), souffle::WriteCoutPrintSize::lease, souffle::WriteCoutPrintSize::WriteCoutPrintSize(), and souffle::WriteStream::WriteStream().
writeNullary()
void souffle::WriteCoutCSV::writeNullary () inline override protected virtual
Implements souffle::WriteStream.
Definition at line 179 of file WriteStreamCSV.h.
{
         writeNextTupleCSV(std::cout, tuple);
     }
References souffle::WriteStreamCSV::writeNextTupleCSV().
The documentation for this class was generated from the following file:
include/souffle/io/WriteStreamCSV.h