souffle: souffle::interpreter::RelInterface Class Reference
souffle::interpreter::RelInterface Class Reference
Wrapper class for interpreter relations.
#include <ProgInterface.h>
Data Structures
class iterator_base
Iterator wrapper class.
Public Member Functions
iterator begin () const override
Iterator to first tuple.
bool contains (const tuple &t) const override
Check whether tuple exists.
iterator end () const override
Iterator to last tuple.
arity_type getArity () const override
Get arity.
const char * getAttrName (size_t idx) const override
Get attribute name.
const char * getAttrType (size_t idx) const override
Get attribute type.
arity_type getAuxiliaryArity () const override
Get arity.
std::string getName () const override
Get name.
SymbolTable & getSymbolTable () const override
Get symbol table.
void insert (const tuple &t) override
Insert tuple.
void purge () override
Eliminate all the tuples in relation.
RelInterface (RelationWrapper &r, SymbolTable &s, std::string n, std::vector< std::string > t, std::vector< std::string > an, uint32_t i)
size_t size () const override
Get number of tuples in relation.
~RelInterface () override=default
Public Member Functions inherited from souffle::Relation
arity_type getPrimaryArity () const
Return the number of non-auxiliary attributes.
std::string getSignature ()
Get the signature of a relation.
virtual ~Relation ()=default
Destructor.
Private Attributes
std::vector< std::string > attrNames
Attribute Names.
uint32_t id
Unique id for wrapper.
std::string name
Name of relation.
RelationWrapper & relation
Wrapped interpreter relation.
SymbolTable & symTable
Symbol table.
std::vector< std::string > types
Attribute type.
Additional Inherited Members
Public Types inherited from souffle::Relation
using arity_type = uint32_t
Detailed Description
Wrapper class for interpreter relations.
Definition at line 53 of file ProgInterface.h.
Constructor & Destructor Documentation
RelInterface()
souffle::interpreter::RelInterface::RelInterface (RelationWrapper & r, SymbolTable & s, std::string n, std::vector< std::string > t, std::vector< std::string > an, uint32_t i) inline
Definition at line 61 of file ProgInterface.h.
{
         return relation.contains(t.data);
     }
References souffle::interpreter::RelationWrapper::contains(), souffle::tuple::data, and relation.
~RelInterface()
souffle::interpreter::RelInterface::~RelInterface () override default
Member Function Documentation
begin()
iterator souffle::interpreter::RelInterface::begin () const inline override virtual
Iterator to first tuple.
Implements souffle::Relation.
Definition at line 78 of file ProgInterface.h.
{
contains()
bool souffle::interpreter::RelInterface::contains (const tuple & t) const inline override virtual
Check whether tuple exists.
Implements souffle::Relation.
Definition at line 73 of file ProgInterface.h.
end()
iterator souffle::interpreter::RelInterface::end () const inline override virtual
Iterator to last tuple.
Implements souffle::Relation.
Definition at line 83 of file ProgInterface.h.
{
getArity()
arity_type souffle::interpreter::RelInterface::getArity () const inline override virtual
Get arity.
Implements souffle::Relation.
Definition at line 93 of file ProgInterface.h.
{
getAttrName()
const char* souffle::interpreter::RelInterface::getAttrName (size_t idx) const inline override virtual
Get attribute name.
Implements souffle::Relation.
Definition at line 114 of file ProgInterface.h.
          :
     /**
getAttrType()
const char* souffle::interpreter::RelInterface::getAttrType (size_t idx) const inline override virtual
Get attribute type.
Implements souffle::Relation.
Definition at line 108 of file ProgInterface.h.
{
         return relation.size();
     }
References relation, and souffle::interpreter::RelationWrapper::size().
Referenced by souffle::interpreter::RelInterface::iterator_base::iterator_base().
getAuxiliaryArity()
arity_type souffle::interpreter::RelInterface::getAuxiliaryArity () const inline override virtual
Get arity.
Implements souffle::Relation.
Definition at line 98 of file ProgInterface.h.
{
getName()
std::string souffle::interpreter::RelInterface::getName () const inline override virtual
Get name.
Implements souffle::Relation.
Definition at line 88 of file ProgInterface.h.
{
getSymbolTable()
SymbolTable& souffle::interpreter::RelInterface::getSymbolTable () const inline override virtual
Get symbol table.
Implements souffle::Relation.
Definition at line 103 of file ProgInterface.h.
{
Referenced by souffle::interpreter::RelInterface::iterator_base::operator++().
insert()
void souffle::interpreter::RelInterface::insert (const tuple & t) inline override virtual
Insert tuple.
Implements souffle::Relation.
Definition at line 68 of file ProgInterface.h.
{
purge()
void souffle::interpreter::RelInterface::purge () inline override virtual
Eliminate all the tuples in relation.
Implements souffle::Relation.
Definition at line 125 of file ProgInterface.h.
{
References souffle::interpreter::RelInterface::iterator_base::it.
size()
size_t souffle::interpreter::RelInterface::size () const inline override virtual
Get number of tuples in relation.
Implements souffle::Relation.
Definition at line 120 of file ProgInterface.h.
                         : public souffle::Relation::iterator_base {
     public:
References i, souffle::interpreter::RelInterface::iterator_base::it, souffle::interpreter::RelInterface::iterator_base::iterator_base(), souffle::interpreter::RelInterface::iterator_base::ramRelationInterface, and souffle::interpreter::RelInterface::iterator_base::tup.
Field Documentation
attrNames
std::vector<std::string> souffle::interpreter::RelInterface::attrNames private
Attribute Names.
Definition at line 211 of file ProgInterface.h.
id
uint32_t souffle::interpreter::RelInterface::id private
Unique id for wrapper.
Definition at line 214 of file ProgInterface.h.
name
std::string souffle::interpreter::RelInterface::name private
Name of relation.
Definition at line 205 of file ProgInterface.h.
relation
RelationWrapper& souffle::interpreter::RelInterface::relation private
Wrapped interpreter relation.
Definition at line 199 of file ProgInterface.h.
Referenced by getAttrType(), and RelInterface().
symTable
SymbolTable& souffle::interpreter::RelInterface::symTable private
Symbol table.
Definition at line 202 of file ProgInterface.h.
types
std::vector<std::string> souffle::interpreter::RelInterface::types private
Attribute type.
Definition at line 208 of file ProgInterface.h.
The documentation for this class was generated from the following file:
interpreter/ProgInterface.h