souffle: souffle::interpreter::NestedOperation Class Reference
souffle::interpreter::NestedOperation Class Reference
Encode a nested operation for the interpreter node. E.g. Loop, IndexScan.
#include <Node.h>
Public Member Functions
const Node * getNestedOperation () const
NestedOperation (Own< Node > nested)
Protected Attributes
Own< Node > nested
Detailed Description
Encode a nested operation for the interpreter node. E.g. Loop, IndexScan.
Definition at line 387 of file Node.h.
Constructor & Destructor Documentation
NestedOperation()
souffle::interpreter::NestedOperation::NestedOperation (Own< Node > nested) inline
Definition at line 389 of file Node.h.
 {
Referenced by souffle::interpreter::BinRelOperation::getTargetId(), souffle::interpreter::IndexAggregate::IndexAggregate(), and souffle::interpreter::IndexChoice::IndexChoice().
Member Function Documentation
getNestedOperation()
const Node* souffle::interpreter::NestedOperation::getNestedOperation () const inline
Definition at line 391 of file Node.h.
       :
     ConditionalOperation(Own<Node> cond) : cond(std::move(cond)) {}
Referenced by souffle::interpreter::BinRelOperation::getTargetId().
Field Documentation
nested
Own<Node> souffle::interpreter::NestedOperation::nested protected
Definition at line 393 of file Node.h.
Referenced by souffle::interpreter::Choice::Choice(), souffle::interpreter::BinRelOperation::getTargetId(), souffle::interpreter::IndexAggregate::IndexAggregate(), souffle::interpreter::IndexChoice::IndexChoice(), souffle::interpreter::IndexScan::IndexScan(), and souffle::interpreter::Scan::Scan().
The documentation for this class was generated from the following file:
interpreter/Node.h