souffle: souffle::interpreter::SuperOperation Class Reference
souffle::interpreter::SuperOperation Class Reference
node that utilizes the super instruction optimization should inherit from this class. E.g. ExistenceCheck, Project
#include <Node.h>
Public Member Functions
const SuperInstruction & getSuperInst () const
SuperOperation (SuperInstruction superInst)
Protected Attributes
const SuperInstruction superInst
Detailed Description
node that utilizes the super instruction optimization should inherit from this class. E.g. ExistenceCheck, Project
Definition at line 311 of file Node.h.
Constructor & Destructor Documentation
SuperOperation()
souffle::interpreter::SuperOperation::SuperOperation (SuperInstruction superInst) inline
Definition at line 313 of file Node.h.
 {
Referenced by souffle::interpreter::Choice::Choice(), souffle::interpreter::ExistenceCheck::getRelationName(), and souffle::interpreter::Scan::Scan().
Member Function Documentation
getSuperInst()
const SuperInstruction& souffle::interpreter::SuperOperation::getSuperInst () const inline
Definition at line 315 of file Node.h.
{
 public:
     /** @brief get view context for operations */
References souffle::interpreter::AbstractParallel::getViewContext(), and souffle::interpreter::AbstractParallel::viewContext.
Field Documentation
superInst
const SuperInstruction souffle::interpreter::SuperOperation::superInst protected
Definition at line 320 of file Node.h.
Referenced by souffle::interpreter::Choice::Choice(), souffle::interpreter::ExistenceCheck::getRelationName(), and souffle::interpreter::Scan::Scan().
The documentation for this class was generated from the following file:
interpreter/Node.h