souffle: souffle::ram::LogSize Class Reference
souffle::ram::LogSize Class Reference
Log relation size and a logging message.
#include <LogSize.h>
Public Member Functions
LogSize * clone () const override
Create a clone (i.e.
const std::string & getMessage () const
Get logging message.
LogSize (std::string rel, std::string message)
Public Member Functions inherited from souffle::ram::RelationStatement
const std::string & getRelation () const
Get RAM relation.
RelationStatement (std::string rel)
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::RelationStatement
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
const std::string message
Logging message.
Protected Attributes inherited from souffle::ram::RelationStatement
std::string relation
Relation.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Log relation size and a logging message.
Definition at line 38 of file LogSize.h.
Constructor & Destructor Documentation
LogSize()
souffle::ram::LogSize::LogSize (std::string rel, std::string message) inline
Definition at line 40 of file LogSize.h.
 {
Referenced by getMessage().
Member Function Documentation
clone()
LogSize* souffle::ram::LogSize::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 47 of file LogSize.h.
          :
     void print(std::ostream& os, int tabpos) const override {
         os << times(" ", tabpos) << "LOGSIZE " << relation;
References message, souffle::ram::RelationStatement::relation, souffle::stringify(), and souffle::times().
equal()
bool souffle::ram::LogSize::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 59 of file LogSize.h.
getMessage()
const std::string& souffle::ram::LogSize::getMessage () const inline
Get logging message.
Definition at line 43 of file LogSize.h.
{
         return new LogSize(relation, message);
     }
References LogSize(), message, and souffle::ram::RelationStatement::relation.
print()
void souffle::ram::LogSize::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 52 of file LogSize.h.
{
         const auto& other = static_cast<const LogSize&>(node);
         return RelationStatement::equal(other) && message == other.message;
Field Documentation
message
const std::string souffle::ram::LogSize::message protected
Logging message.
Definition at line 65 of file LogSize.h.
Referenced by clone(), and getMessage().
The documentation for this class was generated from the following file:
ram/LogSize.h