souffle: souffle::ram::Extend Class Reference
souffle::ram::Extend Class Reference
Extend equivalence relation.
#include <Extend.h>
Public Member Functions
Extend * clone () const override
Create a clone (i.e.
Extend (std::string tRef, const std::string &sRef)
const std::string & getSourceRelation () const
Get source relation.
const std::string & getTargetRelation () const
Get target relation.
Public Member Functions inherited from souffle::ram::BinRelationStatement
BinRelationStatement (std::string f, std::string s)
const std::string & getFirstRelation () const
Get first relation.
const std::string & getSecondRelation () const
Get second relation.
Public Member Functions inherited from souffle::ram::Node
virtual void apply (const NodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const Node * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::BinRelationStatement
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Statement
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Statement
static void print (const Statement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::BinRelationStatement
const std::string first
First relation.
const std::string second
Second relation.
Detailed Description
Extend equivalence relation.
The following example merges A into B:
EXTEND B WITH A
Definition at line 41 of file Extend.h.
Constructor & Destructor Documentation
Extend()
souffle::ram::Extend::Extend (std::string tRef, const std::string & sRef) inline
Definition at line 43 of file Extend.h.
Referenced by getTargetRelation().
Member Function Documentation
clone()
Extend* souffle::ram::Extend::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Statement.
Definition at line 55 of file Extend.h.
          :
     void print(std::ostream& os, int tabpos) const override {
         os << times(" ", tabpos);
References getSourceRelation(), getTargetRelation(), and souffle::times().
getSourceRelation()
const std::string& souffle::ram::Extend::getSourceRelation () const inline
Get source relation.
Definition at line 46 of file Extend.h.
{
         return getSecondRelation();
References souffle::ram::BinRelationStatement::getSecondRelation().
Referenced by clone().
getTargetRelation()
const std::string& souffle::ram::Extend::getTargetRelation () const inline
Get target relation.
Definition at line 51 of file Extend.h.
{
         auto* res = new Extend(second, first);
         return res;
References Extend(), souffle::ram::BinRelationStatement::first, and souffle::ram::BinRelationStatement::second.
Referenced by clone().
print()
void souffle::ram::Extend::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::ram::Statement.
Definition at line 61 of file Extend.h.
The documentation for this class was generated from the following file:
ram/Extend.h