souffle: souffle::interpreter::ViewContext Class Reference
souffle::interpreter::ViewContext Class Reference
This class contains information for views (Hints) creation for ram::Query and ram::Parallel operation.
#include <ViewContext.h>
Public Member Functions
void addViewFreeOperationForFilter (Own< Node > node)
Add outer-most filter operation which does not require a view.
void addViewInfoForFilter (size_t relId, size_t indexPos, size_t viewPos)
Add View creation information into the list for outer filter.
void addViewInfoForNested (size_t relId, size_t indexPos, size_t viewPos)
Add View creation information into the list for nested oprations.
void addViewOperationForFilter (Own< Node > node)
Add outer-most filter operation which requires a view.
void addViewOperationForNested (Own< Node > op)
Add nested operation which require a View (Hints).
const VecOwn< Node > & getOuterFilterViewFreeOps ()
Return views for outer-most filter operations.
const VecOwn< Node > & getOuterFilterViewOps ()
Return outer-most filter operations.
std::vector< std::array< size_t, 3 > > & getViewInfoForFilter ()
Return Views information for outer filter operation.
std::vector< std::array< size_t, 3 > > & getViewInfoForNested ()
Return Views information for nested operation.
VecOwn< Node > & getViewsInNestedOperation ()
Return nested operations.
Data Fields
bool isParallel = false
If this context has information for parallel operation.
Private Attributes
VecOwn< Node > nestedViewOps
Vector of nested operations.
VecOwn< Node > outerFilterViewFreeOps
Vector of filter operations, no views required.
VecOwn< Node > outerFilterViewOps
Vector of filter operation, views required.
std::vector< std::array< size_t, 3 > > viewInfoForFilter
Vector of View information in filter operations.
std::vector< std::array< size_t, 3 > > viewInfoForNested
Vector of View information in nested operations.
Detailed Description
This class contains information for views (Hints) creation for ram::Query and ram::Parallel operation.
Definition at line 39 of file ViewContext.h.
Member Function Documentation
addViewFreeOperationForFilter()
void souffle::interpreter::ViewContext::addViewFreeOperationForFilter (Own< Node > node) inline
Add outer-most filter operation which does not require a view.
Definition at line 47 of file ViewContext.h.
{
addViewInfoForFilter()
void souffle::interpreter::ViewContext::addViewInfoForFilter (size_t relId, size_t indexPos, size_t viewPos) inline
Add View creation information into the list for outer filter.
Definition at line 82 of file ViewContext.h.
        :
     /** Vector of filter operation, views required */
addViewInfoForNested()
void souffle::interpreter::ViewContext::addViewInfoForNested (size_t relId, size_t indexPos, size_t viewPos) inline
Add View creation information into the list for nested oprations.
Definition at line 87 of file ViewContext.h.
        :
     /** Vector of filter operation, views required */
     VecOwn<Node> outerFilterViewOps;
addViewOperationForFilter()
void souffle::interpreter::ViewContext::addViewOperationForFilter (Own< Node > node) inline
Add outer-most filter operation which requires a view.
Definition at line 42 of file ViewContext.h.
{
addViewOperationForNested()
void souffle::interpreter::ViewContext::addViewOperationForNested (Own< Node > op) inline
Add nested operation which require a View (Hints).
Definition at line 52 of file ViewContext.h.
{
getOuterFilterViewFreeOps()
const VecOwn<Node>& souffle::interpreter::ViewContext::getOuterFilterViewFreeOps () inline
Return views for outer-most filter operations.
Definition at line 62 of file ViewContext.h.
Referenced by souffle::interpreter::Engine::execute().
getOuterFilterViewOps()
const VecOwn<Node>& souffle::interpreter::ViewContext::getOuterFilterViewOps () inline
Return outer-most filter operations.
Definition at line 57 of file ViewContext.h.
{
Referenced by souffle::interpreter::Engine::execute().
getViewInfoForFilter()
std::vector<std::array<size_t, 3> >& souffle::interpreter::ViewContext::getViewInfoForFilter () inline
Return Views information for outer filter operation.
Definition at line 72 of file ViewContext.h.
{
Referenced by souffle::interpreter::Engine::execute().
getViewInfoForNested()
std::vector<std::array<size_t, 3> >& souffle::interpreter::ViewContext::getViewInfoForNested () inline
Return Views information for nested operation.
Definition at line 77 of file ViewContext.h.
{
Referenced by souffle::interpreter::Engine::execute().
getViewsInNestedOperation()
VecOwn<Node>& souffle::interpreter::ViewContext::getViewsInNestedOperation () inline
Return nested operations.
Definition at line 67 of file ViewContext.h.
Field Documentation
isParallel
bool souffle::interpreter::ViewContext::isParallel = false
If this context has information for parallel operation.
Definition at line 92 of file ViewContext.h.
Referenced by souffle::interpreter::Engine::execute().
nestedViewOps
VecOwn<Node> souffle::interpreter::ViewContext::nestedViewOps private
Vector of nested operations.
Definition at line 100 of file ViewContext.h.
outerFilterViewFreeOps
VecOwn<Node> souffle::interpreter::ViewContext::outerFilterViewFreeOps private
Vector of filter operations, no views required.
Definition at line 98 of file ViewContext.h.
outerFilterViewOps
VecOwn<Node> souffle::interpreter::ViewContext::outerFilterViewOps private
Vector of filter operation, views required.
Definition at line 96 of file ViewContext.h.
viewInfoForFilter
std::vector<std::array<size_t, 3> > souffle::interpreter::ViewContext::viewInfoForFilter private
Vector of View information in filter operations.
Definition at line 102 of file ViewContext.h.
viewInfoForNested
std::vector<std::array<size_t, 3> > souffle::interpreter::ViewContext::viewInfoForNested private
Vector of View information in nested operations.
Definition at line 104 of file ViewContext.h.
The documentation for this class was generated from the following file:
interpreter/ViewContext.h