souffle: souffle::ast::transform::FixpointTransformer Class Reference
souffle::ast::transform::FixpointTransformer Class Reference
Transformer that repeatedly executes a sub-transformer until no changes are made.
#include <Fixpoint.h>
Public Member Functions
FixpointTransformer * clone () const override
void disableTransformers (const std::set< std::string > &transforms) override
FixpointTransformer (Own< Transformer > transformer)
std::string getName () const override
std::vector< Transformer * > getSubtransformers () const override
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::ast::transform::MetaTransformer
bool applySubtransformer (TranslationUnit &translationUnit, Transformer *transformer)
Public Member Functions inherited from souffle::ast::transform::Transformer
bool apply (TranslationUnit &translationUnit)
virtual ~Transformer ()=default
Private Member Functions
bool transform (TranslationUnit &translationUnit) override
Private Attributes
Own< Transformer > transformer
Additional Inherited Members
Protected Attributes inherited from souffle::ast::transform::MetaTransformer
bool verbose = false
Detailed Description
Transformer that repeatedly executes a sub-transformer until no changes are made.
Definition at line 42 of file Fixpoint.h.
Constructor & Destructor Documentation
FixpointTransformer()
souffle::ast::transform::FixpointTransformer::FixpointTransformer (Own< Transformer > transformer) inline
Definition at line 50 of file Fixpoint.h.
 {
Referenced by disableTransformers().
Member Function Documentation
clone()
FixpointTransformer* souffle::ast::transform::FixpointTransformer::clone () const inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 83 of file Fixpoint.h.
disableTransformers()
void souffle::ast::transform::FixpointTransformer::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 71 of file Fixpoint.h.
{
         return new FixpointTransformer(souffle::clone(transformer));
     }
 private:
     Own<Transformer> transformer;
     bool transform(TranslationUnit& translationUnit) override {
References souffle::clone(), FixpointTransformer(), and transformer.
getName()
std::string souffle::ast::transform::FixpointTransformer::getName () const inline override virtual
Implements souffle::ast::transform::Transformer.
Definition at line 79 of file Fixpoint.h.
{
             changed = true;
         }
getSubtransformers()
std::vector<Transformer*> souffle::ast::transform::FixpointTransformer::getSubtransformers () const inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 60 of file Fixpoint.h.
{
             mt->disableTransformers(transforms);
         } else if (transforms.find(transformer->getName()) != transforms.end()) {
setDebugReport()
void souffle::ast::transform::FixpointTransformer::setDebugReport () inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 52 of file Fixpoint.h.
{
         this->verbose = verbose;
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->setVerbosity(verbose);
         }
     }
References transformer, and souffle::ast::transform::MetaTransformer::verbose.
setVerbosity()
void souffle::ast::transform::FixpointTransformer::setVerbosity (bool verbose) inline override virtual
Implements souffle::ast::transform::MetaTransformer.
Definition at line 64 of file Fixpoint.h.
{
         return "FixpointTransformer";
     }
transform()
bool souffle::ast::transform::FixpointTransformer::transform (TranslationUnit & translationUnit) inline override private virtual
Implements souffle::ast::transform::Transformer.
Definition at line 89 of file Fixpoint.h.
Field Documentation
transformer
Own<Transformer> souffle::ast::transform::FixpointTransformer::transformer private
Definition at line 88 of file Fixpoint.h.
Referenced by disableTransformers(), and setDebugReport().
The documentation for this class was generated from the following file:
ast/transform/Fixpoint.h