souffle: souffle::ram::Negation Class Reference
souffle::ram::Negation Class Reference
Negates a given condition.
#include <Negation.h>
Public Member Functions
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Negation * clone () const override
Create a clone (i.e.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
const Condition & getOperand () const
Get operand of negation.
Negation (Own< Condition > op)
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Protected Member Functions
bool equal (const Node &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< Condition > operand
Operand.
Detailed Description
Negates a given condition.
For example:
(NOT t0 IN A)
Definition at line 49 of file Negation.h.
Constructor & Destructor Documentation
Negation()
souffle::ram::Negation::Negation (Own< Condition > op) inline
Definition at line 51 of file Negation.h.
{
Referenced by getOperand().
Member Function Documentation
apply()
void souffle::ram::Negation::apply (const NodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 68 of file Negation.h.
{
clone()
Negation* souffle::ram::Negation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::ram::Condition.
Definition at line 64 of file Negation.h.
          :
     void print(std::ostream& os) const override {
References operand.
equal()
bool souffle::ram::Negation::equal (const Node &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::ram::Node.
Definition at line 77 of file Negation.h.
getChildNodes()
std::vector<const Node*> souffle::ram::Negation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::ram::Node.
Definition at line 60 of file Negation.h.
{
         operand = map(std::move(operand));
References souffle::map(), and operand.
getOperand()
const Condition& souffle::ram::Negation::getOperand () const inline
Get operand of negation.
Definition at line 56 of file Negation.h.
{
         return new Negation(souffle::clone(operand));
References souffle::clone(), Negation(), and operand.
print()
void souffle::ram::Negation::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::ram::Node.
Definition at line 73 of file Negation.h.
Field Documentation
operand
Own<Condition> souffle::ram::Negation::operand protected
Operand.
Definition at line 83 of file Negation.h.
Referenced by clone(), getChildNodes(), and getOperand().
The documentation for this class was generated from the following file:
ram/Negation.h