souffle: souffle::profile::RelationIOTimingProcessor Class Reference
souffle::profile::RelationIOTimingProcessor Class Reference
Recursive Relation Copy Timing Profile Event Processor.
#include <EventProcessor.h>
Public Member Functions
void process (ProfileDatabase &db, const std::vector< std::string > &signature, va_list &args) override
process event input
RelationIOTimingProcessor ()
Public Member Functions inherited from souffle::profile::EventProcessor
virtual ~EventProcessor ()=default
Detailed Description
Recursive Relation Copy Timing Profile Event Processor.
Definition at line 422 of file EventProcessor.h.
Constructor & Destructor Documentation
RelationIOTimingProcessor()
souffle::profile::RelationIOTimingProcessor::RelationIOTimingProcessor () inline
Definition at line 424 of file EventProcessor.h.
                                       : public EventProcessor {
Member Function Documentation
process()
void souffle::profile::RelationIOTimingProcessor::process (ProfileDatabase & db, const std::vector< std::string > & signature, va_list & args) inline override virtual
process event input
Reimplemented from souffle::profile::EventProcessor.
Definition at line 429 of file EventProcessor.h.
                                       : public EventProcessor {
 public:
     ProgramTimepointProcessor() {
         EventProcessorSingleton::instance().registerEventProcessor("@time", this);
     }
     /** process event input */
     void process(ProfileDatabase& db, const std::vector<std::string>& signature, va_list& args) override {
         microseconds time = va_arg(args, microseconds);
         auto path = signature;
References souffle::profile::EventProcessorSingleton::instance(), souffle::profile::ProgramTimepointProcessor::process(), souffle::profile::ProgramTimepointProcessor::ProgramTimepointProcessor(), souffle::profile::EventProcessorSingleton::registerEventProcessor(), and souffle::test::time().
The documentation for this class was generated from the following file:
include/souffle/profile/EventProcessor.h