souffle: souffle::gzfstream::internal::gzfstream Class Reference
souffle::gzfstream::internal::gzfstream Class Reference
#include <gzfstream.h>
Public Member Functions
void close ()
gzfstream ()
gzfstream (const gzfstream &)=delete
gzfstream (const std::string &filename, std::ios_base::openmode mode)
gzfstream (gzfstream &&)=delete
bool is_open ()
void open (const std::string &filename, std::ios_base::openmode mode)
gzfstreambuf * rdbuf () const
~gzfstream () override=default
Protected Attributes
gzfstreambuf buf
Detailed Description
Definition at line 163 of file gzfstream.h.
Constructor & Destructor Documentation
gzfstream() [1/4]
souffle::gzfstream::internal::gzfstream::gzfstream () inline
Definition at line 165 of file gzfstream.h.
{
         if (buf.open(filename, mode) == nullptr) {
             clear(rdstate() | std::ios::badbit);
Referenced by souffle::gzfstream::internal::gzfstreambuf::sync().
gzfstream() [2/4]
souffle::gzfstream::internal::gzfstream::gzfstream (const std::string & filename, std::ios_base::openmode mode) inline
Definition at line 169 of file gzfstream.h.
                    {
         return buf.is_open();
gzfstream() [3/4]
souffle::gzfstream::internal::gzfstream::gzfstream (const gzfstream &) delete
gzfstream() [4/4]
souffle::gzfstream::internal::gzfstream::gzfstream (gzfstream &&) delete
~gzfstream()
souffle::gzfstream::internal::gzfstream::~gzfstream () override default
Member Function Documentation
close()
void souffle::gzfstream::internal::gzfstream::close () inline
Definition at line 190 of file gzfstream.h.
                  : public internal::gzfstream, public std::istream {
 public:
     igzfstream() : internal::gzfstream(), std::istream(&buf) {}
is_open()
bool souffle::gzfstream::internal::gzfstream::is_open () inline
Definition at line 186 of file gzfstream.h.
          :
     mutable gzfstreambuf buf;
open()
void souffle::gzfstream::internal::gzfstream::open (const std::string & filename, std::ios_base::openmode mode) inline
Definition at line 180 of file gzfstream.h.
{
         return &buf;
Referenced by souffle::gzfstream::igzfstream::igzfstream(), souffle::gzfstream::ogzfstream::ogzfstream(), and souffle::gzfstream::internal::gzfstreambuf::sync().
rdbuf()
gzfstreambuf* souffle::gzfstream::internal::gzfstream::rdbuf () const inline
Definition at line 198 of file gzfstream.h.
             : internal::gzfstream(filename, mode), std::istream(&buf) {}
     igzfstream(const igzfstream&) = delete;
Field Documentation
buf
gzfstreambuf souffle::gzfstream::internal::gzfstream::buf mutable protected
Definition at line 203 of file gzfstream.h.
Referenced by souffle::gzfstream::internal::gzfstreambuf::sync().
The documentation for this class was generated from the following file:
include/souffle/io/gzfstream.h