souffle: souffle::ram::ParallelAggregate Class Reference
souffle::ram::ParallelAggregate Class Reference
Parallel Aggregation function applied on some relation.
#include <ParallelAggregate.h>
Public Member Functions
ParallelAggregate * clone () const override
Create a clone (i.e.
ParallelAggregate (Own< Operation > nested, AggregateOp fun, std::string rel, Own< Expression > expression, Own< Condition > condition, int ident)
Public Member Functions inherited from souffle::ram::Aggregate
Aggregate (Own< Operation > nested, AggregateOp fun, std::string rel, Own< Expression > expression, Own< Condition > condition, int ident)
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
Public Member Functions inherited from souffle::ram::RelationOperation
const std::string & getRelation () const
Get search relation.
RelationOperation (std::string rel, int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::TupleOperation
std::vector< const Node * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
void setTupleId (int id)
Set identifier.
TupleOperation (int ident, Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::NestedOperation
void apply (const NodeMapper &map) override
Apply the mapper to all child nodes.
Operation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
NestedOperation (Own< Operation > nested, std::string profileText="")
Public Member Functions inherited from souffle::ram::Node
bool operator!= (const Node &other) const
Inequality check for two RAM nodes.
bool operator== (const Node &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const Node *oldNode, Own< Node > newNode)
Rewrite a child node.
virtual ~Node ()=default
Public Member Functions inherited from souffle::ram::AbstractAggregate
AbstractAggregate (AggregateOp fun, Own< Expression > expr, Own< Condition > cond)
std::vector< const Node * > getChildNodes () const
const Condition & getCondition () const
Get condition.
const Expression & getExpression () const
Get target expression.
AggregateOp getFunction () const
Get aggregation function.
virtual ~AbstractAggregate ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::ram::Aggregate
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::RelationOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::TupleOperation
bool equal (const Node &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::ram::Operation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::ram::AbstractAggregate
bool equal (const Node &node) const
void print (std::ostream &os, int) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::ram::Operation
static void print (const Operation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::ram::RelationOperation
const std::string relation
Search relation.
Protected Attributes inherited from souffle::ram::TupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::ram::NestedOperation
Own< Operation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::ram::AbstractAggregate
Own< Condition > condition
Aggregation tuple condition.
Own< Expression > expression
Aggregation expression.
const AggregateOp function
Aggregation function.
Detailed Description
Parallel Aggregation function applied on some relation.
For example:
PARALLEL t0.0 = COUNT FOR ALL t0 IN A
Applies the function PARALLEL COUNT to determine the number of elements in A.
Definition at line 53 of file ParallelAggregate.h.
Constructor & Destructor Documentation
ParallelAggregate()
souffle::ram::ParallelAggregate::ParallelAggregate (Own< Operation > nested, AggregateOp fun, std::string rel, Own< Expression > expression, Own< Condition > condition, int ident) inline
Definition at line 55 of file ParallelAggregate.h.
{
         return new ParallelAggregate(souffle::clone(&getOperation()), function, relation,
                 souffle::clone(expression), souffle::clone(condition), identifier);
References souffle::clone(), souffle::ram::AbstractAggregate::condition, souffle::ram::AbstractAggregate::expression, souffle::ram::NestedOperation::getOperation(), souffle::ram::TupleOperation::identifier, and souffle::ram::RelationOperation::relation.
Member Function Documentation
clone()
ParallelAggregate* souffle::ram::ParallelAggregate::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::ram::Aggregate.
Definition at line 59 of file ParallelAggregate.h.
          :
     void print(std::ostream& os, int tabpos) const override {
         os << times(" ", tabpos);
References souffle::ram::TupleOperation::getTupleId(), souffle::ram::AbstractAggregate::print(), and souffle::times().
print()
void souffle::ram::ParallelAggregate::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::ram::Aggregate.
Definition at line 65 of file ParallelAggregate.h.
{
             os << " WHERE " << getCondition();
         }
         os << std::endl;
         RelationOperation::print(os, tabpos + 1);
     }
 };
 }  // namespace souffle::ram
References souffle::ram::AbstractAggregate::getCondition().
The documentation for this class was generated from the following file:
ram/ParallelAggregate.h