souffle: souffle::ast::transform::TypeCheckerImpl Class Reference
souffle::ast::transform::TypeCheckerImpl Class Reference
Public Member Functions
void run ()
Analyse types, clause by clause.
TypeCheckerImpl (TranslationUnit &tu)
Private Member Functions
void visitAggregator (const Aggregator &aggregator) override
void visitAtom (const Atom &atom) override
Check if declared types of the relation match deduced types.
void visitBinaryConstraint (const BinaryConstraint &constraint) override
void visitBranchInit (const BranchInit &adt) override
void visitIntrinsicFunctor (const IntrinsicFunctor &fun) override
void visitNegation (const Negation &neg) override
Collect negated atoms.
void visitNilConstant (const NilConstant &constant) override
void visitNumericConstant (const NumericConstant &constant) override
void visitRecordInit (const RecordInit &rec) override
void visitStringConstant (const StringConstant &constant) override
void visitTypeCast (const ast::TypeCast &cast) override
void visitUserDefinedFunctor (const UserDefinedFunctor &fun) override
void visitVariable (const Variable &var) override
Private Member Functions inherited from souffle::ast::Visitor< void >
void operator() (const Node &node, Params... args)
The main entry for the user allowing visitors to be utilized as functions.
virtual void visit (const Node &node, Params... args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of Nodes.
virtual ~Visitor ()=default
A virtual destructor.
LINK (AlgebraicDataType, Type)
LINK (Argument, Node)
LINK (Attribute, Node)
LINK (Clause, Node)
LINK (Component, Node)
LINK (ComponentInit, Node)
LINK (ComponentType, Node)
LINK (Literal, Node)
LINK (Pragma, Node)
LINK (Program, Node)
LINK (RecordType, Type)
LINK (Relation, Node)
LINK (SubsetType, Type)
LINK (Type, Node)
LINK (UnionType, Type)
virtual void visitNode (const Node &, Params...)
The base case for all visitors – if no more specific overload was defined.
Private Attributes
const FunctorAnalysis & functorAnalysis = *tu.getAnalysis<FunctorAnalysis>()
std::unordered_set< const Atom * > negatedAtoms
const PolymorphicObjectsAnalysis & polyAnalysis = *tu.getAnalysis<PolymorphicObjectsAnalysis>()
const Program & program = tu.getProgram()
ErrorReport & report = tu.getErrorReport()
TranslationUnit & tu
const TypeAnalysis & typeAnalysis = *tu.getAnalysis<TypeAnalysis>()
const TypeEnvironment & typeEnv = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment()
Detailed Description
Definition at line 73 of file TypeChecker.cpp.
Constructor & Destructor Documentation
TypeCheckerImpl()
souffle::ast::transform::TypeCheckerImpl::TypeCheckerImpl (TranslationUnit & tu) inline
Definition at line 75 of file TypeChecker.cpp.
 :
     TranslationUnit& tu;
Member Function Documentation
run()
void souffle::ast::transform::TypeCheckerImpl::run () inline
Analyse types, clause by clause.
Definition at line 78 of file TypeChecker.cpp.
        :
     TranslationUnit& tu;
     ErrorReport& report = tu.getErrorReport();
     const TypeAnalysis& typeAnalysis = *tu.getAnalysis<TypeAnalysis>();
     const TypeEnvironment& typeEnv = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment();
visitAggregator()
void souffle::ast::transform::TypeCheckerImpl::visitAggregator (const Aggregator & aggregator) override private
Definition at line 597 of file TypeChecker.cpp.
{
         report.addError("Couldn't assign types to the aggregator", aggregator.getSrcLoc());
     }
 }
 void TypeCheckerImpl::visitNegation(const Negation& neg) {
     negatedAtoms.insert(neg.getAtom());
 }
 }  // namespace souffle::ast::transform
References souffle::ErrorReport::addError(), and report.
visitAtom()
void souffle::ast::transform::TypeCheckerImpl::visitAtom (const Atom & atom) override private
Check if declared types of the relation match deduced types.
Definition at line 289 of file TypeChecker.cpp.
{
         return;  // error in input program
     }
     for (size_t i = 0; i < attributes.size(); ++i) {
         auto& typeName = attributes[i]->getTypeName();
         if (!typeEnv.isType(typeName)) {
             continue;
         }
         auto argTypes = typeAnalysis.getTypes(arguments[i]);
         auto& attributeType = typeEnv.getType(typeName);
         if (argTypes.isAll() || argTypes.empty()) {
             continue;  // This will be reported later.
         }
         // We consider two cases: negated and not negated atoms.
         // Negated atom have to agree in kind, non-negated atom need to follow source/sink rules.
         if (negatedAtoms.count(&atom) == 0) {
             // Attribute and argument type agree if, argument type is a subtype of declared type
             // or is of the appropriate constant type or the (constant) record type.
             bool validAttribute = all_of(argTypes, [&attributeType](const analysis::Type& type) {
                 if (isSubtypeOf(type, attributeType)) return true;
                 if (!isSubtypeOf(attributeType, type)) return false;
                 if (isA<ConstantType>(type)) return true;
                 return isA<analysis::RecordType>(type) && !isA<analysis::SubsetType>(type);
             });
             if (!validAttribute && !Global::config().has("legacy")) {
                 auto primaryDiagnostic =
                         DiagnosticMessage("Atom's argument type is not a subtype of its declared type",
                                 arguments[i]->getSrcLoc());
                 auto declaredTypeInfo =
                         DiagnosticMessage(tfm::format("The argument's declared type is %s", typeName),
                                 attributes[i]->getSrcLoc());
                 report.addDiagnostic(Diagnostic(Diagnostic::Type::ERROR, std::move(primaryDiagnostic),
                         {std::move(declaredTypeInfo)}));
             }
         } else {  // negation case.
             // Declared attribute and deduced type agree if:
             // They are the same type, or
             // They are derived from the same constant type.
             bool validAttribute = all_of(argTypes, [&](const analysis::Type& type) {
                 return type == attributeType || any_of(typeEnv.getConstantTypes(), [&](auto& constantType) {
                     return isSubtypeOf(attributeType, constantType) && isSubtypeOf(type, constantType);
                 });
             });
             if (!validAttribute) {
                 auto primaryDiagnostic =
                         DiagnosticMessage("The kind of atom's argument doesn't match the declared type kind",
                                 arguments[i]->getSrcLoc());
                 auto declaredTypeInfo =
                         DiagnosticMessage(tfm::format("The argument's declared type is %s", typeName),
                                 attributes[i]->getSrcLoc());
                 report.addDiagnostic(Diagnostic(Diagnostic::Type::ERROR, std::move(primaryDiagnostic),
                         {std::move(declaredTypeInfo)}));
             }
         }
     }
 }
 void TypeCheckerImpl::visitVariable(const ast::Variable& var) {
     if (typeAnalysis.getTypes(&var).empty()) {
         report.addError("Unable to deduce type for variable " + var.getName(), var.getSrcLoc());
     }
 }
visitBinaryConstraint()
void souffle::ast::transform::TypeCheckerImpl::visitBinaryConstraint (const BinaryConstraint & constraint) override private
Definition at line 548 of file TypeChecker.cpp.
{
         report.addError("Cannot compare different types", constraint.getSrcLoc());
     } else {
         auto checkTyAttr = [&](Argument const& side) {
             auto opMatchesType = any_of(opTypesAttrs,
                     [&](auto& typeAttr) { return isOfKind(typeAnalysis.getTypes(&side), typeAttr); });
             if (!opMatchesType) {
                 std::stringstream ss;
                 ss << "Constraint requires an operand of type "
                    << join(opTypesAttrs, " or ", [&](auto& out, auto& typeAttr) {
                           switch (typeAttr) {
                               case TypeAttribute::Signed: out << "`number`"; break;
                               case TypeAttribute::Symbol: out << "`symbol`"; break;
                               case TypeAttribute::Unsigned: out << "`unsigned`"; break;
                               case TypeAttribute::Float: out << "`float`"; break;
                               case TypeAttribute::Record: out << "a record"; break;
                               case TypeAttribute::ADT: out << "a sum"; break;
                           }
                       });
                 report.addError(ss.str(), side.getSrcLoc());
             }
         };
         checkTyAttr(*left);
         checkTyAttr(*right);
     }
 }
 void TypeCheckerImpl::visitAggregator(const Aggregator& aggregator) {
     auto op = polyAnalysis.getOverloadedOperator(&aggregator);
     auto aggregatorType = typeAnalysis.getTypes(&aggregator);
visitBranchInit()
void souffle::ast::transform::TypeCheckerImpl::visitBranchInit (const BranchInit & adt) override private
Definition at line 428 of file TypeChecker.cpp.
{
         // Invalid branchInit arity, handled by checkBranchInits.
         return;
     }
     for (size_t i = 0; i < args.size(); ++i) {
         auto argTypes = typeAnalysis.getTypes(args[i]);
         bool correctType = all_of(
                 argTypes, [&](const analysis::Type& t) { return isSubtypeOf(t, *argsDeclaredTypes[i]); });
         if (!correctType) {
             // TODO (darth_tytus): Give better error
             report.addError("Branch argument's type doesn't match its declared type", args[i]->getSrcLoc());
         }
     }
 }
 void TypeCheckerImpl::visitTypeCast(const ast::TypeCast& cast) {
     if (!typeEnv.isType(cast.getType())) {
         report.addError(
                 tfm::format("Type cast to the undeclared type \"%s\"", cast.getType()), cast.getSrcLoc());
         return;
visitIntrinsicFunctor()
void souffle::ast::transform::TypeCheckerImpl::visitIntrinsicFunctor (const IntrinsicFunctor & fun) override private
Definition at line 479 of file TypeChecker.cpp.
{
     // check type of result
     const TypeSet& resultType = typeAnalysis.getTypes(&fun);
     TypeAttribute returnType;
visitNegation()
void souffle::ast::transform::TypeCheckerImpl::visitNegation (const Negation & neg) override private
Collect negated atoms.
Definition at line 610 of file TypeChecker.cpp.
visitNilConstant()
void souffle::ast::transform::TypeCheckerImpl::visitNilConstant (const NilConstant & constant) override private
Definition at line 403 of file TypeChecker.cpp.
{
     TypeSet types = typeAnalysis.getTypes(&rec);
     if (!isOfKind(types, TypeAttribute::Record) || types.size() != 1) {
         report.addError("Ambiguous record", rec.getSrcLoc());
visitNumericConstant()
void souffle::ast::transform::TypeCheckerImpl::visitNumericConstant (const NumericConstant & constant) override private
Definition at line 375 of file TypeChecker.cpp.
{
         case NumericConstant::Type::Int:
             if (!isOfKind(types, TypeAttribute::Signed)) {
                 report.addError("Number constant (type mismatch)", constant.getSrcLoc());
             }
             break;
         case NumericConstant::Type::Uint:
             if (!isOfKind(types, TypeAttribute::Unsigned)) {
                 report.addError("Unsigned constant (type mismatch)", constant.getSrcLoc());
             }
             break;
         case NumericConstant::Type::Float:
             if (!isOfKind(types, TypeAttribute::Float)) {
                 report.addError("Float constant (type mismatch)", constant.getSrcLoc());
             }
             break;
     }
 }
 void TypeCheckerImpl::visitNilConstant(const NilConstant& constant) {
     TypeSet types = typeAnalysis.getTypes(&constant);
     if (!isOfKind(types, TypeAttribute::Record)) {
         report.addError("Nil constant used as a non-record", constant.getSrcLoc());
         return;
visitRecordInit()
void souffle::ast::transform::TypeCheckerImpl::visitRecordInit (const RecordInit & rec) override private
Definition at line 411 of file TypeChecker.cpp.
{
         report.addError("Wrong number of arguments given to record", rec.getSrcLoc());
         return;
     }
 }
 void TypeCheckerImpl::visitBranchInit(const BranchInit& adt) {
     TypeSet types = typeAnalysis.getTypes(&adt);
     if (!isOfKind(types, TypeAttribute::ADT) || types.isAll() || types.size() != 1) {
         report.addError("Ambiguous branch", adt.getSrcLoc());
visitStringConstant()
void souffle::ast::transform::TypeCheckerImpl::visitStringConstant (const StringConstant & constant) override private
Definition at line 368 of file TypeChecker.cpp.
{
     TypeSet types = typeAnalysis.getTypes(&constant);
     // No type could be assigned.
     if (polyAnalysis.hasInvalidType(&constant)) {
References souffle::ErrorReport::addError(), souffle::ast::Node::getSrcLoc(), souffle::ast::analysis::TypeAnalysis::getTypes(), souffle::ast::analysis::PolymorphicObjectsAnalysis::hasInvalidType(), polyAnalysis, report, typeAnalysis, and types.
visitTypeCast()
void souffle::ast::transform::TypeCheckerImpl::visitTypeCast (const ast::TypeCast & cast) override private
Definition at line 458 of file TypeChecker.cpp.
{
         report.addError("Unable to deduce type of the argument (cast)", cast.getSrcLoc());
         return;
     }
     // This should be reported elsewhere
     if (argTypes.isAll() || castTypes.size() != 1 || argTypes.isAll() || argTypes.size() != 1) {
         return;
     }
 }
 void TypeCheckerImpl::visitIntrinsicFunctor(const IntrinsicFunctor& fun) {
     if (!typeAnalysis.hasValidTypeInfo(&fun)) {
         auto args = fun.getArguments();
         if (!isValidFunctorOpArity(fun.getBaseFunctionOp(), args.size())) {
             report.addError("invalid overload (arity mismatch)", fun.getSrcLoc());
References souffle::ErrorReport::addError(), and report.
visitUserDefinedFunctor()
void souffle::ast::transform::TypeCheckerImpl::visitUserDefinedFunctor (const UserDefinedFunctor & fun) override private
Definition at line 492 of file TypeChecker.cpp.
                   {
         report.addError("Undeclared user functor", fun.getSrcLoc());
         return;
     }
     if (!isOfKind(resultType, returnType)) {
         switch (returnType) {
             case TypeAttribute::Signed:
                 report.addError("Non-numeric use for numeric functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Unsigned:
                 report.addError("Non-unsigned use for unsigned functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Float:
                 report.addError("Non-float use for float functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Symbol:
                 report.addError("Non-symbolic use for symbolic functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Record: fatal("Invalid return type");
             case TypeAttribute::ADT: fatal("Invalid return type");
         }
     }
     size_t i = 0;
     for (auto arg : fun.getArguments()) {
         TypeAttribute argType = functorAnalysis.getArgType(&fun, i);
         if (!isOfKind(typeAnalysis.getTypes(arg), argType)) {
             switch (argType) {
                 case TypeAttribute::Signed:
                     report.addError("Non-numeric argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Symbol:
                     report.addError("Non-symbolic argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Unsigned:
                     report.addError("Non-unsigned argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Float:
                     report.addError("Non-float argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Record: fatal("Invalid argument type");
                 case TypeAttribute::ADT: fatal("Invalid argument type");
             }
         }
         ++i;
     }
 }
 void TypeCheckerImpl::visitBinaryConstraint(const BinaryConstraint& constraint) {
     auto op = polyAnalysis.getOverloadedOperator(&constraint);
     auto left = constraint.getLHS();
     auto right = constraint.getRHS();
     auto opTypesAttrs = getBinaryConstraintTypes(op);
visitVariable()
void souffle::ast::transform::TypeCheckerImpl::visitVariable (const Variable & var) override private
Definition at line 362 of file TypeChecker.cpp.
{
     TypeSet types = typeAnalysis.getTypes(&constant);
     if (!isOfKind(types, TypeAttribute::Symbol)) {
         report.addError("Symbol constant (type mismatch)", constant.getSrcLoc());
     }
References souffle::ErrorReport::addError(), souffle::ast::Node::getSrcLoc(), souffle::ast::analysis::TypeAnalysis::getTypes(), souffle::ast::analysis::isOfKind(), report, souffle::Symbol, typeAnalysis, and types.
Field Documentation
functorAnalysis
const FunctorAnalysis& souffle::ast::transform::TypeCheckerImpl::functorAnalysis = *tu.getAnalysis<FunctorAnalysis>() private
Definition at line 90 of file TypeChecker.cpp.
negatedAtoms
std::unordered_set<const Atom*> souffle::ast::transform::TypeCheckerImpl::negatedAtoms private
Definition at line 94 of file TypeChecker.cpp.
polyAnalysis
const PolymorphicObjectsAnalysis& souffle::ast::transform::TypeCheckerImpl::polyAnalysis = *tu.getAnalysis<PolymorphicObjectsAnalysis>() private
Definition at line 91 of file TypeChecker.cpp.
Referenced by visitStringConstant().
program
const Program& souffle::ast::transform::TypeCheckerImpl::program = tu.getProgram() private
Definition at line 92 of file TypeChecker.cpp.
report
ErrorReport& souffle::ast::transform::TypeCheckerImpl::report = tu.getErrorReport() private
Definition at line 87 of file TypeChecker.cpp.
Referenced by visitAggregator(), visitStringConstant(), visitTypeCast(), and visitVariable().
tu
TranslationUnit& souffle::ast::transform::TypeCheckerImpl::tu private
Definition at line 86 of file TypeChecker.cpp.
typeAnalysis
const TypeAnalysis& souffle::ast::transform::TypeCheckerImpl::typeAnalysis = *tu.getAnalysis<TypeAnalysis>() private
Definition at line 88 of file TypeChecker.cpp.
Referenced by visitStringConstant(), and visitVariable().
typeEnv
const TypeEnvironment& souffle::ast::transform::TypeCheckerImpl::typeEnv = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment() private
Definition at line 89 of file TypeChecker.cpp.
The documentation for this class was generated from the following file:
ast/transform/TypeChecker.cpp