souffle: TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent > Class Template Reference
TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent > Class Template Reference
#include <span.h>
Public Types
using const_pointer = const element_type *
using const_reference = const element_type &
using difference_type = std::ptrdiff_t
using element_type = ElementType
using iterator = pointer
using pointer = element_type *
using reference = element_type &
using reverse_iterator = std::reverse_iterator< iterator >
using size_type = std::size_t
template<std::size_t Offset, std::size_t Count = dynamic_extent>
using subspan_return_t = span< ElementType, Count !=dynamic_extent ? Count :(Extent !=dynamic_extent ? Extent - Offset :dynamic_extent)>
using value_type = typename std::remove_cv< ElementType >::type
Public Member Functions
TCB_SPAN_CONSTEXPR11 reference back () const
constexpr iterator begin () const noexcept
constexpr pointer data () const noexcept
constexpr TCB_SPAN_NODISCARD bool empty () const noexcept
constexpr iterator end () const noexcept
template<std::size_t Count>
TCB_SPAN_CONSTEXPR11 span< element_type, Count > first () const
TCB_SPAN_CONSTEXPR11 span< element_type, dynamic_extent > first (size_type count) const
TCB_SPAN_CONSTEXPR11 reference front () const
template<std::size_t Count>
TCB_SPAN_CONSTEXPR11 span< element_type, Count > last () const
TCB_SPAN_CONSTEXPR11 span< element_type, dynamic_extent > last (size_type count) const
TCB_SPAN_CONSTEXPR_ASSIGN span & operator= (const span &other) noexcept=default
TCB_SPAN_CONSTEXPR11 reference operator[] (size_type idx) const
TCB_SPAN_ARRAY_CONSTEXPR reverse_iterator rbegin () const noexcept
TCB_SPAN_ARRAY_CONSTEXPR reverse_iterator rend () const noexcept
constexpr size_type size () const noexcept
constexpr size_type size_bytes () const noexcept
template<std::size_t E = Extent, typename std::enable_if<(E==dynamic_extent||E<=0), int >::type = 0>
constexpr span () noexcept
template<typename Container , std::size_t E = Extent, typename std::enable_if< E==dynamic_extent &&detail::is_container< Container >::value &&detail::is_container_element_type_compatible< const Container &, ElementType >::value, int >::type = 0>
constexpr span (const Container &cont)
constexpr span (const span &other) noexcept=default
template<typename OtherElementType , std::size_t OtherExtent, typename std::enable_if<(Extent==OtherExtent||Extent==dynamic_extent) &&std::is_convertible< OtherElementType(*)[], ElementType(*)[]>::value, int >::type = 0>
constexpr span (const span< OtherElementType, OtherExtent > &other) noexcept
template<std::size_t N, std::size_t E = Extent, typename std::enable_if<(E==dynamic_extent||N==E) &&detail::is_container_element_type_compatible< const std::array< value_type, N > &, ElementType >::value, int >::type = 0>
TCB_SPAN_ARRAY_CONSTEXPR span (const std::array< value_type, N > &arr) noexcept
template<typename Container , std::size_t E = Extent, typename std::enable_if< E==dynamic_extent &&detail::is_container< Container >::value &&detail::is_container_element_type_compatible< Container &, ElementType >::value, int >::type = 0>
constexpr span (Container &cont)
template<std::size_t N, std::size_t E = Extent, typename std::enable_if<(E==dynamic_extent||N==E) &&detail::is_container_element_type_compatible< element_type(&)[N], ElementType >::value, int >::type = 0>
constexpr span (element_type(&arr)[N]) noexcept
TCB_SPAN_CONSTEXPR11 span (pointer first_elem, pointer last_elem)
TCB_SPAN_CONSTEXPR11 span (pointer ptr, size_type count)
template<std::size_t N, std::size_t E = Extent, typename std::enable_if<(E==dynamic_extent||N==E) &&detail::is_container_element_type_compatible< std::array< value_type, N > &, ElementType >::value, int >::type = 0>
TCB_SPAN_ARRAY_CONSTEXPR span (std::array< value_type, N > &arr) noexcept
template<std::size_t Offset, std::size_t Count = dynamic_extent>
TCB_SPAN_CONSTEXPR11 subspan_return_t< Offset, Count > subspan () const
TCB_SPAN_CONSTEXPR11 span< element_type, dynamic_extent > subspan (size_type offset, size_type count=dynamic_extent) const
~span () noexcept=default
Static Public Attributes
static constexpr size_type extent = Extent
Private Types
using storage_type = detail::span_storage< ElementType, Extent >
Private Attributes
storage_type storage_ {}
Detailed Description
template<typename ElementType, std::size_t Extent>
class TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >
Definition at line 163 of file span.h.
Member Typedef Documentation
const_pointer
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::const_pointer = const element_type*
Definition at line 317 of file span.h.
const_reference
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::const_reference = const element_type&
Definition at line 319 of file span.h.
difference_type
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::difference_type = std::ptrdiff_t
Definition at line 315 of file span.h.
element_type
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::element_type = ElementType
Definition at line 312 of file span.h.
iterator
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::iterator = pointer
Definition at line 320 of file span.h.
pointer
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::pointer = element_type*
Definition at line 316 of file span.h.
reference
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::reference = element_type&
Definition at line 318 of file span.h.
reverse_iterator
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 321 of file span.h.
size_type
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size_type = std::size_t
Definition at line 314 of file span.h.
storage_type
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::storage_type = detail::span_storage<ElementType, Extent> private
Definition at line 308 of file span.h.
subspan_return_t
template<typename ElementType , std::size_t Extent> template<std::size_t Offset, std::size_t Count = dynamic_extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::subspan_return_t = span<ElementType, Count != dynamic_extent ? Count : (Extent != dynamic_extent ? Extent - Offset : dynamic_extent)>
Definition at line 434 of file span.h.
value_type
template<typename ElementType , std::size_t Extent> using TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::value_type = typename std::remove_cv<ElementType>::type
Definition at line 313 of file span.h.
Constructor & Destructor Documentation
span() [1/10]
template<typename ElementType , std::size_t Extent> template<std::size_t E = Extent, typename std::enable_if<(E==dynamic_extent||E<=0), int >::type = 0> constexpr TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span () inline constexpr noexcept
Definition at line 329 of file span.h.
     {}
span() [2/10]
template<typename ElementType , std::size_t Extent> TCB_SPAN_CONSTEXPR11 TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span (pointer ptr, size_type count) inline
Definition at line 332 of file span.h.
         : storage_(ptr, count)
     {
         TCB_SPAN_EXPECT(extent == dynamic_extent || count == extent);
     }
References souffle::test::count(), TCB_SPAN_NAMESPACE_NAME::dynamic_extent, TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::extent, and TCB_SPAN_EXPECT.
span() [3/10]
template<typename ElementType , std::size_t Extent> TCB_SPAN_CONSTEXPR11 TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span (pointer first_elem, pointer last_elem) inline
Definition at line 338 of file span.h.
         : storage_(first_elem, last_elem - first_elem)
     {
         TCB_SPAN_EXPECT(extent == dynamic_extent ||
                         last_elem - first_elem ==
                             static_cast<std::ptrdiff_t>(extent));
     }
References TCB_SPAN_NAMESPACE_NAME::dynamic_extent, TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::extent, and TCB_SPAN_EXPECT.
span() [4/10]
template<typename ElementType , std::size_t Extent> template<std::size_t N, std::size_t E = Extent, typename std::enable_if<(E==dynamic_extent||N==E) &&detail::is_container_element_type_compatible< element_type(&)[N], ElementType >::value, int >::type = 0> constexpr TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span (element_type(&) arr[N]) inline constexpr noexcept
Definition at line 352 of file span.h.
                                                     : storage_(arr, N)
     {}
span() [5/10]
template<typename ElementType , std::size_t Extent> template<std::size_t N, std::size_t E = Extent, typename std::enable_if<(E==dynamic_extent||N==E) &&detail::is_container_element_type_compatible< std::array< value_type, N > &, ElementType >::value, int >::type = 0> TCB_SPAN_ARRAY_CONSTEXPR TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span (std::array< value_type, N > & arr) inline noexcept
Definition at line 361 of file span.h.
         : storage_(arr.data(), N)
     {}
span() [6/10]
template<typename ElementType , std::size_t Extent> template<std::size_t N, std::size_t E = Extent, typename std::enable_if<(E==dynamic_extent||N==E) &&detail::is_container_element_type_compatible< const std::array< value_type, N > &, ElementType >::value, int >::type = 0> TCB_SPAN_ARRAY_CONSTEXPR TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span (const std::array< value_type, N > & arr) inline noexcept
Definition at line 371 of file span.h.
         : storage_(arr.data(), N)
     {}
span() [7/10]
template<typename ElementType , std::size_t Extent> template<typename Container , std::size_t E = Extent, typename std::enable_if< E==dynamic_extent &&detail::is_container< Container >::value &&detail::is_container_element_type_compatible< Container &, ElementType >::value, int >::type = 0> constexpr TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span (Container & cont) inline constexpr
Definition at line 382 of file span.h.
         : storage_(detail::data(cont), detail::size(cont))
     {}
span() [8/10]
template<typename ElementType , std::size_t Extent> template<typename Container , std::size_t E = Extent, typename std::enable_if< E==dynamic_extent &&detail::is_container< Container >::value &&detail::is_container_element_type_compatible< const Container &, ElementType >::value, int >::type = 0> constexpr TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span (const Container & cont) inline constexpr
Definition at line 393 of file span.h.
         : storage_(detail::data(cont), detail::size(cont))
     {}
span() [9/10]
template<typename ElementType , std::size_t Extent> constexpr TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span (const span< ElementType, Extent > & other) constexpr default noexcept
span() [10/10]
template<typename ElementType , std::size_t Extent> template<typename OtherElementType , std::size_t OtherExtent, typename std::enable_if<(Extent==OtherExtent||Extent==dynamic_extent) &&std::is_convertible< OtherElementType(*)[], ElementType(*)[]>::value, int >::type = 0> constexpr TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span (const span< OtherElementType, OtherExtent > & other) inline constexpr noexcept
Definition at line 405 of file span.h.
         : storage_(other.data(), other.size())
     {}
~span()
template<typename ElementType , std::size_t Extent> TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::~span () default noexcept
Member Function Documentation
back()
template<typename ElementType , std::size_t Extent> TCB_SPAN_CONSTEXPR11 reference TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::back () const inline
Definition at line 494 of file span.h.
     {
         TCB_SPAN_EXPECT(!empty());
         return *(data() + (size() - 1));
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::empty(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size(), and TCB_SPAN_EXPECT.
begin()
template<typename ElementType , std::size_t Extent> constexpr iterator TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::begin () const inline constexpr noexcept
Definition at line 503 of file span.h.
 { return data(); }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data().
Referenced by TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::rend().
data()
template<typename ElementType , std::size_t Extent> constexpr pointer TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data () const inline constexpr noexcept
Definition at line 500 of file span.h.
 { return storage_.ptr; }
References TCB_SPAN_NAMESPACE_NAME::detail::span_storage< E, S >::ptr, and TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::storage_.
Referenced by TCB_SPAN_NAMESPACE_NAME::as_bytes(), TCB_SPAN_NAMESPACE_NAME::as_writable_bytes(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::back(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::begin(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::end(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::first(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::front(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::last(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::operator[](), and TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::subspan().
empty()
template<typename ElementType , std::size_t Extent> constexpr TCB_SPAN_NODISCARD bool TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::empty () const inline constexpr noexcept
Definition at line 476 of file span.h.
     {
         return size() == 0;
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size().
Referenced by TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::back(), and TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::front().
end()
template<typename ElementType , std::size_t Extent> constexpr iterator TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::end () const inline constexpr noexcept
Definition at line 505 of file span.h.
 { return data() + size(); }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), and TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size().
Referenced by TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::rbegin().
first() [1/2]
template<typename ElementType , std::size_t Extent> template<std::size_t Count> TCB_SPAN_CONSTEXPR11 span<element_type, Count> TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::first () const inline
Definition at line 416 of file span.h.
     {
         TCB_SPAN_EXPECT(Count <= size());
         return {data(), Count};
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size(), and TCB_SPAN_EXPECT.
first() [2/2]
template<typename ElementType , std::size_t Extent> TCB_SPAN_CONSTEXPR11 span<element_type, dynamic_extent> TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::first (size_type count) const inline
Definition at line 446 of file span.h.
     {
         TCB_SPAN_EXPECT(count <= size());
         return {data(), count};
     }
References souffle::test::count(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size(), and TCB_SPAN_EXPECT.
front()
template<typename ElementType , std::size_t Extent> TCB_SPAN_CONSTEXPR11 reference TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::front () const inline
Definition at line 488 of file span.h.
     {
         TCB_SPAN_EXPECT(!empty());
         return *data();
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::empty(), and TCB_SPAN_EXPECT.
last() [1/2]
template<typename ElementType , std::size_t Extent> template<std::size_t Count> TCB_SPAN_CONSTEXPR11 span<element_type, Count> TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::last () const inline
Definition at line 423 of file span.h.
     {
         TCB_SPAN_EXPECT(Count <= size());
         return {data() + (size() - Count), Count};
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size(), and TCB_SPAN_EXPECT.
last() [2/2]
template<typename ElementType , std::size_t Extent> TCB_SPAN_CONSTEXPR11 span<element_type, dynamic_extent> TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::last (size_type count) const inline
Definition at line 453 of file span.h.
     {
         TCB_SPAN_EXPECT(count <= size());
         return {data() + (size() - count), count};
     }
References souffle::test::count(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size(), and TCB_SPAN_EXPECT.
operator=()
template<typename ElementType , std::size_t Extent> TCB_SPAN_CONSTEXPR_ASSIGN span& TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::operator= (const span< ElementType, Extent > & other) default noexcept
operator[]()
template<typename ElementType , std::size_t Extent> TCB_SPAN_CONSTEXPR11 reference TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::operator[] (size_type idx) const inline
Definition at line 482 of file span.h.
     {
         TCB_SPAN_EXPECT(idx < size());
         return *(data() + idx);
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size(), and TCB_SPAN_EXPECT.
rbegin()
template<typename ElementType , std::size_t Extent> TCB_SPAN_ARRAY_CONSTEXPR reverse_iterator TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::rbegin () const inline noexcept
Definition at line 507 of file span.h.
     {
         return reverse_iterator(end());
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::end().
rend()
template<typename ElementType , std::size_t Extent> TCB_SPAN_ARRAY_CONSTEXPR reverse_iterator TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::rend () const inline noexcept
Definition at line 512 of file span.h.
     {
         return reverse_iterator(begin());
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::begin().
size()
template<typename ElementType , std::size_t Extent> constexpr size_type TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size () const inline constexpr noexcept
Definition at line 469 of file span.h.
 { return storage_.size; }
References TCB_SPAN_NAMESPACE_NAME::detail::span_storage< E, S >::size, and TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::storage_.
Referenced by TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::back(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::empty(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::end(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::first(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::last(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::operator[](), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size_bytes(), and TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::subspan().
size_bytes()
template<typename ElementType , std::size_t Extent> constexpr size_type TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size_bytes () const inline constexpr noexcept
Definition at line 471 of file span.h.
     {
         return size() * sizeof(element_type);
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size().
Referenced by TCB_SPAN_NAMESPACE_NAME::as_bytes(), and TCB_SPAN_NAMESPACE_NAME::as_writable_bytes().
subspan() [1/2]
template<typename ElementType , std::size_t Extent> template<std::size_t Offset, std::size_t Count = dynamic_extent> TCB_SPAN_CONSTEXPR11 subspan_return_t<Offset, Count> TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::subspan () const inline
Definition at line 437 of file span.h.
     {
         TCB_SPAN_EXPECT(Offset <= size() &&
                         (Count == dynamic_extent || Offset + Count <= size()));
         return {data() + Offset,
                 Count != dynamic_extent ? Count : size() - Offset};
     }
References TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), TCB_SPAN_NAMESPACE_NAME::dynamic_extent, TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size(), and TCB_SPAN_EXPECT.
subspan() [2/2]
template<typename ElementType , std::size_t Extent> TCB_SPAN_CONSTEXPR11 span<element_type, dynamic_extent> TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::subspan (size_type offset, size_type count = dynamic_extent) const inline
Definition at line 460 of file span.h.
     {
         TCB_SPAN_EXPECT(offset <= size() &&
                         (count == dynamic_extent || offset + count <= size()));
         return {data() + offset,
                 count == dynamic_extent ? size() - offset : count};
     }
References souffle::test::count(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), TCB_SPAN_NAMESPACE_NAME::dynamic_extent, TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size(), and TCB_SPAN_EXPECT.
Field Documentation
extent
template<typename ElementType , std::size_t Extent> constexpr size_type TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::extent = Extent static constexpr
Definition at line 323 of file span.h.
Referenced by TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span().
storage_
template<typename ElementType , std::size_t Extent> storage_type TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::storage_ {} private
Definition at line 518 of file span.h.
Referenced by TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::data(), and TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::size().
The documentation for this class was generated from the following file:
include/souffle/utility/span.h