souffle: souffle::detail::brie Namespace Reference
souffle::detail::brie Namespace Reference
Data Structures
struct default_factory
A templated functor to obtain default values for unspecified elements of sparse array instances.
struct default_merge
A operation to be utilized by the sparse map when merging elements associated to different values.
struct fix_binding
A functor initializing an iterator upon creation to reference the first element exhibiting a given prefix within a given Trie.
struct fix_binding< 0, Dim, Dim >
struct fix_binding< 0, Pos, Dim >
struct fix_first
A functor initializing an iterator upon creation to reference the first element in the associated Trie.
struct fix_first< Dim, Dim >
struct fix_first_nested
struct fix_lower_bound
A functor initializing an iterator upon creation to reference the first element within a given Trie being not less than a given value .
struct fix_upper_bound
A functor initializing an iterator upon creation to reference the first element within a given Trie being greater than a given value .
struct forward_non_output_iterator_traits
struct get_nested_iter_core
A functor extracting a reference to a nested iterator core from an enclosing iterator core.
struct get_nested_iter_core< 0 >
struct identity
A functor representing the identity function.
struct SparseArrayIter
Iterator type for souffle::SparseArray.
class SparseBitMapIter
Iterator type for souffle::SparseArray.
class TrieBase
A base class for the Trie implementation allowing various specializations of the Trie template to inherit common functionality.
class TrieIterator
An iterator over the stored entries.
struct TrieTypes
struct TrieTypes< 1u >
Typedefs
using brie_element_type = RamDomain
Functions
template<typename A , size_t arity>
auto copy (span< A, arity > s)
template<size_t offset, typename A , size_t arity>
auto drop (span< A, arity > s) -> std::enable_if_t< offset<=arity, span< A, arity - offset >>
template<typename C >
auto tail (C &s)
Typedef Documentation
brie_element_type
using souffle::detail::brie::brie_element_type = typedef RamDomain
Definition at line 84 of file Brie.h.
Function Documentation
copy()
template<typename A , size_t arity> auto souffle::detail::brie::copy (span< A, arity > s)
Definition at line 98 of file Brie.h.
{
References souffle::detail::brie::default_factory< T >::operator()().
Referenced by tinyformat::detail::FormatListN< N >::FormatListN(), souffle::ast::NumericConstant::NumericConstant(), souffle::ast::BinaryConstraint::setBaseOperator(), and souffle::ast::IntrinsicFunctor::setFunction().
drop()
template<size_t offset, typename A , size_t arity> auto souffle::detail::brie::drop (span< A, arity > s) -> std::enable_if_t<offset <= arity, span<A, arity - offset>>
Definition at line 105 of file Brie.h.
                 {
tail()
template<typename C > auto souffle::detail::brie::tail (C & s)
Definition at line 110 of file Brie.h.
                 {
References souffle::detail::brie::identity< T >::operator()().
Referenced by souffle::Trie< Dim >::clear(), and souffle::detail::brie::TrieTypes< Dim >::iterator_core::iterator_core().