souffle: souffle::interpreter::test Namespace Reference
souffle::interpreter::test Namespace Reference
Functions
RamDomain evalBinary (FunctorOp functor, RamDomain arg1, RamDomain arg2)
Evaluate a binary operator.
RamDomain evalExpression (Own< Expression > expression)
Function to evaluate a single Expression.
RamDomain evalExpression (Own< Expression > expression, SymbolTable &symTab)
Function to evaluate a single Expression.
RamDomain evalMultiArg (FunctorOp functor, VecOwn< Expression > args)
RamDomain evalMultiArg (FunctorOp functor, VecOwn< Expression > args, SymbolTable &symTab)
RamDomain evalUnary (FunctorOp functor, RamDomain arg1)
Evaluate a single argument expression.
TEST (Basic, Iteration)
TEST (Binary, FloatAdd)
TEST (Binary, FloatDiv)
TEST (Binary, FloatExp)
TEST (Binary, FloatMul)
TEST (Binary, FloatSub)
TEST (Binary, SignedAdd)
TEST (Binary, SignedBinaryAnd)
TEST (Binary, SignedBinaryOr)
TEST (Binary, SignedBinaryXor)
TEST (Binary, SignedDiv)
TEST (Binary, SignedExp)
TEST (Binary, SignedLogicalAnd)
TEST (Binary, SignedLogicalOr)
TEST (Binary, SignedMod)
TEST (Binary, SignedMul)
TEST (Binary, SignedSub)
TEST (Binary, UnsignedAdd)
TEST (Binary, UnsignedBinaryAnd)
TEST (Binary, UnsignedBinaryOr)
TEST (Binary, UnsignedBinaryXor)
TEST (Binary, UnsignedDiv)
TEST (Binary, UnsignedExp)
TEST (Binary, UnsignedLogicalAnd)
TEST (Binary, UnsignedLogicalOr)
TEST (Binary, UnsignedMod)
TEST (Binary, UnsignedMul)
TEST (Binary, UnsignedSub)
TEST (Independence, Iteration)
TEST (IndependentCopying, Iteration)
TEST (IndependentMoving, Iteration)
TEST (IO_load, Float)
TEST (IO_load, MixedTypesLoad)
TEST (IO_load, Signed)
TEST (IO_load, Unsigned)
TEST (IO_store, Float)
TEST (IO_store, FloatSimple)
TEST (IO_store, MixedTypes)
TEST (IO_store, Signed)
TEST (IO_store, SignedChangedDelimiter)
TEST (IO_store, Unsigned)
TEST (MultiArg, FloatMax)
TEST (MultiArg, FloatMin)
TEST (MultiArg, Max)
TEST (MultiArg, Min)
TEST (MultiArg, SymbolMax)
TEST (MultiArg, SymbolMin)
TEST (MultiArg, UnsignedMax)
TEST (MultiArg, UnsignedMin)
TEST (Relation0, Construction)
TEST (Relation0, Iteration)
TEST (Relation1, Construction)
TEST (Reordering, Iteration)
TEST (SignedConstant, ArithmeticEvaluation)
TEST (Unary, BinaryNot)
TEST (Unary, FloatNeg)
TEST (Unary, FloatToSigned)
TEST (Unary, FloatToUnsigned)
TEST (Unary, LogicalNeg)
TEST (Unary, Neg)
TEST (Unary, SignedToFloat)
TEST (Unary, SingedTpUnsigned)
TEST (Unary, UnsignedBinaryNot)
TEST (Unary, UnsignedLogicalNeg)
TEST (Unary, UnsignedToFloat)
TEST (Unary, UnsignedToSigned)
const std::string testInterpreterStore (std::vector< std::string > attribs, std::vector< std::string > attribsTypes, VecOwn< Expression > exprs)
Function Documentation
evalBinary()
RamDomain souffle::interpreter::test::evalBinary (FunctorOp functor, RamDomain arg1, RamDomain arg2)
Evaluate a binary operator.
Definition at line 112 of file ram_arithmetic_test.cpp.
{
     RamDomain num = 42;
     Own<Expression> expression = mk<SignedConstant>(num);
     RamDomain result = evalExpression(std::move(expression));
     EXPECT_EQ(result, num);
Referenced by TEST().
evalExpression() [1/2]
RamDomain souffle::interpreter::test::evalExpression (Own< Expression > expression)
Function to evaluate a single Expression.
Definition at line 89 of file ram_arithmetic_test.cpp.
{
evalExpression() [2/2]
RamDomain souffle::interpreter::test::evalExpression (Own< Expression > expression, SymbolTable & symTab)
Function to evaluate a single Expression.
Definition at line 59 of file ram_arithmetic_test.cpp.
                                          {}, ret);
     return ret.at(0);
 }
 /** Function to evaluate a single Expression. */
 RamDomain evalExpression(Own<Expression> expression) {
     SymbolTable symTab;
     return evalExpression(std::move(expression), symTab);
 }
evalMultiArg() [1/2]
RamDomain souffle::interpreter::test::evalMultiArg (FunctorOp functor, VecOwn< Expression > args)
Definition at line 98 of file ram_arithmetic_test.cpp.
{
     VecOwn<Expression> args;
     args.push_back(mk<SignedConstant>(arg1));
References evalMultiArg().
evalMultiArg() [2/2]
RamDomain souffle::interpreter::test::evalMultiArg (FunctorOp functor, VecOwn< Expression > args, SymbolTable & symTab)
Definition at line 94 of file ram_arithmetic_test.cpp.
{
Referenced by evalMultiArg(), and evalUnary().
evalUnary()
RamDomain souffle::interpreter::test::evalUnary (FunctorOp functor, RamDomain arg1)
Evaluate a single argument expression.
Definition at line 104 of file ram_arithmetic_test.cpp.
{
     VecOwn<Expression> args;
     args.push_back(mk<SignedConstant>(arg1));
     args.push_back(mk<SignedConstant>(arg2));
References evalMultiArg().
Referenced by TEST().
TEST() [1/66]
souffle::interpreter::test::TEST (Basic , Iteration)
Definition at line 94 of file interpreter_relation_test.cpp.
                                                   {"i"}, {"i"}, 0);
     // add some values
     relInt.insert(tuple(&relInt, {1}));
     relInt.insert(tuple(&relInt, {2}));
     relInt.insert(tuple(&relInt, {3}));
     relInt.insert(tuple(&relInt, {4}));
     // Iterate
     souffle::Relation::iterator it = relInt.begin();
     std::size_t count = 0;
     while (it != relInt.end()) {
         // Check the 'deref' doesn't crash
         auto value = (*it)[0];
         (void)value;
         ++it;
         ++count;
     }
     EXPECT_EQ(4, count);
 }
 TEST(Independence, Iteration) {
     // create a table
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
TEST() [2/66]
souffle::interpreter::test::TEST (Binary , FloatAdd)
Definition at line 258 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 + arg2);
     }
 }
 TEST(Binary, SignedSub) {
     FunctorOp functor = FunctorOp::SUB;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [3/66]
souffle::interpreter::test::TEST (Binary , FloatDiv)
Definition at line 388 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         if (arg2 != 0) {
             RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
             EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 / arg2);
         }
     }
 }
 TEST(Binary, SignedExp) {
     FunctorOp functor = FunctorOp::EXP;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [4/66]
souffle::interpreter::test::TEST (Binary , FloatExp)
Definition at line 432 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         auto result = ramBitCast<RamFloat>(evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2)));
         auto expected = static_cast<RamFloat>(std::pow(arg1, arg2));
         EXPECT_TRUE((std::isnan(result) && std::isnan(expected)) || result == expected);
     }
 }
 TEST(Binary, SignedMod) {
     FunctorOp functor = FunctorOp::MOD;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_TRUE, i, and souffle::ramBitCast().
TEST() [5/66]
souffle::interpreter::test::TEST (Binary , FloatMul)
Definition at line 342 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 * arg2);
     }
 }
 TEST(Binary, SignedDiv) {
     FunctorOp functor = FunctorOp::DIV;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [6/66]
souffle::interpreter::test::TEST (Binary , FloatSub)
Definition at line 300 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 - arg2);
     }
 }
 TEST(Binary, SignedMul) {
     FunctorOp functor = FunctorOp::MUL;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [7/66]
souffle::interpreter::test::TEST (Binary , SignedAdd)
Definition at line 230 of file ram_arithmetic_test.cpp.
{
         RamDomain arg1 = vecArg1[i];
         RamDomain arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 + arg2);
     }
 }
 TEST(Binary, UnsignedAdd) {
     FunctorOp functor = FunctorOp::UADD;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [8/66]
souffle::interpreter::test::TEST (Binary , SignedBinaryAnd)
Definition at line 475 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 & arg2);
     }
 }
 TEST(Binary, UnsignedBinaryAnd) {
     FunctorOp functor = FunctorOp::UBAND;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [9/66]
souffle::interpreter::test::TEST (Binary , SignedBinaryOr)
Definition at line 503 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 | arg2);
     }
 }
 TEST(Binary, UnsignedBinaryOr) {
     FunctorOp functor = FunctorOp::UBOR;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [10/66]
souffle::interpreter::test::TEST (Binary , SignedBinaryXor)
Definition at line 531 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 ^ arg2);
     }
 }
 TEST(Binary, UnsignedBinaryXor) {
     FunctorOp functor = FunctorOp::UBXOR;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [11/66]
souffle::interpreter::test::TEST (Binary , SignedDiv)
Definition at line 356 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         if (arg2 != 0) {
             RamDomain result = evalBinary(functor, arg1, arg2);
             EXPECT_EQ(result, arg1 / arg2);
         }
     }
 }
 TEST(Binary, UnsignedDiv) {
     FunctorOp functor = FunctorOp::UDIV;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [12/66]
souffle::interpreter::test::TEST (Binary , SignedExp)
Definition at line 404 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, static_cast<RamDomain>(std::pow(arg1, arg2)));
     }
 }
 TEST(Binary, UnsignedExp) {
     FunctorOp functor = FunctorOp::UEXP;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [13/66]
souffle::interpreter::test::TEST (Binary , SignedLogicalAnd)
Definition at line 559 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 || arg2);
     }
 }
 TEST(Binary, UnsignedLogicalAnd) {
     FunctorOp functor = FunctorOp::ULAND;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [14/66]
souffle::interpreter::test::TEST (Binary , SignedLogicalOr)
Definition at line 587 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 || arg2);
     }
 }
 TEST(Binary, UnsignedLogicalOr) {
     FunctorOp functor = FunctorOp::ULOR;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [15/66]
souffle::interpreter::test::TEST (Binary , SignedMod)
Definition at line 447 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 % arg2);
     }
 }
 TEST(Binary, UnsignedMod) {
     FunctorOp functor = FunctorOp::UMOD;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [16/66]
souffle::interpreter::test::TEST (Binary , SignedMul)
Definition at line 314 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 * arg2);
     }
 }
 TEST(Binary, UnsignedMul) {
     FunctorOp functor = FunctorOp::UMUL;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [17/66]
souffle::interpreter::test::TEST (Binary , SignedSub)
Definition at line 272 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 - arg2);
     }
 }
 TEST(Binary, UnsignedSub) {
     FunctorOp functor = FunctorOp::USUB;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, and i.
TEST() [18/66]
souffle::interpreter::test::TEST (Binary , UnsignedAdd)
Definition at line 244 of file ram_arithmetic_test.cpp.
{
         RamUnsigned arg1 = vecArg1[i];
         RamUnsigned arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 + arg2);
     }
 }
 TEST(Binary, FloatAdd) {
     FunctorOp functor = FunctorOp::FADD;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [19/66]
souffle::interpreter::test::TEST (Binary , UnsignedBinaryAnd)
Definition at line 489 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 & arg2);
     }
 }
 TEST(Binary, SignedBinaryOr) {
     FunctorOp functor = FunctorOp::BOR;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [20/66]
souffle::interpreter::test::TEST (Binary , UnsignedBinaryOr)
Definition at line 517 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 | arg2);
     }
 }
 TEST(Binary, SignedBinaryXor) {
     FunctorOp functor = FunctorOp::BXOR;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [21/66]
souffle::interpreter::test::TEST (Binary , UnsignedBinaryXor)
Definition at line 545 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 ^ arg2);
     }
 }
 TEST(Binary, SignedLogicalAnd) {
     FunctorOp functor = FunctorOp::LAND;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [22/66]
souffle::interpreter::test::TEST (Binary , UnsignedDiv)
Definition at line 372 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         if (arg2 != 0) {
             RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
             EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 / arg2);
         }
     }
 }
 TEST(Binary, FloatDiv) {
     FunctorOp functor = FunctorOp::FDIV;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [23/66]
souffle::interpreter::test::TEST (Binary , UnsignedExp)
Definition at line 418 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), static_cast<RamUnsigned>(std::pow(arg1, arg2)));
     }
 }
 TEST(Binary, FloatExp) {
     FunctorOp functor = FunctorOp::FEXP;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [24/66]
souffle::interpreter::test::TEST (Binary , UnsignedLogicalAnd)
Definition at line 573 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 || arg2);
     }
 }
 TEST(Binary, SignedLogicalOr) {
     FunctorOp functor = FunctorOp::LOR;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [25/66]
souffle::interpreter::test::TEST (Binary , UnsignedLogicalOr)
Definition at line 601 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 || arg2);
     }
 }
 TEST(MultiArg, Max) {
     FunctorOp functor = FunctorOp::MAX;
     VecOwn<Expression> args;
     for (RamDomain i = 0; i <= 50; ++i) {
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [26/66]
souffle::interpreter::test::TEST (Binary , UnsignedMod)
Definition at line 461 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 % arg2);
     }
 }
 TEST(Binary, SignedBinaryAnd) {
     FunctorOp functor = FunctorOp::BAND;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [27/66]
souffle::interpreter::test::TEST (Binary , UnsignedMul)
Definition at line 328 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 * arg2);
     }
 }
 TEST(Binary, FloatMul) {
     FunctorOp functor = FunctorOp::FMUL;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [28/66]
souffle::interpreter::test::TEST (Binary , UnsignedSub)
Definition at line 286 of file ram_arithmetic_test.cpp.
{
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 - arg2);
     }
 }
 TEST(Binary, FloatSub) {
     FunctorOp functor = FunctorOp::FSUB;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
References evalBinary(), EXPECT_EQ, i, and souffle::ramBitCast().
TEST() [29/66]
souffle::interpreter::test::TEST (Independence , Iteration)
Definition at line 121 of file interpreter_relation_test.cpp.
                                                   {"i"}, {"i"}, 0);
     // add a value
     relInt.insert(tuple(&relInt, {1}));
     // Test a iterator returns the correct value
     souffle::Relation::iterator it = relInt.begin();
     EXPECT_EQ(1, (*it)[0]);
     // Copy the iterator and modify the copy
     {
         souffle::Relation::iterator it2(it);
         EXPECT_EQ(1, (*it2)[0]);
         ++it2;
     }
     EXPECT_EQ(1, (*it)[0]);
     // Test that a new iterator is also valid
     souffle::Relation::iterator it3 = relInt.begin();
     EXPECT_EQ(1, (*it3)[0]);
 }
 TEST(IndependentMoving, Iteration) {
     // create a table
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
TEST() [30/66]
souffle::interpreter::test::TEST (IndependentCopying , Iteration)
Definition at line 172 of file interpreter_relation_test.cpp.
                                                   {"i"}, {"i"}, 0);
     // add a value
     relInt.insert(tuple(&relInt, {1}));
     souffle::Relation::iterator it = relInt.begin();
     EXPECT_EQ(1, (*it)[0]);
     // Make a new iterator, copy it to the first iterator, then let the new iterator go out of scope
     {
         souffle::Relation::iterator it2(relInt.begin());
         EXPECT_EQ(1, (*it2)[0]);
         it = it2;
     }
     EXPECT_EQ(1, (*it)[0]);
 }
 TEST(Reordering, Iteration) {
     // create a relation, with a non-default ordering.
     SymbolTable symbolTable;
     // create an index of order {0, 2, 1}
TEST() [31/66]
souffle::interpreter::test::TEST (IndependentMoving , Iteration)
Definition at line 149 of file interpreter_relation_test.cpp.
                                                   {"i"}, {"i"}, 0);
     // add a value
     relInt.insert(tuple(&relInt, {1}));
     souffle::Relation::iterator it = relInt.begin();
     EXPECT_EQ(1, (*it)[0]);
     // Make a new iterator, move it to the first iterator, then let the new iterator go out of scope
     {
         souffle::Relation::iterator it2(relInt.begin());
         EXPECT_EQ(1, (*it2)[0]);
         it = std::move(it2);
     }
     EXPECT_EQ(1, (*it)[0]);
 }
 TEST(IndependentCopying, Iteration) {
     // create a table
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
TEST() [32/66]
souffle::interpreter::test::TEST (IO_load , Float)
Definition at line 449 of file ram_relation_test.cpp.
                                    {"a", "b"};
     std::vector<std::string> attribsTypes = {"f", "f"};
     Own<ram::Relation> myrel =
             mk<ram::Relation>("test", 2, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     Own<ram::Statement> main =
             mk<ram::Sequence>(mk<ram::IO>("test", readIoDirs), mk<ram::IO>("test", writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<Engine> interpreter = mk<Engine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 0.5 0.5
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
 TEST(IO_load, Unsigned) {
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("6 6");
     std::cin.rdbuf(testInput.rdbuf());
TEST() [33/66]
souffle::interpreter::test::TEST (IO_load , MixedTypesLoad)
Definition at line 573 of file ram_relation_test.cpp.
                                    {"l", "u", "b", "a"};
     std::vector<std::string> attribsTypes = {"s", "i", "u", "f"};
     Own<ram::Relation> myrel =
             mk<ram::Relation>("test", 4, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     Own<ram::Statement> main =
             mk<ram::Sequence>(mk<ram::IO>("test", readIoDirs), mk<ram::IO>("test", writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<Engine> interpreter = mk<Engine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 meow    -3  3   0.5
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
 }  // namespace souffle::interpreter::test
TEST() [34/66]
souffle::interpreter::test::TEST (IO_load , Signed)
Definition at line 387 of file ram_relation_test.cpp.
                                    {"a", "b"};
     std::vector<std::string> attribsTypes = {"i", "i"};
     Own<ram::Relation> myrel =
             mk<ram::Relation>("test", 2, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     Own<ram::Statement> main =
             mk<ram::Sequence>(mk<ram::IO>("test", readIoDirs), mk<ram::IO>("test", writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<Engine> interpreter = mk<Engine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 5   3
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
 TEST(IO_load, Float) {
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("0.5   0.5");
     std::cin.rdbuf(testInput.rdbuf());
TEST() [35/66]
souffle::interpreter::test::TEST (IO_load , Unsigned)
Definition at line 511 of file ram_relation_test.cpp.
                                    {"a", "b"};
     std::vector<std::string> attribsTypes = {"u", "u"};
     Own<ram::Relation> myrel =
             mk<ram::Relation>("test", 2, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     Own<ram::Statement> main =
             mk<ram::Sequence>(mk<ram::IO>("test", readIoDirs), mk<ram::IO>("test", writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<Engine> interpreter = mk<Engine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 6   6
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
 TEST(IO_load, MixedTypesLoad) {
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("meow  -3  3   0.5");
     std::cin.rdbuf(testInput.rdbuf());
TEST() [36/66]
souffle::interpreter::test::TEST (IO_store , Float)
Definition at line 165 of file ram_relation_test.cpp.
                     : randomNumbers) {
         exprs.push_back(mk<SignedConstant>(ramBitCast(f)));
     }
     std::stringstream expected;
     expected << std::setprecision(std::numeric_limits<RamFloat>::max_digits10);
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << "\t" << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected.str(), result);
 }
 TEST(IO_store, Unsigned) {
     std::vector<RamUnsigned> randomNumbers = testutil::generateRandomVector<RamUnsigned>(RANDOM_TESTS);
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
TEST() [37/66]
souffle::interpreter::test::TEST (IO_store , FloatSimple)
Definition at line 110 of file ram_relation_test.cpp.
{
     std::vector<RamDomain> randomNumbers = testutil::generateRandomVector<RamDomain>(RANDOM_TESTS);
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
TEST() [38/66]
souffle::interpreter::test::TEST (IO_store , MixedTypes)
Definition at line 317 of file ram_relation_test.cpp.
                                      {"i", "u", "f", "f", "s"};
     Own<ram::Relation> myrel =
             mk<ram::Relation>("test", 5, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> dirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> ioDirs = std::map<std::string, std::string>(dirs);
     SymbolTable symbolTable;
     ErrorReport errReport;
     DebugReport debugReport;
     VecOwn<Expression> exprs;
     RamFloat floatValue = 27.75;
     exprs.push_back(mk<SignedConstant>(3));
     exprs.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamUnsigned>(27))));
     exprs.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamFloat>(floatValue))));
     exprs.push_back(mk<SignedConstant>(ramBitCast(static_cast<RamFloat>(floatValue))));
     exprs.push_back(mk<SignedConstant>(symbolTable.lookup("meow")));
     Own<ram::Statement> main = mk<ram::Sequence>(
             mk<ram::Query>(mk<ram::Project>("test", std::move(exprs))), mk<ram::IO>("test", ioDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     TranslationUnit translationUnit(std::move(prog), symbolTable, errReport, debugReport);
     // configure and execute interpreter
     Own<Engine> interpreter = mk<Engine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::stringstream expected;
     expected << std::setprecision(std::numeric_limits<RamFloat>::max_digits10);
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << 3 << "\t" << 27 << "\t" << floatValue << "\t" << floatValue << "\t"
              << "meow"
              << "\n"
              << "==============="
              << "\n";
     EXPECT_EQ(expected.str(), sout.str());
 }
 TEST(IO_load, Signed) {
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("5 3");
     std::cin.rdbuf(testInput.rdbuf());
TEST() [39/66]
souffle::interpreter::test::TEST (IO_store , Signed)
Definition at line 129 of file ram_relation_test.cpp.
                      : randomNumbers) {
         exprs.push_back(mk<SignedConstant>(i));
     }
     std::stringstream expected;
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << "\t" << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected.str(), result);
 }
 TEST(IO_store, Float) {
     std::vector<RamFloat> randomNumbers = testutil::generateRandomVector<RamFloat>(RANDOM_TESTS);
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
TEST() [40/66]
souffle::interpreter::test::TEST (IO_store , SignedChangedDelimiter)
Definition at line 240 of file ram_relation_test.cpp.
{
         attribs[i].append(std::to_string(i));
     }
     std::vector<std::string> attribsTypes(RANDOM_TESTS, "i");
     Own<ram::Relation> myrel =
             mk<ram::Relation>("test", RANDOM_TESTS, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> dirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"delimiter", delimiter}, {"types", types.dump()}};
     std::map<std::string, std::string> ioDirs = std::map<std::string, std::string>(dirs);
     VecOwn<Expression> exprs;
     for (RamDomain i : randomNumbers) {
         exprs.push_back(mk<SignedConstant>(i));
     }
     Own<ram::Statement> main = mk<ram::Sequence>(
             mk<ram::Query>(mk<ram::Project>("test", std::move(exprs))), mk<ram::IO>("test", ioDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<Engine> interpreter = mk<Engine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::stringstream expected;
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << delimiter << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     EXPECT_EQ(expected.str(), sout.str());
 }
 TEST(IO_store, MixedTypes) {
     Global::config().set("jobs", "1");
     VecOwn<ram::Relation> rels;
TEST() [41/66]
souffle::interpreter::test::TEST (IO_store , Unsigned)
Definition at line 203 of file ram_relation_test.cpp.
                        : randomNumbers) {
         exprs.push_back(mk<SignedConstant>(ramBitCast(u)));
     }
     std::stringstream expected;
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << "\t" << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected.str(), result);
 }
 // Test (store) with different delimiter
 TEST(IO_store, SignedChangedDelimiter) {
     std::vector<RamDomain> randomNumbers = testutil::generateRandomVector<RamDomain>(RANDOM_TESTS);
     const std::string delimiter{", "};
TEST() [42/66]
souffle::interpreter::test::TEST (MultiArg , FloatMax)
Definition at line 641 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::SMAX;
     VecOwn<Expression> args;
     SymbolTable symTab;
TEST() [43/66]
souffle::interpreter::test::TEST (MultiArg , FloatMin)
Definition at line 695 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::SMIN;
     VecOwn<Expression> args;
     SymbolTable symTab;
TEST() [44/66]
souffle::interpreter::test::TEST (MultiArg , Max)
Definition at line 615 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::UMAX;
     VecOwn<Expression> args;
     for (RamUnsigned i = 0; i <= 100; ++i) {
TEST() [45/66]
souffle::interpreter::test::TEST (MultiArg , Min)
Definition at line 669 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::UMIN;
     VecOwn<Expression> args;
     for (RamUnsigned i = 0; i <= 100; ++i) {
TEST() [46/66]
souffle::interpreter::test::TEST (MultiArg , SymbolMax)
Definition at line 654 of file ram_arithmetic_test.cpp.
{
         args.push_back(mk<SignedConstant>(symTab.lookup(std::to_string(i))));
     }
     auto&& result = symTab.resolve(evalMultiArg(functor, std::move(args), symTab));
     EXPECT_EQ(result, "99");
 }
 TEST(MultiArg, Min) {
     FunctorOp functor = FunctorOp::MIN;
     VecOwn<Expression> args;
     for (RamDomain i = 0; i <= 50; ++i) {
References i, and souffle::SymbolTable::lookup().
TEST() [47/66]
souffle::interpreter::test::TEST (MultiArg , SymbolMin)
Definition at line 708 of file ram_arithmetic_test.cpp.
{
         args.push_back(mk<SignedConstant>(symTab.lookup(std::to_string(i))));
     }
     auto&& result = symTab.resolve(evalMultiArg(functor, std::move(args), symTab));
     EXPECT_EQ(result, "-1");
 }
 }  // namespace souffle::interpreter::test
References i, and souffle::SymbolTable::lookup().
TEST() [48/66]
souffle::interpreter::test::TEST (MultiArg , UnsignedMax)
Definition at line 628 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::FMAX;
     VecOwn<Expression> args;
     for (RamDomain i = -100; i <= 100; ++i) {
TEST() [49/66]
souffle::interpreter::test::TEST (MultiArg , UnsignedMin)
Definition at line 682 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::FMIN;
     VecOwn<Expression> args;
     for (RamDomain i = -100; i <= 100; ++i) {
TEST() [50/66]
souffle::interpreter::test::TEST (Relation0 , Construction)
Definition at line 38 of file interpreter_relation_test.cpp.
{
     // create a nullary relation
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(0);
TEST() [51/66]
souffle::interpreter::test::TEST (Relation0 , Iteration)
Definition at line 54 of file interpreter_relation_test.cpp.
{
     // create a single attribute relation
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
TEST() [52/66]
souffle::interpreter::test::TEST (Relation1 , Construction)
Definition at line 73 of file interpreter_relation_test.cpp.
                                                   {"i"}, {"i"}, 0);
     tuple d1(&relInt, {1});
     // add some values
     EXPECT_EQ(0, rel.size());
     relInt.insert(d1);
     EXPECT_EQ(1, rel.size());
     relInt.insert(tuple(&relInt, {2}));
     EXPECT_EQ(2, rel.size());
     relInt.insert(tuple(&relInt, {3}));
     EXPECT_EQ(3, rel.size());
     relInt.insert(tuple(&relInt, {4}));
     EXPECT_EQ(4, rel.size());
 }
 TEST(Basic, Iteration) {
     // create a relation
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
TEST() [53/66]
souffle::interpreter::test::TEST (Reordering , Iteration)
Definition at line 195 of file interpreter_relation_test.cpp.
                                     {0, 1, 2};
     rel.insert(tuple);
     // Scan should give undecoded tuple.
     {
         const auto& t = *(rel.scan().begin());
         EXPECT_EQ((souffle::Tuple<RamDomain, 3>{0, 2, 1}), t);
     }
     // For-each should give decoded tuple.
     {
         auto t = rel.begin();
         EXPECT_EQ(0, (*t)[0]);
         EXPECT_EQ(1, (*t)[1]);
         EXPECT_EQ(2, (*t)[2]);
     }
     RelInterface relInt(rel, symbolTable, "test", {"i", "i", "i"}, {"i", "i", "i"}, 3);
     // ProgInterface should give decoded tuple.
     {
         const auto it = relInt.begin();
         EXPECT_EQ(0, (*it)[0]);
         EXPECT_EQ(1, (*it)[1]);
         EXPECT_EQ(2, (*it)[2]);
     }
 }
 }  // namespace souffle::interpreter::test
TEST() [54/66]
souffle::interpreter::test::TEST (SignedConstant , ArithmeticEvaluation)
Definition at line 120 of file ram_arithmetic_test.cpp.
                  {
     for (RamDomain randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         EXPECT_EQ(evalUnary(FunctorOp::NEG, randomNumber), -randomNumber);
     }
 }
References evalUnary(), EXPECT_EQ, souffle::NEG, and TESTS_PER_OPERATION.
TEST() [55/66]
souffle::interpreter::test::TEST (Unary , BinaryNot)
Definition at line 142 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::UBNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
TEST() [56/66]
souffle::interpreter::test::TEST (Unary , FloatNeg)
Definition at line 133 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::BNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         EXPECT_EQ(evalUnary(functor, randomNumber), ~randomNumber);
TEST() [57/66]
souffle::interpreter::test::TEST (Unary , FloatToSigned)
Definition at line 203 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::U2F;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
TEST() [58/66]
souffle::interpreter::test::TEST (Unary , FloatToUnsigned)
Definition at line 221 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::ADD;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
TEST() [59/66]
souffle::interpreter::test::TEST (Unary , LogicalNeg)
Definition at line 159 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::ULNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
TEST() [60/66]
souffle::interpreter::test::TEST (Unary , Neg)
Definition at line 127 of file ram_arithmetic_test.cpp.
                       {
     FunctorOp functor = FunctorOp::FNEG;
     for (auto randomNumber : testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION)) {
         auto result = evalUnary(functor, ramBitCast(randomNumber));
References evalUnary(), EXPECT_EQ, souffle::FNEG, souffle::ramBitCast(), and TESTS_PER_OPERATION.
TEST() [61/66]
souffle::interpreter::test::TEST (Unary , SignedToFloat)
Definition at line 194 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::F2I;
     for (auto randomNumber : testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
TEST() [62/66]
souffle::interpreter::test::TEST (Unary , SingedTpUnsigned)
Definition at line 176 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::U2I;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
TEST() [63/66]
souffle::interpreter::test::TEST (Unary , UnsignedBinaryNot)
Definition at line 150 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::LNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         EXPECT_EQ(evalUnary(functor, randomNumber), !randomNumber);
TEST() [64/66]
souffle::interpreter::test::TEST (Unary , UnsignedLogicalNeg)
Definition at line 167 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::I2U;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, randomNumber);
TEST() [65/66]
souffle::interpreter::test::TEST (Unary , UnsignedToFloat)
Definition at line 212 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::F2U;
     for (auto randomNumber : testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
TEST() [66/66]
souffle::interpreter::test::TEST (Unary , UnsignedToSigned)
Definition at line 185 of file ram_arithmetic_test.cpp.
{
     FunctorOp functor = FunctorOp::I2F;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
testInterpreterStore()
const std::string souffle::interpreter::test::testInterpreterStore (std::vector< std::string > attribs, std::vector< std::string > attribsTypes, VecOwn< Expression > exprs)
Definition at line 64 of file ram_relation_test.cpp.
                            {{"relation",
             Json::object{{"arity", static_cast<long long>(arity)}, {"auxArity", static_cast<long long>(0)},
                     {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> dirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> ioDirs = std::map<std::string, std::string>(dirs);
     Own<ram::Statement> main = mk<ram::Sequence>(
             mk<ram::Query>(mk<ram::Project>("test", std::move(exprs))), mk<ram::IO>("test", ioDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, Own<Statement>> subs;
     Own<ram::Program> prog = mk<Program>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     TranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     Own<Engine> interpreter = mk<Engine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     return sout.str();
 }
 TEST(IO_store, FloatSimple) {
     std::vector<std::string> attribs = {"a", "b"};
     std::vector<std::string> attribsTypes = {"f", "f"};
     VecOwn<Expression> exprs;