souffle: std Namespace Reference
std Namespace Reference
Data Structures
struct hash< tuple< A, B > >
struct iterator_traits< SparseArrayIter< A > >
struct iterator_traits< SparseBitMapIter< A > >
struct iterator_traits< TrieIterator< A, IterCore > >
Typedefs
using type = ElementType
Functions
template<typename T , size_t E>
ostream & operator<< (ostream &out, const array< T, E > &v)
Enables the generic printing of arrays assuming their element types are printable.
template<typename K , typename T , typename C , typename A >
ostream & operator<< (ostream &out, const map< K, T, C, A > &m)
Enables the generic printing of maps assuming their element types are printable.
template<typename K , typename C , typename A >
ostream & operator<< (ostream &out, const multiset< K, C, A > &s)
Enables the generic printing of multisets assuming their element types are printable.
template<typename A , typename B >
ostream & operator<< (ostream &out, const pair< A, B > &p)
Introduces support for printing pairs as long as their components can be printed.
template<typename K , typename C , typename A >
ostream & operator<< (ostream &out, const set< K, C, A > &s)
Enables the generic printing of sets assuming their element types are printable.
template<typename T , size_t E>
ostream & operator<< (ostream &out, const souffle::span< T, E > &v)
Enables the generic printing of spans assuming their element types are printable.
template<typename T , typename A >
ostream & operator<< (ostream &out, const vector< T, A > &v)
Enables the generic printing of vectors assuming their element types are printable.
template<typename A , typename B >
std::ostream & operator<< (std::ostream &out, const tuple< A, B > &t)
Variables
TCB_SPAN_TUPLE_SIZE_KIND Extent {}
Typedef Documentation
type
using std::type = typedef ElementType
Definition at line 640 of file span.h.
Function Documentation
operator<<() [1/8]
template<typename T , size_t E> ostream& std::operator<< (ostream & out, const array< T, E > & v)
Enables the generic printing of arrays assuming their element types are printable.
Definition at line 233 of file StreamUtil.h.
{
     return out << "[" << souffle::join(v) << "]";
 }
References souffle::join().
operator<<() [2/8]
template<typename K , typename T , typename C , typename A > ostream& std::operator<< (ostream & out, const map< K, T, C, A > & m)
Enables the generic printing of maps assuming their element types are printable.
Definition at line 286 of file StreamUtil.h.
{
     return out << "{" << souffle::join(m, ",", [](ostream& out, const pair<K, T>& cur) {
         out << cur.first << "->" << cur.second;
     }) << "}";
 }
References souffle::join(), and m.
operator<<() [3/8]
template<typename K , typename C , typename A > ostream& std::operator<< (ostream & out, const multiset< K, C, A > & s)
Enables the generic printing of multisets assuming their element types are printable.
Definition at line 277 of file StreamUtil.h.
{
     return out << "{" << souffle::join(s) << "}";
 }
References souffle::join().
operator<<() [4/8]
template<typename A , typename B > ostream& std::operator<< (ostream & out, const pair< A, B > & p)
Introduces support for printing pairs as long as their components can be printed.
Definition at line 241 of file StreamUtil.h.
{
     return out << "(" << p.first << "," << p.second << ")";
 }
References p.
operator<<() [5/8]
template<typename K , typename C , typename A > ostream& std::operator<< (ostream & out, const set< K, C, A > & s)
Enables the generic printing of sets assuming their element types are printable.
Definition at line 268 of file StreamUtil.h.
{
     return out << "{" << souffle::join(s) << "}";
 }
References souffle::join().
operator<<() [6/8]
template<typename T , size_t E> ostream& std::operator<< (ostream & out, const souffle::span< T, E > & v)
Enables the generic printing of spans assuming their element types are printable.
Definition at line 259 of file StreamUtil.h.
{
     return out << "[" << souffle::join(v) << "]";
 }
References souffle::join().
operator<<() [7/8]
template<typename T , typename A > ostream& std::operator<< (ostream & out, const vector< T, A > & v)
Enables the generic printing of vectors assuming their element types are printable.
Definition at line 250 of file StreamUtil.h.
{
     return out << "[" << souffle::join(v) << "]";
 }
References souffle::join().
operator<<() [8/8]
template<typename A , typename B > std::ostream & std::operator<< (std::ostream & out, const tuple< A, B > & t)
Definition at line 53 of file btree_multiset_test.cpp.
                {
Variable Documentation
Extent
TCB_SPAN_TUPLE_SIZE_KIND std::Extent {}
Definition at line 628 of file span.h.