souffle: souffle::ram::test Namespace Reference
souffle::ram::test Namespace Reference
Functions
TEST (AutoIncrement, CloneAndEquals)
TEST (Clear, CloneAndEquals)
TEST (Conjunction, CloneAndEquals)
TEST (Constraint, CloneAndEquals)
TEST (DebugInfo, CloneAndEquals)
TEST (EmptinessCheck, CloneAndEquals)
TEST (ExistenceCheck, CloneAndEquals)
TEST (Exit, CloneAndEquals)
TEST (Extend, CloneAndEquals)
TEST (False, CloneAndEquals)
TEST (IntrinsicOperator, CloneAndEquals)
TEST (IO1, CloneAndEquals)
TEST (LogRelationTimer, CloneAndEquals)
TEST (LogSize, CloneAndEquals)
TEST (LogTimer, CloneAndEquals)
TEST (Loop, CloneAndEquals)
TEST (Negation, CloneAndEquals)
TEST (PackRecord, CloneAndEquals)
TEST (Parallel, CloneAndEquals)
TEST (Query, CloneAndEquals)
TEST (RamAggregate, CloneAndEquals)
TEST (RamBreak, CloneAndEquals)
TEST (RamChoice, CloneAndEquals)
TEST (RamFilter, CloneAndEquals)
TEST (RamIndexAggregate, CloneAndEquals)
TEST (RamIndexChoice, CloneAndEquals)
TEST (RamIndexScan, CloneAndEquals)
TEST (RamiParallelIndexChoice, CloneAndEquals)
TEST (RamParallelChoice, CloneAndEquals)
TEST (RamParallelIndexScan, CloneAndEquals)
TEST (RamParallelScan, CloneAndEquals)
TEST (RamProject, CloneAndEquals)
TEST (RamProvenanceExistCheck, CloneAndEquals)
TEST (RamScan, CloneAndEquals)
TEST (RamSubrountineArgument, CloneAndEquals)
TEST (RamSubroutineReturn, CloneAndEquals)
TEST (RamUnpackedRecord, CloneAndEquals)
TEST (randomConversions, RamFloat)
TEST (randomConversions, RamSigned)
TEST (randomConversions, RamUnsigned)
TEST (Relation, CloneAndEquals)
TEST (Sequence, CloneAndEquals)
TEST (SignedConstant, CloneAndEquals)
TEST (Swap, CloneAndEquals)
TEST (True, CloneAndEquals)
TEST (TupleElement, CloneAndEquals)
TEST (UndefValue, CloneAndEquals)
TEST (UserDefinedOperator, CloneAndEquals)
Function Documentation
TEST() [1/48]
souffle::ram::test::TEST (AutoIncrement , CloneAndEquals)
Definition at line 136 of file ram_expression_equal_clone_test.cpp.
{
     UndefValue a;
     UndefValue b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     UndefValue* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
References b, souffle::ram::UndefValue::clone(), EXPECT_EQ, and EXPECT_NE.
TEST() [2/48]
souffle::ram::test::TEST (Clear , CloneAndEquals)
Definition at line 93 of file ram_statement_equal_clone_test.cpp.
{
     // MERGE B WITH A
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Extend a("B", "A");
     Extend b("B", "A");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Extend* c = a.clone();
     EXPECT_EQ(a, *c);
TEST() [3/48]
souffle::ram::test::TEST (Conjunction , CloneAndEquals)
Definition at line 78 of file ram_condition_equal_clone_test.cpp.
{
     auto a = mk<True>();
     auto neg_a = mk<Negation>(std::move(a));
     auto b = mk<True>();
     auto neg_b = mk<Negation>(std::move(b));
     EXPECT_EQ(*neg_a, *neg_b);
     EXPECT_NE(neg_a, neg_b);
     auto c = mk<False>();
     auto neg_neg_c = mk<Negation>(mk<Negation>(std::move(c)));
     auto d = mk<False>();
TEST() [4/48]
souffle::ram::test::TEST (Constraint , CloneAndEquals)
Definition at line 132 of file ram_condition_equal_clone_test.cpp.
{
     // N(1) in relation N(x:number)
     Relation N("N", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     VecOwn<Expression> tuple_a;
     tuple_a.emplace_back(new SignedConstant(1));
     ExistenceCheck a("N", std::move(tuple_a));
     VecOwn<Expression> tuple_b;
     tuple_b.emplace_back(new SignedConstant(1));
     ExistenceCheck b("N", std::move(tuple_b));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
TEST() [5/48]
souffle::ram::test::TEST (DebugInfo , CloneAndEquals)
Definition at line 371 of file ram_statement_equal_clone_test.cpp.
                                           :- \n   edge(x,y,_,@level_num_0).\nin file /edge.dl [17:1-17:26];");
     VecOwn<Expression> b_project_list;
     b_project_list.emplace_back(new TupleElement(0, 0));
     b_project_list.emplace_back(new TupleElement(0, 1));
     b_project_list.emplace_back(new SignedConstant(1));
     VecOwn<Expression> b_project_add;
     b_project_add.emplace_back(new TupleElement(0, 3));
     b_project_add.emplace_back(new SignedConstant(1));
     b_project_list.emplace_back(new IntrinsicOperator(FunctorOp::ADD, std::move(b_project_add)));
     auto b_project = mk<Project>("path", std::move(b_project_list));
     VecOwn<Expression> b_filter1_list;
     b_filter1_list.emplace_back(new TupleElement(0, 0));
     b_filter1_list.emplace_back(new TupleElement(0, 1));
     b_filter1_list.emplace_back(new UndefValue);
     b_filter1_list.emplace_back(new UndefValue);
     auto b_existence_check1 = mk<ExistenceCheck>("path", std::move(b_filter1_list));
     auto b_cond1 = mk<Negation>(std::move(b_existence_check1));
     auto b_filter1 = mk<Filter>(std::move(b_cond1), std::move(b_project), "");
     auto b_cond2 = mk<Negation>(mk<EmptinessCheck>("edge"));
     auto b_filter2 = mk<Filter>(std::move(b_cond2), std::move(b_filter1), "");
     auto b_scan = mk<Scan>("edge", 0, std::move(b_filter2), "");
     auto b_query = mk<Query>(std::move(b_scan));
     DebugInfo b(std::move(b_query),
             "path(x,y,1,(@level_num_0+1)) :- \n   edge(x,y,_,@level_num_0).\nin file /edge.dl [17:1-17:26];");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     DebugInfo* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
 TEST(LogSize, CloneAndEquals) {
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     LogSize a("A", "Log message");
     LogSize b("A", "Log message");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     LogSize* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
TEST() [6/48]
souffle::ram::test::TEST (EmptinessCheck , CloneAndEquals)
Definition at line 252 of file ram_condition_equal_clone_test.cpp.
TEST() [7/48]
souffle::ram::test::TEST (ExistenceCheck , CloneAndEquals)
Definition at line 166 of file ram_condition_equal_clone_test.cpp.
                                 {"x", "y"}, {"i", "i"}, RelationRepresentation::BRIE);
     VecOwn<Expression> tuple_d;
     tuple_d.emplace_back(new SignedConstant(1));
     tuple_d.emplace_back(new SignedConstant(2));
     ExistenceCheck d("edge", std::move(tuple_d));
     VecOwn<Expression> tuple_e;
     tuple_e.emplace_back(new SignedConstant(1));
     tuple_e.emplace_back(new SignedConstant(2));
     ExistenceCheck e("edge", std::move(tuple_e));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     ExistenceCheck* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_EQ(e, *f);
     EXPECT_NE(&d, f);
     EXPECT_NE(&e, f);
     delete f;
 }
 TEST(RamProvenanceExistCheck, CloneAndEquals) {
     Relation N("N", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     VecOwn<Expression> tuple_a;
     tuple_a.emplace_back(new SignedConstant(1));
     ExistenceCheck a("N", std::move(tuple_a));
     VecOwn<Expression> tuple_b;
     tuple_b.emplace_back(new SignedConstant(1));
     ExistenceCheck b("N", std::move(tuple_b));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
TEST() [8/48]
souffle::ram::test::TEST (Exit , CloneAndEquals)
Definition at line 317 of file ram_statement_equal_clone_test.cpp.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     /*
      * START_TIMER ON A "file.dl [8:1-8:8]"
      *   IO A()
      * END_TIMER
      * */
     std::map<std::string, std::string> a_IODir;
     std::map<std::string, std::string> b_IODir;
     LogRelationTimer a(mk<IO>("A", std::move(a_IODir)), "file.dl [8:1-8:8]", "A");
     LogRelationTimer b(mk<IO>("A", std::move(b_IODir)), "file.dl [8:1-8:8]", "A");
TEST() [9/48]
souffle::ram::test::TEST (Extend , CloneAndEquals)
Definition at line 107 of file ram_statement_equal_clone_test.cpp.
{
     // SWAP(A,B)
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Swap a("A", "B");
     Swap b("A", "B");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Swap* c = a.clone();
     EXPECT_EQ(a, *c);
TEST() [10/48]
souffle::ram::test::TEST (False , CloneAndEquals)
Definition at line 66 of file ram_condition_equal_clone_test.cpp.
{
     // true /\ false
     auto a = mk<Conjunction>(mk<True>(), mk<False>());
     auto b = mk<Conjunction>(mk<True>(), mk<False>());
     EXPECT_EQ(*a, *b);
     EXPECT_NE(a, b);
     Own<Conjunction> c(a->clone());
     EXPECT_EQ(*a, *c);
     EXPECT_NE(a, c);
References b, EXPECT_EQ, and EXPECT_NE.
TEST() [11/48]
souffle::ram::test::TEST (IntrinsicOperator , CloneAndEquals)
Definition at line 51 of file ram_expression_equal_clone_test.cpp.
{
     // define binary functor NE check if two Expressions are not equal
     // NE(number(1), number(10))
     VecOwn<Expression> a_args;
     a_args.emplace_back(new SignedConstant(1));
     a_args.emplace_back(new SignedConstant(10));
     UserDefinedOperator a("NE", {TypeAttribute::Signed, TypeAttribute::Signed}, TypeAttribute::Signed, false,
             std::move(a_args));
     VecOwn<Expression> b_args;
     b_args.emplace_back(new SignedConstant(1));
TEST() [12/48]
souffle::ram::test::TEST (IO1 , CloneAndEquals)
Definition at line 77 of file ram_statement_equal_clone_test.cpp.
{
     // CLEAR A
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Clear a("A");
     Clear b("A");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Clear* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
TEST() [13/48]
souffle::ram::test::TEST (LogRelationTimer , CloneAndEquals)
Definition at line 331 of file ram_statement_equal_clone_test.cpp.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     /*
      * START_TIMER "@runtime"
      *   IO .. (..)
      * END_TIMER
      * */
     std::map<std::string, std::string> a_IODir;
     std::map<std::string, std::string> b_IODir;
     LogTimer a(mk<IO>("A", std::move(a_IODir)), "@runtime");
     LogTimer b(mk<IO>("A", std::move(a_IODir)), "@runtime");
TEST() [14/48]
souffle::ram::test::TEST (LogSize , CloneAndEquals)
Definition at line 437 of file ram_statement_equal_clone_test.cpp.
TEST() [15/48]
souffle::ram::test::TEST (LogTimer , CloneAndEquals)
Definition at line 351 of file ram_statement_equal_clone_test.cpp.
{
     Relation edge(
             "edge", 4, 1, {"src", "dest", "a", "b"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     Relation path(
             "path", 4, 1, {"src", "dest", "a", "b"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     /* BEGIN_DEBUG "path(x,y,1,(@level_num_0+1)) :- \n   edge(x,y,_,@level_num_0).\nin file /edge.dl
      * [17:1-17:26];" QUERY FOR t0 IN edge IF (NOT (edge = )) IF (NOT (t0.0,t0.1,,)  path) PROJECT (t0.0,
      * t0.1, number(1), (t0.3+number(1))) INTO path END DEBUG
      * */
     VecOwn<Expression> a_project_list;
     a_project_list.emplace_back(new TupleElement(0, 0));
TEST() [16/48]
souffle::ram::test::TEST (Loop , CloneAndEquals)
Definition at line 279 of file ram_statement_equal_clone_test.cpp.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // EXIT (A = )
     Exit a(mk<EmptinessCheck>("A"));
     Exit b(mk<EmptinessCheck>("A"));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Exit* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
TEST() [17/48]
souffle::ram::test::TEST (Negation , CloneAndEquals)
Definition at line 116 of file ram_condition_equal_clone_test.cpp.
{
     // constraint t0.1 = t1.0
     Own<Expression> a_lhs(new TupleElement(0, 1));
     Own<Expression> a_rhs(new TupleElement(1, 0));
     Own<Constraint> a(new Constraint(BinaryConstraintOp::EQ, std::move(a_lhs), std::move(a_rhs)));
     Own<Expression> b_lhs(new TupleElement(0, 1));
     Own<Expression> b_rhs(new TupleElement(1, 0));
     Own<Constraint> b(new Constraint(BinaryConstraintOp::EQ, std::move(b_lhs), std::move(b_rhs)));
     EXPECT_EQ(*a, *b);
     EXPECT_NE(a, b);
TEST() [18/48]
souffle::ram::test::TEST (PackRecord , CloneAndEquals)
Definition at line 160 of file ram_expression_equal_clone_test.cpp.
{
     SubroutineArgument a(2);
     SubroutineArgument b(2);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     SubroutineArgument* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [19/48]
souffle::ram::test::TEST (Parallel , CloneAndEquals)
Definition at line 237 of file ram_statement_equal_clone_test.cpp.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     /*
      * LOOP
      *  QUERY
      *   FOR t0 IN A
      *    IF t0.0 = 4 BREAK
      *    PROJECT (t0.0) INTO B
      * END LOOP
      * */
     VecOwn<Expression> a_expressions;
TEST() [20/48]
souffle::ram::test::TEST (Query , CloneAndEquals)
Definition at line 137 of file ram_statement_equal_clone_test.cpp.
{
     // no statements in the sequence
     Sequence a;
     Sequence b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     Sequence* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
TEST() [21/48]
souffle::ram::test::TEST (RamAggregate , CloneAndEquals)
Definition at line 346 of file ram_operation_equal_clone_test.cpp.
{
     Relation sqrt("sqrt", 2, 1, {"nth", "value"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // t0.0 = MIN t1.1 SEARCH t1 IN sqrt ON INDEX t1.0 =  AND t1.1 =
     // WHERE t1.1 > 80
     //  RETURN t0.0
TEST() [22/48]
souffle::ram::test::TEST (RamBreak , CloneAndEquals)
Definition at line 462 of file ram_operation_equal_clone_test.cpp.
{
     Relation A("A", 2, 1, {"a", "b"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // PROJECT (t0.1, t0.3) INTO A
     VecOwn<Expression> a_args;
     a_args.emplace_back(new TupleElement(0, 1));
TEST() [23/48]
souffle::ram::test::TEST (RamChoice , CloneAndEquals)
Definition at line 184 of file ram_operation_equal_clone_test.cpp.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // parallel choose an edge not adjcent to vertex 5
     // PARALLEL CHOICE t1 IN edge WHERE NOT t1.0 = 5 AND NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
TEST() [24/48]
souffle::ram::test::TEST (RamFilter , CloneAndEquals)
Definition at line 434 of file ram_operation_equal_clone_test.cpp.
{
     Relation A("A", 1, 1, {"a"}, {"i"}, RelationRepresentation::DEFAULT);
     // IF (A = ) BREAK
     // RETURN number(0)
     VecOwn<Expression> a_return_args;
TEST() [25/48]
souffle::ram::test::TEST (RamIndexAggregate , CloneAndEquals)
Definition at line 368 of file ram_operation_equal_clone_test.cpp.
{
     // UNPACK (t0.0, t0.2) INTO t1
     // RETURN number(0)
     VecOwn<Expression> a_return_args;
     a_return_args.emplace_back(new SignedConstant(0));
TEST() [26/48]
souffle::ram::test::TEST (RamIndexChoice , CloneAndEquals)
Definition at line 264 of file ram_operation_equal_clone_test.cpp.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // PARALLEL FOR t1 IN edge ON INDEX t1.x = 5 AND t1.y =
     // WHERE NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
TEST() [27/48]
souffle::ram::test::TEST (RamIndexScan , CloneAndEquals)
Definition at line 110 of file ram_operation_equal_clone_test.cpp.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     Relation new_edge("new_edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // get edges direct to vertex 5
     // PARALLEL FOR t1 IN edge ON INDEX t1.x =  AND t1.y = 5
TEST() [28/48]
souffle::ram::test::TEST (RamiParallelIndexChoice , CloneAndEquals)
Definition at line 305 of file ram_operation_equal_clone_test.cpp.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // t0.0 = COUNT FOR ALL t1 IN edge
     //  RETURN t0.0
     VecOwn<Expression> a_return_args;
TEST() [29/48]
souffle::ram::test::TEST (RamParallelChoice , CloneAndEquals)
Definition at line 224 of file ram_operation_equal_clone_test.cpp.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // FOR t1 IN edge ON INDEX t1.x = 5 AND t1.y =
     // WHERE NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
TEST() [30/48]
souffle::ram::test::TEST (RamParallelIndexScan , CloneAndEquals)
Definition at line 146 of file ram_operation_equal_clone_test.cpp.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // choose an edge not adjcent to vertex 5
     // CHOICE t1 IN edge WHERE NOT t1.0 = 5 AND NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
TEST() [31/48]
souffle::ram::test::TEST (RamParallelScan , CloneAndEquals)
Definition at line 87 of file ram_operation_equal_clone_test.cpp.
{
     Relation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     Relation vertex("vertex", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // get vertices contain self loop
     // FOR t1 IN edge ON INDEX t1.x = t1.1 AND t1.y =
TEST() [32/48]
souffle::ram::test::TEST (RamProject , CloneAndEquals)
Definition at line 484 of file ram_operation_equal_clone_test.cpp.
{
     // RETURN (t0.1, t0.2)
     VecOwn<Expression> a_args;
     a_args.emplace_back(new TupleElement(0, 1));
     a_args.emplace_back(new TupleElement(0, 2));
TEST() [33/48]
souffle::ram::test::TEST (RamProvenanceExistCheck , CloneAndEquals)
Definition at line 208 of file ram_condition_equal_clone_test.cpp.
                                       {"state", "postCode", "street"}, {"s", "i", "s"},
             RelationRepresentation::DEFAULT);
     VecOwn<Expression> tuple_d;
     tuple_d.emplace_back(new SignedConstant(0));
     tuple_d.emplace_back(new SignedConstant(2000));
     tuple_d.emplace_back(new SignedConstant(0));
     ProvenanceExistenceCheck d("address", std::move(tuple_d));
     VecOwn<Expression> tuple_e;
     tuple_e.emplace_back(new SignedConstant(0));
     tuple_e.emplace_back(new SignedConstant(2000));
     tuple_e.emplace_back(new SignedConstant(0));
     ProvenanceExistenceCheck e("address", std::move(tuple_e));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     ProvenanceExistenceCheck* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_EQ(e, *f);
     EXPECT_NE(&d, f);
     EXPECT_NE(&e, f);
     delete f;
 }
 TEST(EmptinessCheck, CloneAndEquals) {
     // Check A(x:number)
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     EmptinessCheck a("A");
     EmptinessCheck b("A");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     EmptinessCheck* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_EQ(b, *c);
     EXPECT_NE(&a, c);
TEST() [34/48]
souffle::ram::test::TEST (RamScan , CloneAndEquals)
Definition at line 64 of file ram_operation_equal_clone_test.cpp.
{
     Relation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // PARALLEL FOR t0 in A
     //  RETURN number(0)
     VecOwn<Expression> a_return_args;
TEST() [35/48]
souffle::ram::test::TEST (RamSubrountineArgument , CloneAndEquals)
Definition at line 212 of file ram_expression_equal_clone_test.cpp.
TEST() [36/48]
souffle::ram::test::TEST (RamSubroutineReturn , CloneAndEquals)
Definition at line 505 of file ram_operation_equal_clone_test.cpp.
TEST() [37/48]
souffle::ram::test::TEST (RamUnpackedRecord , CloneAndEquals)
Definition at line 405 of file ram_operation_equal_clone_test.cpp.
{
     Relation A("A", 1, 1, {"a"}, {"i"}, RelationRepresentation::DEFAULT);
     // IF (NOT t0.1 in A)
     // RETURN number(0)
     VecOwn<Expression> a_return_args;
TEST() [38/48]
souffle::ram::test::TEST (randomConversions , RamFloat)
Definition at line 63 of file ram_type_conversion_test.cpp.
TEST() [39/48]
souffle::ram::test::TEST (randomConversions , RamSigned)
Definition at line 33 of file ram_type_conversion_test.cpp.
{
     std::mt19937 randomGenerator(3);
     std::uniform_int_distribution<RamUnsigned> dist(0, 1000);
     for (int i = 0; i < NUMBER_OF_CONVERSION_TESTS; ++i) {
TEST() [40/48]
souffle::ram::test::TEST (randomConversions , RamUnsigned)
Definition at line 48 of file ram_type_conversion_test.cpp.
{
     std::mt19937 randomGenerator(3);
     std::uniform_real_distribution<RamFloat> dist(-100.0, 100.0);
     for (int i = 0; i < NUMBER_OF_CONVERSION_TESTS; ++i) {
TEST() [41/48]
souffle::ram::test::TEST (Relation , CloneAndEquals)
Definition at line 39 of file ram_relation_equal_clone_test.cpp.
TEST() [42/48]
souffle::ram::test::TEST (Sequence , CloneAndEquals)
Definition at line 196 of file ram_statement_equal_clone_test.cpp.
                           {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // one statement in the sequence
     // CLEAR A
     Sequence d(mk<Clear>("A"));
     Sequence e(mk<Clear>("A"));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     Sequence* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_NE(&d, f);
     delete f;
     // multiple statements in the sequence
     // IO A ()
     // CLEAR A
     std::map<std::string, std::string> g_load_IODir;
     std::map<std::string, std::string> h_load_IODir;
     Sequence g(mk<IO>("A", std::move(g_load_IODir)), mk<Clear>("A"));
     Sequence h(mk<IO>("A", std::move(h_load_IODir)), mk<Clear>("A"));
     EXPECT_EQ(g, h);
     EXPECT_NE(&g, &h);
     Sequence* i = g.clone();
     EXPECT_EQ(g, *i);
     EXPECT_NE(&g, i);
     delete i;
 }
 TEST(Parallel, CloneAndEquals) {
     Relation A("A", 3, 1, {"a", "b", "c"}, {"i", "s", "i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 2, 1, {"a", "c"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     /* PARALLEL
      *  QUERY
      *   FOR t0 IN A
      *    IF (t0.0 > 0)
      *     PROJECT (t0.0, t0.2) INTO B
      * END PARALLEL
      * */
TEST() [43/48]
souffle::ram::test::TEST (SignedConstant , CloneAndEquals)
Definition at line 123 of file ram_expression_equal_clone_test.cpp.
{
     AutoIncrement a;
     AutoIncrement b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     AutoIncrement* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
References b, souffle::ram::AutoIncrement::clone(), EXPECT_EQ, and EXPECT_NE.
TEST() [44/48]
souffle::ram::test::TEST (Swap , CloneAndEquals)
Definition at line 122 of file ram_statement_equal_clone_test.cpp.
{
     Relation A("A", 3, 1, {"a", "b", "c"}, {"i", "s", "i"}, RelationRepresentation::DEFAULT);
     Relation B("B", 2, 1, {"a", "c"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     /*
      * QUERY
      *  FOR t0 IN A
      *   PROJECT (t0.0, t0.2) INTO B
      */
     VecOwn<Expression> a_expressions;
     a_expressions.emplace_back(new TupleElement(0, 0));
     a_expressions.emplace_back(new TupleElement(0, 2));
TEST() [45/48]
souffle::ram::test::TEST (True , CloneAndEquals)
Definition at line 54 of file ram_condition_equal_clone_test.cpp.
{
     False a;
     False b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     False* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
References b, souffle::ram::False::clone(), EXPECT_EQ, and EXPECT_NE.
TEST() [46/48]
souffle::ram::test::TEST (TupleElement , CloneAndEquals)
Definition at line 110 of file ram_expression_equal_clone_test.cpp.
{
     // number(5)
     SignedConstant a(5);
     SignedConstant b(5);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     SignedConstant* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
References b, souffle::ram::SignedConstant::clone(), EXPECT_EQ, and EXPECT_NE.
TEST() [47/48]
souffle::ram::test::TEST (UndefValue , CloneAndEquals)
Definition at line 148 of file ram_expression_equal_clone_test.cpp.
{
     // {number{10), number(5), , }
     VecOwn<Expression> a_args;
     a_args.emplace_back(new SignedConstant(10));
     a_args.emplace_back(new SignedConstant(5));
     a_args.emplace_back(new UndefValue);
     a_args.emplace_back(new UndefValue);
     PackRecord a(std::move(a_args));
     VecOwn<Expression> b_args;
     b_args.emplace_back(new SignedConstant(10));
TEST() [48/48]
souffle::ram::test::TEST (UserDefinedOperator , CloneAndEquals)
Definition at line 87 of file ram_expression_equal_clone_test.cpp.
                                 {TypeAttribute::Signed, TypeAttribute::Signed}, TypeAttribute::Signed, false,
             std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     UserDefinedOperator* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
 TEST(TupleElement, CloneAndEquals) {
     // t0.1
     TupleElement a(0, 1);
     TupleElement b(0, 1);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     TupleElement* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
References souffle::Signed.