souffle: souffle::interpreter::RelationWrapper Struct Reference
souffle::interpreter::RelationWrapper Struct Reference abstract
Wrapper for InterpreterRelation.
#include <Relation.h>
Data Structures
class Iterator
The iterator interface.
class iterator_base
A virtualized iterator class that can be used by the Proginterface.
Public Types
using arity_type = souffle::Relation::arity_type
using IndexViewPtr = Own< ViewWrapper >
Public Member Functions
virtual Iterator begin () const =0
virtual bool contains (const RamDomain *) const =0
virtual IndexViewPtr createView (const size_t &) const =0
Obtains a view on an index of this relation, facilitating hint-supported accesses.
virtual Iterator end () const =0
arity_type getArity () const
arity_type getAuxiliaryArity () const
virtual Order getIndexOrder (size_t) const =0
Return the order of an index.
const std::string & getName () const
virtual void insert (const RamDomain *)=0
virtual void purge ()=0
RelationWrapper (arity_type arity, arity_type auxiliaryArity, std::string relName)
virtual size_t size () const =0
virtual ~RelationWrapper ()=default
Protected Attributes
arity_type arity
arity_type auxiliaryArity
std::string relName
Detailed Description
Wrapper for InterpreterRelation.
This class unifies the InterpreterRelation template classes. It also defines virtual interfaces for ProgInterface and some virtual helper functions for interpreter execution.
Definition at line 48 of file Relation.h.
Member Typedef Documentation
arity_type
using souffle::interpreter::RelationWrapper::arity_type = souffle::Relation::arity_type
Definition at line 55 of file Relation.h.
IndexViewPtr
using souffle::interpreter::RelationWrapper::IndexViewPtr = Own<ViewWrapper>
Definition at line 141 of file Relation.h.
Constructor & Destructor Documentation
RelationWrapper()
souffle::interpreter::RelationWrapper::RelationWrapper (arity_type arity, arity_type auxiliaryArity, std::string relName) inline
Definition at line 58 of file Relation.h.
           :
         virtual ~iterator_base() = default;
~RelationWrapper()
virtual souffle::interpreter::RelationWrapper::~RelationWrapper () virtual default
Member Function Documentation
begin()
virtual Iterator souffle::interpreter::RelationWrapper::begin () const pure virtual
Implemented in souffle::interpreter::Relation< _Arity, Structure >.
Referenced by souffle::interpreter::Relation< 2, Eqrel >::castView().
contains()
virtual bool souffle::interpreter::RelationWrapper::contains (const RamDomain *) const pure virtual
Implemented in souffle::interpreter::Relation< _Arity, Structure >, and souffle::interpreter::Relation< 2, Eqrel >.
Referenced by souffle::interpreter::RelInterface::RelInterface().
createView()
virtual IndexViewPtr souffle::interpreter::RelationWrapper::createView (const size_t &) const pure virtual
Obtains a view on an index of this relation, facilitating hint-supported accesses.
This function is virtual because view creation require at least one indirect dispatch.
Implemented in souffle::interpreter::Relation< _Arity, Structure >, and souffle::interpreter::Relation< 2, Eqrel >.
end()
virtual Iterator souffle::interpreter::RelationWrapper::end () const pure virtual
Implemented in souffle::interpreter::Relation< _Arity, Structure >.
getArity()
arity_type souffle::interpreter::RelationWrapper::getArity () const inline
Definition at line 131 of file Relation.h.
          :
     std::string relName;
getAuxiliaryArity()
arity_type souffle::interpreter::RelationWrapper::getAuxiliaryArity () const inline
Definition at line 135 of file Relation.h.
          :
     std::string relName;
getIndexOrder()
virtual Order souffle::interpreter::RelationWrapper::getIndexOrder (size_t) const pure virtual
Return the order of an index.
Implemented in souffle::interpreter::Relation< _Arity, Structure >, and souffle::interpreter::Relation< 2, Eqrel >.
getName()
const std::string& souffle::interpreter::RelationWrapper::getName () const inline
Definition at line 127 of file Relation.h.
       :
     using IndexViewPtr = Own<ViewWrapper>;
insert()
virtual void souffle::interpreter::RelationWrapper::insert (const RamDomain *) pure virtual
Implemented in souffle::interpreter::Relation< _Arity, Structure >, and souffle::interpreter::Relation< 2, Eqrel >.
purge()
virtual void souffle::interpreter::RelationWrapper::purge () pure virtual
Implemented in souffle::interpreter::Relation< _Arity, Structure >, and souffle::interpreter::Relation< 2, Eqrel >.
size()
virtual size_t souffle::interpreter::RelationWrapper::size () const pure virtual
Implemented in souffle::interpreter::Relation< _Arity, Structure >.
Referenced by souffle::interpreter::RelInterface::getAttrType().
Field Documentation
arity
arity_type souffle::interpreter::RelationWrapper::arity protected
Definition at line 158 of file Relation.h.
auxiliaryArity
arity_type souffle::interpreter::RelationWrapper::auxiliaryArity protected
Definition at line 159 of file Relation.h.
relName
std::string souffle::interpreter::RelationWrapper::relName protected
Definition at line 156 of file Relation.h.
Referenced by souffle::interpreter::RelationWrapper::Iterator::operator!=().
The documentation for this struct was generated from the following file:
interpreter/Relation.h