souffle: souffle::ast::analysis::TypeVisitor< R > Struct Template Reference
souffle::ast::analysis::TypeVisitor< R > Struct Template Reference
A visitor for Types.
Public Member Functions
R operator() (const Type &type) const
virtual R visit (const Type &type) const
virtual R visitType (const Type &) const
virtual ~TypeVisitor ()=default
Detailed Description
template<typename R>
struct souffle::ast::analysis::TypeVisitor< R >
A visitor for Types.
Definition at line 93 of file TypeSystem.cpp.
Constructor & Destructor Documentation
~TypeVisitor()
template<typename R > virtual souffle::ast::analysis::TypeVisitor< R >::~TypeVisitor () virtual default
Referenced by souffle::ast::analysis::TypeEnvironment::getType().
Member Function Documentation
operator()()
template<typename R > R souffle::ast::analysis::TypeVisitor< R >::operator() (const Type & type) const inline
Definition at line 96 of file TypeSystem.cpp.
{
         FORWARD(Constant);
References FORWARD.
Referenced by souffle::ast::analysis::TypeEnvironment::getType().
visit()
template<typename R > virtual R souffle::ast::analysis::TypeVisitor< R >::visit (const Type & type) const inline virtual
Reimplemented in souffle::ast::analysis::VisitOnceTypeVisitor< R >.
Definition at line 103 of file TypeSystem.cpp.
                                                               { \
         return visitType(type);                                 \
     }
Referenced by souffle::ast::analysis::TypeEnvironment::getType().
visitType()
template<typename R > virtual R souffle::ast::analysis::TypeVisitor< R >::visitType (const Type &) const inline virtual
Definition at line 125 of file TypeSystem.cpp.
                            : public TypeVisitor<R> {
References souffle::ast::analysis::VisitOnceTypeVisitor< R >::seen, and souffle::ast::analysis::VisitOnceTypeVisitor< R >::visit().
The documentation for this struct was generated from the following file:
ast/analysis/TypeSystem.cpp