/*
 * Souffle - A Datalog Compiler
 * Copyright (c) 2021 The Souffle Developers. All rights reserved
 * Licensed under the Universal Permissive License v 1.0 as shown at:
 * - https://opensource.org/licenses/UPL
 * - <souffle root>/licenses/SOUFFLE-UPL.txt
 */

// Tests whether ADT access is working correctly

////////////
// Test 1 //
////////////

.type ADT1 = br1 {x : number, y :number}

.decl A(e:ADT1)
A($br1(1, 2)).

.decl test1()
test1() :-
   A($br1(1, 2)).

////////////
// Test 2 //
////////////

.type ADT2 = br2 {x : number}

.decl B(e:ADT2)
B($br2(1)).

.decl test2()
test2() :-
   B($br2(1)).

////////////
// Test 3 //
////////////

.type ADT3 = br3 {x : number, y :number}

.decl C(e:ADT3)
C($br3(1, 2)).

.decl D(e:number,b:number)
D(left,right) :-
   C($br3(left, right)).

.decl test3()
test3() :-
   D(1,2).

////////////
// Test 4 //
////////////

.type ADT4 = br4 {x : number}

.decl E(e:ADT4)
E($br4(1)).

.decl F(b:number)
F(left) :-
   E($br4(left)).

.decl test4()
test4() :-
   F(1).

////////////
// Test 5 //
////////////

.type ADT5 = br5 {} | br6 {}

.decl G(x:ADT5)
G($br5()).
G($br6()).

.decl test5()
test5() :-
   G($br5()),
   G($br6()).

.output test1, test2, test3, test4, test5
