// Souffle - A Datalog Compiler
// Copyright (c) 2021, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// building a shortest-path tree for a simple graph
// with multiple subsumptive rules

.decl A(from:number, to:number, z:number) btree_delete
.output A

.decl graph(from:number, to:number)

graph(1, 2).
graph(1, 3).
graph(3, 4).
graph(2, 5).
graph(4, 6).
graph(5, 6).
graph(6, 7).

A(1, 2, 1).
A(1, 3, 1).

A(from, to, c+1) :-
    A(_, from, c),
    graph(from, to).

A(from, to, c1) <= A(_, to, c2) :-
    c1 > c2.

A(from1, to, c) <= A(from2, to, c) :-
    from1 > from2.