// Souffle - A Datalog Compiler
// Copyright (c) 2021, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

.pragma "disable-transformers" "ResolveAliasesTransformer"

.decl words (i:number, w:symbol)
.decl bigram (w:symbol, w1:symbol)

.input words

bigram(w, w1) :-
   words(i,w),
   words(i+1,w1).

.output bigram
