// Souffle - A Datalog Compiler
// Copyright (c) 2017, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test if sqlite3 IO works with null columns

.decl A(x:symbol)
// Read in from sqlite3 (assumes relative path to test dir is correct
.input A(IO=sqlite,filename="A.sqlite.input")
.printsize A
