macro(ADD_SOUFFLE_BINARY_TEST TEST_NAME)
    add_executable(${TEST_NAME} ${TEST_NAME}.cpp)
    target_link_libraries(${TEST_NAME} libsouffle)
    add_test(NAME ${TEST_NAME} COMMAND ${TEST_NAME})
endmacro()
